// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.25/esri/copyright.txt for details.
//>>built
define("../../chunks/_rollupPluginBabelHelpers ../../chunks/tslib.es6 ../../core/Error ../../core/jsonMap ../../core/Logger ../../core/screenUtils ../../core/accessorSupport/decorators/property ../../core/arrayUtils ../../core/accessorSupport/decorators/cast ../../core/accessorSupport/decorators/reader ../../core/accessorSupport/decorators/subclass ../../core/accessorSupport/decorators/writer ./VisualVariable ./support/SizeStop ./support/SizeVariableLegendOptions ./support/sizeVariableUtils ./support/visualVariableUtils".split(" "),
function(u,c,z,v,n,A,d,p,w,q,B,C,D,E,F,k,G){function x(e){if(null!=e){if("string"===typeof e||"number"===typeof e)return A.toPt(e);if("size"===e.type){if(k.isSizeVariable(e))return e;e={...e};delete e.type;return new b(e)}}}function y(e,m,g){if("object"!==typeof e)return e;m=new b;m.read(e,g);return m}var r;p=new v.JSONMap({width:"width",depth:"depth",height:"height",widthAndDepth:"width-and-depth",all:"all"});const t=new v.JSONMap({unknown:"unknown",inch:"inches",foot:"feet",yard:"yards",mile:"miles",
"nautical-mile":"nautical-miles",millimeter:"millimeters",centimeter:"centimeters",decimeter:"decimeters",meter:"meters",kilometer:"kilometers","decimal-degree":"decimal-degrees"});let b=r=function(e){function m(a){a=e.call(this,a)||this;a.axis=null;a.legendOptions=null;a.normalizationField=null;a.scaleBy=null;a.target=null;a.type="size";a.useSymbolValue=null;a.valueExpression=null;a.valueRepresentation=null;a.valueUnit=null;return a}u._inheritsLoose(m,e);var g=m.prototype;g.castMaxSize=function(a){return x(a)};
g.readMaxSize=function(a,f,l){return y(a,f,l)};g.castMinSize=function(a){return x(a)};g.readMinSize=function(a,f,l){return y(a,f,l)};g.readValueExpression=function(a,f){return a||f.expression&&"$view.scale"};g.writeValueExpressionWebScene=function(a,f,l,h){"$view.scale"===a?h&&h.messages&&(a=this.index,h.messages.push(new z("property:unsupported",this.type+"VisualVariable.valueExpression \x3d '$view.scale' is not supported in Web Scene. Please remove this property to save the Web Scene.",{instance:this,
propertyName:("string"===typeof a?a:`visualVariables[${a}]`)+".valueExpression",context:h}))):f[l]=a};g.readValueUnit=function(a){return a?t.read(a):null};g.clone=function(){return new r({axis:this.axis,field:this.field,valueExpression:this.valueExpression,valueExpressionTitle:this.valueExpressionTitle,maxDataValue:this.maxDataValue,maxSize:k.isSizeVariable(this.maxSize)?this.maxSize.clone():this.maxSize,minDataValue:this.minDataValue,minSize:k.isSizeVariable(this.minSize)?this.minSize.clone():this.minSize,
normalizationField:this.normalizationField,stops:this.stops&&this.stops.map(a=>a.clone()),target:this.target,useSymbolValue:this.useSymbolValue,valueRepresentation:this.valueRepresentation,valueUnit:this.valueUnit,legendOptions:this.legendOptions&&this.legendOptions.clone()})};g.flipSizes=function(){if(this.transformationType===k.TransformationType.ClampedLinear){const {minSize:a,maxSize:f}=this;this.minSize=f;this.maxSize=a;return this}if(this.transformationType===k.TransformationType.Stops){const a=
this.stops;if(!a)return this;const f=a.map(h=>h.size).reverse(),l=a.length;for(let h=0;h<l;h++)a[h].size=f[h]}return this};g.getAttributeHash=function(){return`${e.prototype.getAttributeHash.call(this)}-${this.target}-${this.normalizationField}`};g._interpolateData=function(){return this.stops&&this.stops.map(a=>a.value||0)};u._createClass(m,[{key:"cache",get:function(){return{ipData:this._interpolateData(),hasExpression:!!this.valueExpression,compiledFunc:null,isScaleDriven:null!=this.valueExpression&&
G.viewScaleRE.test(this.valueExpression)}}},{key:"expression",set:function(a){n.getLogger(this.declaredClass).warn("'expression' is deprecated since version 4.2. Use 'valueExpression' instead. The only supported expression is 'view.scale'.");"view.scale"===a?(this.valueExpression="$view.scale",this._set("expression",a)):this._set("expression",null)}},{key:"index",set:function(a){k.isSizeVariable(this.maxSize)&&(this.maxSize.index=`visualVariables[${a}].maxSize`);k.isSizeVariable(this.minSize)&&(this.minSize.index=
`visualVariables[${a}].minSize`);this._set("index",a)}},{key:"inputValueType",get:function(){return k.getInputValueType(this)}},{key:"maxDataValue",set:function(a){a&&this.stops&&(n.getLogger(this.declaredClass).warn("cannot set maxDataValue when stops is not null."),a=null);this._set("maxDataValue",a)}},{key:"maxSize",set:function(a){a&&this.stops&&(n.getLogger(this.declaredClass).warn("cannot set maxSize when stops is not null."),a=null);this._set("maxSize",a)}},{key:"minDataValue",set:function(a){a&&
this.stops&&(n.getLogger(this.declaredClass).warn("cannot set minDataValue when stops is not null."),a=null);this._set("minDataValue",a)}},{key:"minSize",set:function(a){a&&this.stops&&(n.getLogger(this.declaredClass).warn("cannot set minSize when stops is not null."),a=null);this._set("minSize",a)}},{key:"arcadeRequired",get:function(){return this.valueExpression?!0:null!=this.minSize&&"object"===typeof this.minSize&&this.minSize.arcadeRequired||null!=this.maxSize&&"object"===typeof this.maxSize&&
this.maxSize.arcadeRequired}},{key:"stops",set:function(a){null==this.minDataValue&&null==this.maxDataValue&&null==this.minSize&&null==this.maxSize?a&&Array.isArray(a)&&(a=a.filter(f=>!!f),a.sort((f,l)=>f.value-l.value)):a&&(n.getLogger(this.declaredClass).warn("cannot set stops when one of minDataValue, maxDataValue, minSize or maxSize is not null."),a=null);this._set("stops",a)}},{key:"transformationType",get:function(){return k.getTransformationType(this,this.inputValueType)}}]);return m}(D);c.__decorate([d.property({readOnly:!0})],
b.prototype,"cache",null);c.__decorate([d.property({type:p.apiValues,json:{type:p.jsonValues,origins:{"web-map":{read:!1}},read:p.read,write:p.write}})],b.prototype,"axis",void 0);c.__decorate([d.property({type:String,value:null,json:{read:!1}})],b.prototype,"expression",null);c.__decorate([d.property()],b.prototype,"index",null);c.__decorate([d.property({type:String,readOnly:!0})],b.prototype,"inputValueType",null);c.__decorate([d.property({type:F,json:{write:!0}})],b.prototype,"legendOptions",void 0);
c.__decorate([d.property({type:Number,value:null,json:{write:!0}})],b.prototype,"maxDataValue",null);c.__decorate([d.property({type:Number,value:null,json:{write:!0}})],b.prototype,"maxSize",null);c.__decorate([w.cast("maxSize")],b.prototype,"castMaxSize",null);c.__decorate([q.reader("maxSize")],b.prototype,"readMaxSize",null);c.__decorate([d.property({type:Number,value:null,json:{write:!0}})],b.prototype,"minDataValue",null);c.__decorate([d.property({type:Number,value:null,json:{write:!0}})],b.prototype,
"minSize",null);c.__decorate([w.cast("minSize")],b.prototype,"castMinSize",null);c.__decorate([q.reader("minSize")],b.prototype,"readMinSize",null);c.__decorate([d.property({type:String,json:{write:!0}})],b.prototype,"normalizationField",void 0);c.__decorate([d.property({readOnly:!0})],b.prototype,"arcadeRequired",null);c.__decorate([d.property({type:String})],b.prototype,"scaleBy",void 0);c.__decorate([d.property({type:[E],value:null,json:{write:!0}})],b.prototype,"stops",null);c.__decorate([d.property({type:["outline"],
json:{write:!0}})],b.prototype,"target",void 0);c.__decorate([d.property({type:String,readOnly:!0})],b.prototype,"transformationType",null);c.__decorate([d.property({type:["size"],json:{type:["sizeInfo"]}})],b.prototype,"type",void 0);c.__decorate([d.property({type:Boolean,json:{write:!0,origins:{"web-map":{read:!1}}}})],b.prototype,"useSymbolValue",void 0);c.__decorate([d.property({type:String,json:{write:!0}})],b.prototype,"valueExpression",void 0);c.__decorate([q.reader("valueExpression",["valueExpression",
"expression"])],b.prototype,"readValueExpression",null);c.__decorate([C.writer("web-scene","valueExpression")],b.prototype,"writeValueExpressionWebScene",null);c.__decorate([d.property({type:["radius","diameter","area","width","distance"],json:{write:!0}})],b.prototype,"valueRepresentation",void 0);c.__decorate([d.property({type:t.apiValues,json:{write:t.write,origins:{"web-map":{read:!1},"web-scene":{write:!0}}}})],b.prototype,"valueUnit",void 0);c.__decorate([q.reader("valueUnit")],b.prototype,
"readValueUnit",null);return b=r=c.__decorate([B.subclass("esri.renderers.visualVariables.SizeVariable")],b)});