// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.25/esri/copyright.txt for details.
//>>built
define(["exports","../lib/parser","../lib/types","../lib/scanner"],function(a,b,c,d){a.DiagnosticCodes=void 0;b=a.DiagnosticCodes||(a.DiagnosticCodes={});b.AlreadyDefined="AlreadyDefined";b.ApiConflict="ApiConflict";b.AssignedNeverUsed="AssignedNeverUsed";b.DefinedNeverAssigned="DefinedNeverAssigned";b.DefinedNeverUsed="DefinedNeverUsed";b.EmptyBlockStatement="EmptyBlockStatement";b.ExecutionError="ExecutionError";b.ProfileVariablesConflict="ProfileVariablesConflict";b.ProfileVariablesAreImmutable=
"ProfileVariablesAreImmutable";b.InvalidCallIdentifier="InvalidCallIdentifier";b.InvalidConstantIdentifier="InvalidConstantIdentifier";b.InvalidPropertyIdentifier="InvalidPropertyIdentifier";b.UnknownPropertyIdentifier="UnknownPropertyIdentifier";b.NoArgumentExpected="NoArgumentExpected";b.NotDefined="NotDefined";b.NotADictionary="NotADictionary";b.NotEnoughArguments="NotEnoughArguments";b.TooManyArguments="TooManyArguments";b.UnexpectedEmptyFunction="UnexpectedEmptyFunction";b.UnexpectedPropertyIdentifier=
"UnexpectedPropertyIdentifier";a.DiagnosticMessages={[a.DiagnosticCodes.ExecutionError]:"Execution Error: '${stack}'",[a.DiagnosticCodes.NoArgumentExpected]:"Expecting no argument",[a.DiagnosticCodes.NotEnoughArguments]:"Expecting at least ${min} argument(s)",[a.DiagnosticCodes.TooManyArguments]:"Too many arguments, expecting ${max}",[a.DiagnosticCodes.UnexpectedEmptyFunction]:"Unexpected empty function '${identifier}'",[a.DiagnosticCodes.NotDefined]:"'${identifier}' is not defined",[a.DiagnosticCodes.AlreadyDefined]:"'${identifier}' is already defined",
[a.DiagnosticCodes.ApiConflict]:"'${identifier}' is already defined as an Arcade constant or function",[a.DiagnosticCodes.ProfileVariablesConflict]:"'${identifier}' is already defined as a profile variable",[a.DiagnosticCodes.ProfileVariablesAreImmutable]:"Profile variables cannot be modified",[a.DiagnosticCodes.EmptyBlockStatement]:"Empty block statement",[a.DiagnosticCodes.AssignedNeverUsed]:"'${identifier}' is assigned but never used",[a.DiagnosticCodes.DefinedNeverUsed]:"'${identifier}' is defined but never used",
[a.DiagnosticCodes.DefinedNeverAssigned]:"'${identifier}' is defined but never assigned",[a.DiagnosticCodes.InvalidConstantIdentifier]:"Invalid constant identifier, expecting ${list}",[a.DiagnosticCodes.InvalidPropertyIdentifier]:"Invalid property identifier, expecting ${list}",[a.DiagnosticCodes.UnknownPropertyIdentifier]:"Unknown property identifier '${identifier}'",[a.DiagnosticCodes.NotADictionary]:"'${identifier}' doesn't have properties",[a.DiagnosticCodes.UnexpectedPropertyIdentifier]:"Unexpected property identifier",
[c.ParsingErrorCodes.ForInOfLoopInitializer]:"Variable in for-in loop cannot be initialized",[c.ParsingErrorCodes.IdentiferExpected]:"Identifier expected",[c.ParsingErrorCodes.InvalidEscapedReservedWord]:"Keyword cannot contain escaped characters",[c.ParsingErrorCodes.InvalidExpression]:"Invalid expression",[c.ParsingErrorCodes.InvalidFunctionIdentifier]:"Invalid function identifier",[c.ParsingErrorCodes.InvalidHexEscapeSequence]:"Invalid hexadecimal escape sequence",[c.ParsingErrorCodes.InvalidLeftHandSideInAssignment]:"Invalid left-hand side in assignment",
[c.ParsingErrorCodes.InvalidLeftHandSideInForIn]:"Invalid left-hand side in for-in",[c.ParsingErrorCodes.InvalidTemplateHead]:"Invalid template structure",[c.ParsingErrorCodes.InvalidVariableAssignment]:"Invalid variable assignment",[c.ParsingErrorCodes.KeyMustBeString]:"Object keys must be a string",[c.ParsingErrorCodes.NoFunctionInsideFunction]:"Functions cannot be declared inside another function",[c.ParsingErrorCodes.PunctuatorExpected]:"'${value}' expected",[c.ParsingErrorCodes.TemplateOctalLiteral]:"Octal literals are not allowed in template strings.",
[c.ParsingErrorCodes.UnexpectedEndOfScript]:"Unexpected end of script",[c.ParsingErrorCodes.UnexpectedIdentifier]:"Unexpected identifier",[c.ParsingErrorCodes.UnexpectedNumber]:"Unexpected number",[c.ParsingErrorCodes.UnexpectedString]:"Unexpected string",[c.ParsingErrorCodes.UnexpectedTemplate]:"Unexpected quasi '${value}'",[c.ParsingErrorCodes.UnexpectedToken]:"Unexpected token"};Object.defineProperties(a,{__esModule:{value:!0},[Symbol.toStringTag]:{value:"Module"}})});