// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.25/esri/copyright.txt for details.
//>>built
define(["exports","../../../core/maybe","../../../geometry/support/zscale","../../../layers/graphics/featureConversionUtils"],function(l,h,p,m){function q(e,c){return c}function k(e,c,a,b){switch(a){case 0:return g(e,c+b,0);case 1:return"lowerLeft"===e.originPosition?g(e,c+b,1):r(e,c+b,1)}}function n(e,c,a,b){switch(a){case 2:return g(e,c,2);default:return k(e,c,a,b)}}function t(e,c,a,b){switch(a){case 2:return g(e,c,3);default:return k(e,c,a,b)}}function u(e,c,a,b){switch(a){case 3:return g(e,c,
3);default:return n(e,c,a,b)}}function g({translate:e,scale:c},a,b){return e[b]+a*c[b]}function r({translate:e,scale:c},a,b){return e[b]-a*c[b]}let v=function(){function e(a){this._options=a;this.geometryTypes=["esriGeometryPoint","esriGeometryMultipoint","esriGeometryPolyline","esriGeometryPolygon"];this._previousCoordinate=[0,0];this._transform=null;this._applyTransform=q;this._lengths=[];this._vertexDimension=this._toAddInCurrentPath=this._currentLengthIndex=0;this._coordinateBuffer=null;this._coordinateBufferPtr=
0;this._attributesConstructor=function(){return function(){}}()}var c=e.prototype;c.createFeatureResult=function(){return{fields:[],features:[]}};c.finishFeatureResult=function(a){this._options.applyTransform&&(a.transform=null);this._attributesConstructor=function(){return function(){}}();this._coordinateBuffer=null;this._lengths.length=0;if(a.hasZ){var b=p.getGeometryZScaler(a.geometryType,this._options.sourceSpatialReference,a.spatialReference);if(!h.isNone(b))for(const d of a.features)b(d.geometry)}};
c.createSpatialReference=function(){return{}};c.addField=function(a,b){a=a.fields;h.assertIsSome(a);a.push(b);const d=a.map(f=>f.name);this._attributesConstructor=function(){for(const f of d)this[f]=null}};c.addFeature=function(a,b){a.features.push(b)};c.prepareFeatures=function(a){this._transform=a.transform;this._options.applyTransform&&a.transform&&(this._applyTransform=this._deriveApplyTransform(a));this._vertexDimension=2;a.hasZ&&this._vertexDimension++;a.hasM&&this._vertexDimension++;switch(a.geometryType){case "esriGeometryPoint":this.addCoordinate=
(b,d,f)=>this.addCoordinatePoint(b,d,f);this.createGeometry=b=>this.createPointGeometry(b);break;case "esriGeometryPolygon":this.addCoordinate=(b,d,f)=>this._addCoordinatePolygon(b,d,f);this.createGeometry=b=>this._createPolygonGeometry(b);break;case "esriGeometryPolyline":this.addCoordinate=(b,d,f)=>this._addCoordinatePolyline(b,d,f);this.createGeometry=b=>this._createPolylineGeometry(b);break;case "esriGeometryMultipoint":this.addCoordinate=(b,d,f)=>this._addCoordinateMultipoint(b,d,f),this.createGeometry=
b=>this._createMultipointGeometry(b)}};c.createFeature=function(){this._currentLengthIndex=this._lengths.length=0;this._previousCoordinate[0]=0;this._previousCoordinate[1]=0;this._coordinateBuffer=null;this._coordinateBufferPtr=0;return{attributes:new this._attributesConstructor}};c.allocateCoordinates=function(){};c.addLength=function(a,b,d){0===this._lengths.length&&(this._toAddInCurrentPath=b);this._lengths.push(b)};c.addQueryGeometry=function(a,b){const {queryGeometry:d,queryGeometryType:f}=b;
b=m.unquantizeOptimizedGeometry(d.clone(),d,!1,!1,this._transform);b=m.convertToGeometry(b,f,!1,!1);a.queryGeometryType=f;a.queryGeometry={...b}};c.createPointGeometry=function(a){const b={x:0,y:0,spatialReference:a.spatialReference};a.hasZ&&(b.z=0);a.hasM&&(b.m=0);return b};c.addCoordinatePoint=function(a,b,d){const f=h.unwrapOrThrow(this._transform,"transform");b=this._applyTransform(f,b,d,0);switch(d){case 0:a.x=b;break;case 1:a.y=b;break;case 2:"z"in a?a.z=b:a.m=b;break;case 3:a.m=b}};c._transformPathLikeValue=
function(a,b){let d=0;1>=b&&(d=this._previousCoordinate[b],this._previousCoordinate[b]+=a);const f=h.unwrapOrThrow(this._transform,"transform");return this._applyTransform(f,a,b,d)};c._addCoordinatePolyline=function(a,b,d){this._dehydratedAddPointsCoordinate(a.paths,b,d)};c._addCoordinatePolygon=function(a,b,d){this._dehydratedAddPointsCoordinate(a.rings,b,d)};c._addCoordinateMultipoint=function(a,b,d){0===d&&a.points.push([]);b=this._transformPathLikeValue(b,d);a.points[a.points.length-1].push(b)};
c._createPolygonGeometry=function(a){return{rings:[[]],spatialReference:a.spatialReference,hasZ:!!a.hasZ,hasM:!!a.hasM}};c._createPolylineGeometry=function(a){return{paths:[[]],spatialReference:a.spatialReference,hasZ:!!a.hasZ,hasM:!!a.hasM}};c._createMultipointGeometry=function(a){return{points:[],spatialReference:a.spatialReference,hasZ:!!a.hasZ,hasM:!!a.hasM}};c._dehydratedAddPointsCoordinate=function(a,b,d){0===d&&0===this._toAddInCurrentPath--&&(a.push([]),this._toAddInCurrentPath=this._lengths[++this._currentLengthIndex]-
1,this._previousCoordinate[0]=0,this._previousCoordinate[1]=0);b=this._transformPathLikeValue(b,d);a=a[a.length-1];0===d&&(this._coordinateBufferPtr=0,this._coordinateBuffer=Array(this._vertexDimension),a.push(this._coordinateBuffer));this._coordinateBuffer[this._coordinateBufferPtr++]=b};c._deriveApplyTransform=function(a){const {hasZ:b,hasM:d}=a;return b&&d?u:b?n:d?t:k};return e}();l.JSONFeatureSetParserContext=v;Object.defineProperties(l,{__esModule:{value:!0},[Symbol.toStringTag]:{value:"Module"}})});