// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.25/esri/copyright.txt for details.
//>>built
define("exports ../../chunks/_rollupPluginBabelHelpers ../../Color ../../core/Error ../../core/fontUtils ../../core/screenUtils ./gfxUtils ./previewUtils ./renderUtils ../../views/support/colorUtils".split(" "),function(u,y,E,O,P,n,t,p,Q,F){function G(a,b){const c=R.getContext("2d"),d=[];b&&(b.weight&&d.push(b.weight),b.size&&d.push(b.size+"px"),b.family&&d.push(b.family));c.font=d.join(" ");return c.measureText(a).width}function S(a){if(0===a.length)return 0;if(2<a.length){const b=n.px2pt(1),c=parseFloat(a);
switch(a.slice(-2)){case "px":return c;case "pt":return c*b;case "in":return 72*c*b;case "pc":return 12*c*b;case "mm":return c*T*b;case "cm":return c*U*b}}return parseFloat(a)}function q(a){var b=a?.size;a=null!=b&&"object"===typeof b&&"width"in b?n.pt2px(b.width):null;b=null!=b&&"object"===typeof b&&"height"in b?n.pt2px(b.height):null;return{width:a,height:b}}function V(a,b){return z.apply(this,arguments)}function z(){z=y._asyncToGenerator(function*(a,b){const c=b.fill,d=a.color;"pattern"===c?.type&&
d&&"picture-fill"!==a.type&&(a=yield t.getPatternUrlWithColor(c.src,d.toCss(!0)),c.src=a,b.fill=c)});return z.apply(this,arguments)}function W(a,b,c,d){return A.apply(this,arguments)}function A(){A=y._asyncToGenerator(function*(a,b,c,d){if("font"in a&&a.font&&"text"===b.shape.type){try{yield P.loadFont(a.font)}catch{}({width:a}=q(d));d=/[\uE600-\uE6FF]/.test(b.shape.text);null!=a||d||(c[0]=G(b.shape.text,{weight:b.font.weight,size:b.font.size,family:b.font.family}))}});return A.apply(this,arguments)}
function H(a,b){return a>b?"dark":"light"}function I(a,b){var c="number"===typeof b?.size?b?.size:null,d=null!=c?n.pt2px(c):null,k=null!=b?.maxSize?n.pt2px(b.maxSize):null;c=null!=b?.rotation?b.rotation:"angle"in a?a.angle:null;var h=t.getFill(a),l=t.getStroke(a);"dark"!==J(a,245)||b?.ignoreWhiteSymbols||(l={width:.75,...l,color:"#bdc3c7"});h={shape:null,fill:h,stroke:l,offset:[0,0]};l?.width&&(l.width=Math.min(l.width,X));var g=l?.width||0,m=null==b?.size?!1:null!=b?.scale?b?.scale:!0,e=0,f=0;let r=
!1;switch(a.type){case "simple-marker":l=a.style;const {width:B,height:Y}=q(b);f=e=d=B===Y&&null!=B?B:null!=d?d:Math.min(n.pt2px(a.size),k||v);switch(l){case "circle":h.shape={type:"circle",cx:0,cy:0,r:.5*d};m||(e+=g,f+=g);break;case "cross":h.shape={type:"path",path:[{command:"M",values:[0,.5*f]},{command:"L",values:[e,.5*f]},{command:"M",values:[.5*e,0]},{command:"L",values:[.5*e,f]}]};break;case "diamond":h.shape={type:"path",path:[{command:"M",values:[0,.5*f]},{command:"L",values:[.5*e,0]},{command:"L",
values:[e,.5*f]},{command:"L",values:[.5*e,f]},{command:"Z",values:[]}]};m||(e+=g,f+=g);break;case "square":h.shape={type:"path",path:[{command:"M",values:[0,0]},{command:"L",values:[e,0]},{command:"L",values:[e,f]},{command:"L",values:[0,f]},{command:"Z",values:[]}]};m||(e+=g,f+=g);c&&(r=!0);break;case "triangle":h.shape={type:"path",path:[{command:"M",values:[.5*e,0]},{command:"L",values:[e,f]},{command:"L",values:[0,f]},{command:"Z",values:[]}]};m||(e+=g,f+=g);c&&(r=!0);break;case "x":h.shape=
{type:"path",path:[{command:"M",values:[0,0]},{command:"L",values:[e,f]},{command:"M",values:[e,0]},{command:"L",values:[0,f]}]};c&&(r=!0);break;case "path":h.shape={type:"path",path:a.path||""},m||(e+=g,f+=g),c&&(r=!0),m=!0}break;case "simple-line":const {width:K,height:L}=q(b);a=null!=L?L:null!=d?d:g;m=null!=K?K:Z;l&&(l.width=a);e=m;f=a;d=h?.stroke?.cap||"butt";k="round"===d;m=!0;h.stroke&&(h.stroke.cap="butt"===d?"square":d);h.shape={type:"path",path:[{command:"M",values:[k?a/2:0,f/2]},{command:"L",
values:[k?e-a/2:e,f/2]}]};break;case "picture-fill":case "simple-fill":a="object"===typeof b?.symbolConfig&&b?.symbolConfig.isSquareFill;const {width:w,height:x}=q(b);e=!a&&w!==x||null==w?null!=d?d:aa:w;f=!a&&w!==x||null==x?e:x;m||(e+=g,f+=g);m=!0;h.shape=a?{type:"path",path:[{command:"M",values:[0,0]},{command:"L",values:[e,0]},{command:"L",values:[e,f]},{command:"L",values:[0,f]},{command:"L",values:[0,0]},{command:"Z",values:[]}]}:p.shapes.fill[0];break;case "picture-marker":e=Math.min(n.pt2px(a.width),
k||v);k=Math.min(n.pt2px(a.height),k||v);const {width:C,height:ba}=q(b);f=C===ba&&null!=C?C:null!=d?d:Math.max(e,k);d=e/k;e=1>=d?Math.ceil(f*d):f;f=1>=d?f:Math.ceil(f/d);h.shape={type:"image",x:-Math.round(e/2),y:-Math.round(f/2),width:e,height:f,src:a.url||""};c&&(r=!0);break;case "text":l=b?.overrideText||a.text||"Aa";g=a.font;const {width:ca,height:M}=q(b);d=null!=M?M:null!=d?d:Math.min(n.pt2px(g.size),k||v);e=G(l,{weight:g.weight,size:d,family:g.family});k=/[\uE600-\uE6FF]/.test(l);e=ca??(k?d:
e);f=d;let N=.25*S((g?d:0).toString());k&&(N+=5);h.shape={type:"text",text:l,x:a.xoffset||0,y:a.yoffset||N,align:"middle",alignBaseline:a.verticalAlignment,decoration:g&&g.decoration,rotated:a.rotated,kerning:a.kerning};h.font=g&&{size:d,style:g.style,decoration:g.decoration,weight:g.weight,family:g.family}}return{shapeDescriptor:h,size:[e,f],renderOptions:{node:b?.node,scale:m,opacity:b?.opacity,rotation:c,useRotationSize:r,effectView:b?.effectView}}}function D(){D=y._asyncToGenerator(function*(a,
b){const {shapeDescriptor:c,size:d,renderOptions:k}=I(a,b);if(!c.shape)throw new O("symbolPreview: renderPreviewHTML2D","symbol not supported.");yield V(a,c);yield W(a,c,d,b);a=[[c]];"object"===typeof b?.symbolConfig&&b?.symbolConfig.applyColorModulation&&(b=.6*d[0],a.unshift([{...c,offset:[-b,0],fill:p.adjustColorBrightness(c.fill,-.3)}]),a.push([{...c,offset:[b,0],fill:p.adjustColorBrightness(c.fill,.3)}]),d[0]+=2*b,k.scale=!1);return Q.renderSymbol(a,d,k)});return D.apply(this,arguments)}function J(a,
b=225){var c=t.getFill(a);a=t.getStroke(a);c=!c||"type"in c?null:new E(c);a=a?.color?new E(a?.color):null;c=c?H(F.getColorLuminance(c),b):null;return(a=a?H(F.getColorLuminance(a),b):null)?c?c===a?c:225<=b?"light":"dark":a:c}const aa=p.SymbolSizeDefaults.size,v=p.SymbolSizeDefaults.maxSize,X=p.SymbolSizeDefaults.maxOutlineSize,Z=p.SymbolSizeDefaults.lineWidth,R=document.createElement("canvas"),T=7.2/2.54,U=72/2.54;u.getContrastingBackgroundTheme=J;u.getRenderSymbolParameters=I;u.previewSymbol2D=function(a,
b){return D.apply(this,arguments)};Object.defineProperties(u,{__esModule:{value:!0},[Symbol.toStringTag]:{value:"Module"}})});