// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.25/esri/copyright.txt for details.
//>>built
define("exports ../../chunks/_rollupPluginBabelHelpers ../../assets ../../core/colorUtils ../../core/has ../../core/Error ../../core/Logger ../../core/maybe ../../core/promiseUtils ../../core/screenUtils ./gfxUtils ./IconSymbol3DLayerResource ./ObjectSymbol3DLayerResource ./previewUtils ./renderUtils ./utils ./webStyleSymbolUtils".split(" "),function(A,P,Q,R,ka,S,Y,v,Z,x,B,aa,ba,n,C,T,ca){function z(a){const b=a.outline;var c=v.isSome(a.material)?a.material.color:null;c=v.isSome(c)?c.toHex():null;
if(v.isNone(b)||"pattern"in b&&v.isSome(b.pattern)&&"style"===b.pattern.type&&"none"===b.pattern.style)return"fill"===a.type&&"#ffffff"===c?{color:"#bdc3c7",width:.75}:null;a=x.pt2px(b.size)||0;return{color:"rgba("+(v.isSome(b.color)?b.color.toRgba():"255,255,255,1")+")",width:Math.min(a,J),style:"pattern"in b&&v.isSome(b.pattern)&&"style"===b.pattern.type?B.dekebabifyLineStyle(b.pattern.style):null,join:"butt",cap:"patternCap"in b?b.patternCap:"butt"}}function da(a,b){var c=b&&b.resource;c=c&&c.href;
if(a.thumbnail&&a.thumbnail.url)return Promise.resolve(a.thumbnail.url);if(c&&"object"!==b.type)return Promise.resolve(T.getIconHref(a,b));const e=Q.getAssetUrl("esri/images/Legend/legend3dsymboldefault.png");return a.styleOrigin&&(a.styleOrigin.styleName||a.styleOrigin.styleUrl)?ca.resolveWebStyleSymbol(a.styleOrigin,{portal:a.styleOrigin.portal},"webRef").catch(p=>p).then(p=>p?.thumbnail?.url||e):Promise.resolve(e)}function K(a,b=1){const c=a.a;a=R.toHSV(a);const {r:e,g:p,b:w}=R.toRGB({h:a.h,s:a.s/
b,v:100-(100-a.v)/b});return[e,p,w,c]}function D(a){return"water"===a.type?v.isNone(a.color)?null:a.color:v.isNone(a.material)||v.isNone(a.material.color)?null:a.material.color}function g(a,b=0){var c=D(a);if(!c){if("fill"===a.type)return null;b=n.adjustColorComponentBrightness(B.defaultThematicColor.r,b);return[b,b,b,100]}a=c.toRgba();for(c=0;3>c;c++)a[c]=n.adjustColorComponentBrightness(a[c],b);return a}function U(a,b){return L.apply(this,arguments)}function L(){L=P._asyncToGenerator(function*(a,
b){a=a.style;return"none"===a?null:{type:"pattern",x:0,y:0,src:yield B.getPatternUrlWithColor(Q.getAssetUrl(`esri/symbols/patterns/${a}.png`),b.toCss(!0)),width:5,height:5}});return L.apply(this,arguments)}function V(a){return a.outline?z(a):{color:"rgba(0, 0, 0, 1)",width:1.5}}function W(a,b){a=D(a);if(!a)return null;let c;c="rgba("+(n.adjustColorComponentBrightness(a.r,b)+",");c+=n.adjustColorComponentBrightness(a.g,b)+",";c+=n.adjustColorComponentBrightness(a.b,b)+",";return c+a.a+");"}function M(a,
b){b=W(a,b);if(!b)return{};if("pattern"in a&&v.isSome(a.pattern)&&"style"===a.pattern.type&&"none"===a.pattern.style)return null;const c=Math.min(a.size?x.pt2px(a.size):.75,J);return{color:b,width:c,style:"pattern"in a&&v.isSome(a.pattern)&&"style"===a.pattern.type?B.dekebabifyLineStyle(a.pattern.style):null,cap:"cap"in a?a.cap:null,join:"join"in a?"miter"===a.join?x.pt2px(2):a.join:null}}function E(a,b,c){c=null!=c?.75*c:0;return{type:"linear",x1:c?.25*c:0,y1:c?.5*c:0,x2:c||4,y2:c?.5*c:4,colors:[{color:a,
offset:0},{color:b,offset:1}]}}function ea(a){const b=a.depth,c=a.height;a=a.width;return 0!==a&&0!==b&&0!==c&&a===b&&null!=a&&null!=c&&a<c}function fa(a,b,c){const e=[];if(!a)return e;switch(a.type){case "icon":switch(a.resource&&a.resource.primitive||aa.defaultPrimitive){case "circle":e.push({shape:{type:"circle",cx:0,cy:0,r:.5*b},fill:g(a,0),stroke:z(a)});break;case "square":e.push({shape:{type:"path",path:[{command:"M",values:[0,b]},{command:"L",values:[0,0]},{command:"L",values:[b,0]},{command:"L",
values:[b,b]},{command:"Z",values:[]}]},fill:g(a,0),stroke:z(a)});break;case "triangle":e.push({shape:{type:"path",path:[{command:"M",values:[0,b]},{command:"L",values:[.5*b,0]},{command:"L",values:[b,b]},{command:"Z",values:[]}]},fill:g(a,0),stroke:z(a)});break;case "cross":e.push({shape:{type:"path",path:[{command:"M",values:[.5*b,0]},{command:"L",values:[.5*b,b]},{command:"M",values:[0,.5*b]},{command:"L",values:[b,.5*b]}]},stroke:V(a)});break;case "x":e.push({shape:{type:"path",path:[{command:"M",
values:[0,0]},{command:"L",values:[b,b]},{command:"M",values:[b,0]},{command:"L",values:[0,b]}]},stroke:V(a)});break;case "kite":e.push({shape:{type:"path",path:[{command:"M",values:[0,.5*b]},{command:"L",values:[.5*b,0]},{command:"L",values:[b,.5*b]},{command:"L",values:[.5*b,b]},{command:"Z",values:[]}]},fill:g(a,0),stroke:z(a)})}break;case "object":switch(a.resource&&a.resource.primitive||ba.defaultPrimitive){case "cone":var p=g(a,0);a=g(a,-.6);a=E(p,a,c?N:b);b=n.getConeShapes(b,c);e.push({shape:b[0],
fill:a});e.push({shape:b[1],fill:a});break;case "inverted-cone":c=g(a,0);a=g(a,-.6);a=E(c,a,b);b=n.getInvertedConeShapes(b);e.push({shape:b[0],fill:a});e.push({shape:b[1],fill:c});break;case "cube":b=n.getCubeShapes(b,c);e.push({shape:b[0],fill:g(a,0)});e.push({shape:b[1],fill:g(a,-.3)});e.push({shape:b[2],fill:g(a,-.5)});break;case "cylinder":p=g(a,0);const w=g(a,-.6);p=E(p,w,c?N:b);b=n.getCylinderShapes(b,c);e.push({shape:b[0],fill:p});e.push({shape:b[1],fill:p});e.push({shape:b[2],fill:g(a,0)});
break;case "diamond":b=n.getDiamondShapes(b);e.push({shape:b[0],fill:g(a,-.3)});e.push({shape:b[1],fill:g(a,0)});e.push({shape:b[2],fill:g(a,-.3)});e.push({shape:b[3],fill:g(a,-.7)});break;case "sphere":c=g(a,0);a=g(a,-.6);a=E(c,a);a.x1=0;a.y1=0;a.x2=.25*b;a.y2=.25*b;e.push({shape:{type:"circle",cx:0,cy:0,r:.5*b},fill:a});break;case "tetrahedron":b=n.getTetrahedronShapes(b),e.push({shape:b[0],fill:g(a,-.3)}),e.push({shape:b[1],fill:g(a,0)}),e.push({shape:b[2],fill:g(a,-.6)})}}return e}function F(a){return(a=
"number"===typeof a?.size?a?.size:null)?x.pt2px(a):null}function ha(a,b){const c=F(b),e=b?.maxSize?x.pt2px(b.maxSize):null,p=b?.disableUpsampling??!1,w=a.symbolLayers,r=[];let m=0,t=0;const d=w.getItemAt(w.length-1);let l;d&&"icon"===d.type&&(l=d.size&&x.pt2px(d.size));w.forEach(f=>{if("icon"===f.type||"object"===f.type){var h="icon"===f.type?f.size&&x.pt2px(f.size):0,k=c||h?Math.ceil(Math.min(c||h,e||G)):y;if(f&&f.resource&&f.resource.href){var q=da(a,f).then(u=>{const H=f.get("material.color");
var I="icon"===f.type?"multiply":"tint";return C.tintImageWithColor(u,k,H,I,p)}).then(u=>{const H=u.width,I=u.height;m=Math.max(m,H);t=Math.max(t,I);return[{shape:{type:"image",x:0,y:0,width:H,height:I,src:u.url},fill:null,stroke:null}]});r.push(q)}else q=k,"icon"===f.type&&l&&c&&(q=h/l*k),h="tall"===b?.symbolConfig||b?.symbolConfig?.isTall||("object"===f.type?ea(f):!1),m=Math.max(m,h?N:q),t=Math.max(t,q),r.push(Promise.resolve(fa(f,q,h)))}});return Z.eachAlways(r).then(f=>{const h=[];f.forEach(k=>
{k.value?h.push(k.value):k.error&&Y.getLogger("esri.symbols.support.previewSymbol3D").warn("error while building swatchInfo!",k.error)});return C.renderSymbol(h,[m,t],{node:b&&b.node,scale:!1,opacity:b&&b.opacity})})}function ia(a,b){const c=a.symbolLayers,e=[];a=T.isVolumetricSymbol(a);const p=F(b),w=(b&&b.maxSize?x.pt2px(b.maxSize):null)||J;let r=0,m=0,t;c.forEach((d,l)=>{if(d&&("line"===d.type||"path"===d.type)){var f=[];switch(d.type){case "line":var h=M(d,0);if(v.isNone(h))break;var k=h&&h.width||
0;0===l&&(t=k);d=Math.min(p||k,w);l=0===l?d:p?k/t*d:d;k=l>X/2?2*l:X;m=Math.max(m,l);r=Math.max(r,k);h.width=l;f.push({shape:{type:"path",path:[{command:"M",values:[0,.5*m]},{command:"L",values:[r,.5*m]}]},stroke:h});break;case "path":h=Math.min(p||y,w);l=g(d,0);k=g(d,-.2);var q=W(d,-.4);q=q?{color:q,width:1}:{};if("quad"===d.profile){const u=d.width;d=d.height;d=n.getPathSymbolShapes(u&&d?u/d:1,0===d,0===u);q={...q,join:"bevel"};f.push({shape:d[0],fill:k,stroke:q});f.push({shape:d[1],fill:k,stroke:q});
f.push({shape:d[2],fill:l,stroke:q})}else f.push({shape:n.shapes.pathSymbol3DLayer[0],fill:k,stroke:q}),f.push({shape:n.shapes.pathSymbol3DLayer[1],fill:l,stroke:q});r=m=Math.max(m,h)}e.push(f)}});return Promise.resolve(C.renderSymbol(e,[r,m],{node:b&&b.node,scale:a,opacity:b&&b.opacity}))}function ja(a,b){return O.apply(this,arguments)}function O(){O=P._asyncToGenerator(function*(a,b){const c="mesh-3d"===a.type;a=a.symbolLayers;var e=F(b);const p=b&&b.maxSize?x.pt2px(b.maxSize):null;e=e||y;const w=
[];let r=0,m=0;var t=!1;for(let q=0;q<a.length;q++){var d=a.getItemAt(q);const u=[];if(!c||"fill"===d.type){var l=n.shapes.fill[0];switch(d.type){case "fill":var f=z(d);t=Math.min(e,p||G);r=Math.max(r,t);m=Math.max(m,t);t=!0;var h=g(d,0),k="pattern"in d?d.pattern:null;d=D(d);!c&&v.isSome(k)&&"style"===k.type&&"solid"!==k.style&&d&&(h=yield U(k,d));u.push({shape:l,fill:h,stroke:f});break;case "line":d=M(d,0);if(v.isNone(d))break;d={stroke:d,shape:l};r=Math.max(r,y);m=Math.max(m,y);u.push(d);break;
case "extrude":l={join:"round",width:1,...M(d,-.4)};f=g(d,0);d=g(d,-.2);h=Math.min(e,p||G);k=n.getExtrudeSymbolShapes(h);l.width=1;u.push({shape:k[0],fill:d,stroke:l});u.push({shape:k[1],fill:d,stroke:l});u.push({shape:k[2],fill:f,stroke:l});d=.7*y+.5*h;r=Math.max(r,y);m=Math.max(m,d);break;case "water":t=v.unwrapOrThrow(D(d)),d=K(t),l=K(t,2),f=K(t,3),h=n.getWaterSymbolShapes(),t=!0,u.push({shape:h[0],fill:d}),u.push({shape:h[1],fill:l}),u.push({shape:h[2],fill:f}),d=Math.min(e,p||G),r=Math.max(r,
d),m=Math.max(m,d)}w.push(u)}}return C.renderSymbol(w,[r,m],{node:b&&b.node,scale:t,opacity:b&&b.opacity})});return O.apply(this,arguments)}const y=n.SymbolSizeDefaults.size,G=n.SymbolSizeDefaults.maxSize,J=n.SymbolSizeDefaults.maxOutlineSize,X=n.SymbolSizeDefaults.lineWidth,N=n.SymbolSizeDefaults.tallSymbolWidth;A.getPatternDescriptor=U;A.getSizeFromOptions=F;A.getSymbolLayerFill=g;A.previewSymbol3D=function(a,b){if(0===a.symbolLayers.length)return Promise.reject(new S("symbolPreview: renderPreviewHTML3D",
"No symbolLayers in the symbol."));switch(a.type){case "point-3d":return ha(a,b);case "line-3d":return ia(a,b);case "polygon-3d":case "mesh-3d":return ja(a,b)}return Promise.reject(new S("symbolPreview: swatchInfo3D","symbol not supported."))};Object.defineProperties(A,{__esModule:{value:!0},[Symbol.toStringTag]:{value:"Module"}})});