// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.25/esri/copyright.txt for details.
//>>built
define("require exports ../../chunks/_rollupPluginBabelHelpers ../../Graphic ../../core/has ../../core/handleUtils ../../core/maybe ../../core/promiseUtils ../../core/reactiveUtils ../../core/screenUtils ../../core/accessorSupport/diffUtils ../../renderers/support/clickToleranceUtils ../../renderers/support/lengthUtils ../../renderers/visualVariables/support/sizeVariableUtils ../../renderers/visualVariables/support/visualVariableUtils ../../symbols/support/symbolConversion ../../symbols/support/symbolUtils ../../views/3d/layers/graphics/GraphicState ../../views/support/drapedUtils ../../views/support/hitTestSelectUtils".split(" "),
function(X,t,p,ha,ya,ia,n,x,B,F,ja,ka,la,Y,Z,ma,G,na,oa,H){function aa(b){const a=b.sourceLayer;var c;if(!(c="feature"!==a.type)){a:switch(a.renderer.type){case "class-breaks":case "simple":case "unique-value":case "dot-density":case "dictionary":case "pie-chart":c=!0;break a;default:c=!1}c=!c}if(c)return{rotation:null,size:null};let d=c=null;var g=a.renderer.getVisualVariablesForType("rotation").filter(f=>(!f.axis||"heading"===f.axis)&&f.field&&!f.valueExpression&&n.isSome(Z.getRotationAngle(f,b)));
1===g.length&&(c=pa(g[0],a));g=a.renderer.getVisualVariablesForType("size").filter(f=>f.field&&!f.useSymbolValue&&!f.valueExpression&&Y.getTransformationType(f)===Y.TransformationType.RealWorldSize&&n.isSome(Z.getSize(f,b)));1===g.length&&(d=qa(g[0],a));return{rotation:c,size:d}}function pa(b,a){const c="heading"===(b.axis||"heading")&&"arithmetic"===b.rotationType?-1:1,d=b.field,g=(a=a.fields&&a.fields.filter(k=>k.name===d))&&1===a.length?a[0].type:"double";var f=0,e=0;return{field:d,fieldType:g,
getDefault:()=>Promise.resolve(0),getValue:k=>{e=f-c*k;return I((e+360)%360,g)},initValue:k=>{f=null!=k?k:e;e=0},isUpdatingInteractively:!1,rotationType:b.rotationType??"geographic"}}function ra(b,a){switch(a){case "width":return b[0];case "depth":return b[1];case "height":return b[2];default:return b[2]||b[1]||b[0]}}function sa(b,a,c){return J.apply(this,arguments)}function J(){J=p._asyncToGenerator(function*(b,a,c){if(n.isNone(a))return 0;({symbol:a}=ma.to3D(a));if(n.isNone(a)||"web-style"===a.type||
"cim"===a.type)return 0;a=a.symbolLayers.getItemAt(0);if(!a)return 0;switch(a.type){case "icon":return{computeIconLayerResourceSize:c}=yield new Promise((g,f)=>X(["../../symbols/support/symbolLayerUtils"],g,f)),a.size||Math.min(v.icon,(yield c(a,v.icon))[0])||v.icon;case "text":return a.size||v.text;case "line":return a.size||v.line;case "object":const {computeObjectLayerResourceSize:d}=yield new Promise((g,f)=>X(["../../symbols/support/symbolLayerUtils"],g,f));b=yield d(a,b.scale/v.viewScaleSizeFactor);
return ra(b,c);case "path":return(null!=a.width?a.width:a.height)||b.scale/v.viewScaleSizeFactor;case "extrude":return a.size||b.scale/v.viewScaleSizeFactor;case "fill":case "water":return 0;default:return 0}});return J.apply(this,arguments)}function qa(b,a){const c=b.field,d=b.axis,g=(a=a.fields&&a.fields.filter(h=>h.name===c))&&1===a.length?a[0].type:"double";var f=0,e=0;const k=la.meterIn[b.valueUnit]??1;let l;l="area"===b.valueRepresentation?h=>(h*k/2)**2*Math.PI:"radius"===b.valueRepresentation||
"distance"===b.valueRepresentation?h=>h*k/2:h=>h*k;return{field:c,fieldType:g,getDefault:function(){var h=p._asyncToGenerator(function*(m,r){return I(l(yield sa(r,m,d)),g)});return function(m,r){return h.apply(this,arguments)}}(),getValue:(h,m)=>{f||(f=m.pixelSizeAt(m.center));e=f*h;return I(e,g)},initValue:h=>{f=null!=h?h:e;e=0},isUpdatingInteractively:!1,displayUnit:ba(b.valueUnit),axis:b.axis}}function I(b,a){switch(a){case "small-integer":case "integer":case "long":return Math.round(b);case "double":case "single":return b;
default:return 0}}function y(b,a){return K.apply(this,arguments)}function K(){K=p._asyncToGenerator(function*(b,a){a=yield G.getDisplayedSymbol(b,{useSourceLayer:!0,ignoreGraphicSymbol:!0,webStyleCache:a});const c=ja.diff(b.symbol,a);n.isSome(c)&&(b.symbol=a)});return K.apply(this,arguments)}function L(){L=p._asyncToGenerator(function*(b,a,c,d){yield M(b,a,d);const g=b.on("create",function(){var f=p._asyncToGenerator(function*(e){if("cancel"===e.state)return M(b,a,d);"complete"===e.state&&(e=e.graphic,
e.sourceLayer||(e.sourceLayer=a.layer),e.attributes||(e.attributes={...a.template.prototype.attributes}),yield y(e,d),c(e))});return function(e){return f.apply(this,arguments)}}());return{remove:()=>{g.remove();b.cancel()}}});return L.apply(this,arguments)}function M(b,a,c){return N.apply(this,arguments)}function N(){N=p._asyncToGenerator(function*(b,a,c){var d=a.layer;a={...a.template.prototype.attributes};yield ta(b,d,a,c);c={graphicProperties:{attributes:a,sourceLayer:d},hasZ:d.capabilities.data.supportsZ};
b.layer.elevationInfo=d.elevationInfo;a=b.create;d=d.geometryType;if("mesh"===d||"multipatch"===d)throw Error("Mesh and Multipatch not supported");return a.call(b,d,c)});return N.apply(this,arguments)}function ta(b,a,c,d){return O.apply(this,arguments)}function O(){O=p._asyncToGenerator(function*(b,a,c,d){a=new ha({sourceLayer:a,attributes:c});const {rotation:g,size:f}=aa(a);let e=yield G.getDisplayedSymbol(a,{useSourceLayer:!0,webStyleCache:d}),k=!1;for(const l of[f,g])n.isNone(l)||null!=c[l.field]||
(c[l.field]=yield l.getDefault(e,b.view),k=!0);k&&(e=yield G.getDisplayedSymbol(a,{useSourceLayer:!0,webStyleCache:d}));switch(e?.type){case "simple-fill":case "polygon-3d":b.polygonSymbol=e;break;case "simple-line":case "line-3d":b.polylineSymbol=e;break;case "simple-marker":case "picture-marker":case "point-3d":case "cim":b.pointSymbol=e}ca(b.tooltipOptions,f,g)});return O.apply(this,arguments)}function ca(b,a,c){n.isSome(a)||n.isSome(c)?b.visualVariables={size:n.isSome(a)?{unit:a.displayUnit,axis:a.axis,
valueType:a.fieldType}:null,rotation:n.isSome(c)?{valueType:c.fieldType,rotationType:c.rotationType??"geographic"}:null}:b.visualVariables=null}function ua(b,a,c,d){return P.apply(this,arguments)}function P(){P=p._asyncToGenerator(function*(b,a,c,d){if(0===b.length)return[];const {updatable:g,graphicsByLayer:f}=yield c.async(p._asyncToGenerator(function*(){var {results:e}=yield x.whenOrAbort(H.hitTestSelectSimilarDistance(a,c),d);const k=new Map,l=({layer:h})=>{var m=k.get(h);return m?m:(m=[],k.set(h,
m),m)};H.filterGraphicHits(e).forEach(({graphic:h})=>l(h).push(h));e=b.filter(({supports:h,layer:m})=>h.includes("update")&&k.has(m));0!==e.length&&c.stopPropagation();return{updatable:e,graphicsByLayer:k}}));return x.whenOrAbort(x.eachAlways(g.map(function(){var e=p._asyncToGenerator(function*({layer:k}){var {objectIdField:l}=k,h="displayField"in k?k.displayField:null;const m=[l];k.fieldsIndex.has(h)&&m.push(h);l=f.get(k);return l.some(r=>m.some(w=>!(w in r.attributes)))?(h=k.createQuery(),h.outFields=
m,h.returnGeometry=!1,h.objectIds=l.map(r=>r.getObjectId()),k.queryFeatures(h,{signal:d}).then(({features:r})=>r)):l});return function(k){return e.apply(this,arguments)}}())),d)});return P.apply(this,arguments)}function va(b,a,c,d){return Q.apply(this,arguments)}function Q(){Q=p._asyncToGenerator(function*(b,a,c,d){if(0===b.length)return[];let g=null;const f=yield c.async(p._asyncToGenerator(function*(){var {results:e}=yield x.whenOrAbort(a.hitTest(c),d);if(0===e.length)return[];const k=new Set;g=
H.filterGraphicHits(e);g.forEach(({graphic:l})=>l&&k.add(l.layer));e=b.items.filter(({layer:l,supports:h})=>h.includes("update")&&k.has(l));0<e.length&&c.stopPropagation();return e}));return x.whenOrAbort(x.eachAlways(f.map(({layer:e})=>{const {objectIdField:k}=e;var l="displayField"in e?e.displayField:null,h=[k];e.fieldsIndex.has(l)&&h.push(l);l=e.createQuery();l.outFields=h;l.returnGeometry=!1;h="renderer"in e?ka.calculateTolerance({renderer:e.renderer,event:c}):0;l.geometry=oa.createQueryGeometry(c.mapPoint,
h,a);l.outSpatialReference=a.spatialReference;return e.queryFeatures(l,{signal:d}).then(({features:m})=>{g.forEach(({graphic:r})=>{r.layer===e&&(m.find(w=>w.attributes[k]===r.attributes[e.objectIdField])||m.push(r))});return m})})),d)});return Q.apply(this,arguments)}function R(){R=p._asyncToGenerator(function*(b,a,c,d){switch(a.type){case "3d":return ua(b,a,c,d);case "2d":return va(b,a,c,d)}});return R.apply(this,arguments)}function S(){S=p._asyncToGenerator(function*(b,a,c){const d=b.layer,g=d.createQuery();
g.objectIds=[b.getAttribute(d.objectIdField)];g.outFields=["*"];g.outSpatialReference=a.spatialReference;g.returnM=d.capabilities.data.supportsM;g.returnZ=d.capabilities.data.supportsZ;return(yield d.queryFeatures(g,{signal:c})).features[0]});return S.apply(this,arguments)}function T(b,a,c,d,g){return U.apply(this,arguments)}function U(){U=p._asyncToGenerator(function*(b,a,c,d,g){let f=!1;const {rotation:e,size:k}=d;[e,k].forEach(function(){var l=p._asyncToGenerator(function*(h){if(!n.isNone(h)){var m=
a.attributes[h.field];n.isSome(m)?h.initValue(m):(m=yield h.getDefault(a.symbol,b.view),h.initValue(m),a.setAttribute(h.field,m),f=!0)}});return function(h){return l.apply(this,arguments)}}());f&&(yield y(a,g));d={multipleSelectionEnabled:!1};"point"===c.geometryType&&(d.enableRotation=n.isSome(e),d.enableScaling=n.isSome(k));ca(b.tooltipOptions,k,e);b.layer.elevationInfo=c.elevationInfo;return b.update(a,d)});return U.apply(this,arguments)}function da(b,a,c,d,g){return V.apply(this,arguments)}function V(){V=
p._asyncToGenerator(function*(b,a,c,d,g){if(n.isSome(a.geometry)&&"point"===a.geometry?.type){var f=d.rotation;var e=c.toolEventInfo;e=!n.isSome(e)||"rotate-start"!==e.type&&"rotate"!==e.type&&"rotate-stop"!==e.type?null:e;if(n.isSome(f)&&n.isSome(e))if("rotate-stop"===e.type)f.isUpdatingInteractively=!1,f.initValue();else{f.isUpdatingInteractively=!0;const {field:k,getValue:l}=f;a.attributes[k]=l(e.angle,b)}d=d.size;c=c.toolEventInfo;c=!n.isSome(c)||"scale-start"!==c.type&&"scale"!==c.type&&"scale-stop"!==
c.type?null:c;if(n.isSome(d)&&n.isSome(c))if("scale-stop"===c.type)d.isUpdatingInteractively=!1,d.initValue();else{d.isUpdatingInteractively=!0;const {field:k,getValue:l}=d;a.attributes[k]=l(c.xScale,b)}yield y(a,g)}});return V.apply(this,arguments)}function W(){W=p._asyncToGenerator(function*(b,a,c,d,g,f){const e=b.clone();yield y(e,f);d.map.add(c.layer);c.layer.add(e);const k=b.sourceLayer,l=d.whenLayerView(k),h=()=>{const u=b.attributes[b.layer.objectIdField];l.then(q=>q.setVisibility(u,!1),()=>
{});return{remove(){l.then(q=>q.setVisibility(u,!0),()=>{})}}};let m=null,r=null;if("3d"===d.type){const u=new na.GraphicState({graphic:e});m=ia.handlesGroup([d.trackGraphicState(u),B.watch(()=>u.displaying,q=>{r=q?h():n.removeMaybe(r)},B.initial)])}else r=h();yield T(c,e,k,a,f);let w=null;l.then(u=>w=u,()=>{});const C=a.size,D=a.rotation,ea=B.watch(()=>b.attributes,function(){var u=p._asyncToGenerator(function*(q){let z=!1;for(const A in q){const E=q[A];E!==e.attributes[A]&&(e.setAttribute(A,E),
n.isSome(C)&&!C.isUpdatingInteractively&&C.field===A&&C.initValue(E),n.isSome(D)&&!D.isUpdatingInteractively&&D.field===A&&D.initValue(E),n.isNone(w)||w.requiredFields.includes(A))&&(z=!0)}z&&(yield y(e,f))});return function(q){return u.apply(this,arguments)}}()),wa=c.on("update",function(){var u=p._asyncToGenerator(function*(q){const z=q.graphics[0];if("complete"===q.state)return T(c,z,k,a,f);yield da(d,z,q,a,f);g(z.clone(),q)});return function(q){return u.apply(this,arguments)}}()),xa=c.on(["undo",
"redo"],function(){var u=p._asyncToGenerator(function*(q){g(q.graphics[0].clone(),q)});return function(q){return u.apply(this,arguments)}}()),fa=()=>{};return{interactive:{remove(){xa.remove();wa.remove();c.cancel();ea&&ea.remove();this.remove=fa}},visual:{remove(){n.removeMaybe(r);d.whenLayerView(k).then(u=>B.whenOnce(()=>!u.updating)).then(()=>{n.removeMaybe(m);c.layer.remove(e);this.remove=fa})}}}});return W.apply(this,arguments)}function ba(b){switch(b){case "unknown":case "decimal-degrees":return null;
default:return b}}const v={icon:F.px2pt(24),text:F.px2pt(12),line:F.px2pt(1),viewScaleSizeFactor:100};t.avoidFeatureTemplateSelectionWithOnlyOneItem=function(b,a){b.viewModel.refreshCreationTemplates();if("awaiting-feature-creation-info"===a[0].id){var c=b.viewModel.featureTemplatesViewModel.items;1!==c.length?c=null:(c=c[0],c="items"in c?1===c.items.length?c.items[0]:null:c);n.isSome(c)&&(b.creationInfo={layer:c.layer,template:c.template},a.shift())}return a};t.createWorkflowSteps=function(b,a,c){let d=
!1;return b.filter(g=>d?!0:d=g===a).map(g=>c[g]())};t.fetchCandidates=function(b,a,c,d){return R.apply(this,arguments)};t.fetchFullFeature=function(b,a,c){return S.apply(this,arguments)};t.findLayerInfo=function(b,a){return b&&b.find(c=>c.layer===a)};t.getVisualVariableAttributes=aa;t.isTerminalUpdateEventType=b=>/-stop/.test(b)||/vertex-/.test(b);t.setUpFeatureAdd=function(b,a,c,d){return L.apply(this,arguments)};t.setUpGeometryUpdate=function(b,a,c,d,g,f){return W.apply(this,arguments)};t.sizeDefaults=
v;t.sizeVariableUnitToLengthUnit=ba;t.startCreatingNewFeature=M;t.startUpdatingFeature=T;t.updateGraphicSymbolWhenRequired=y;t.visualVariableInteractiveUpdate=da;Object.defineProperties(t,{__esModule:{value:!0},[Symbol.toStringTag]:{value:"Module"}})});