// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.25/esri/copyright.txt for details.
//>>built
define(["exports","../../core/maybe","../support/networkEnums"],function(d,g,h){d.closestFacilityParametersToQueryParameters=function(a){a=a.toJSON();a.accumulateAttributeNames&&(a.accumulateAttributeNames=a.accumulateAttributeNames.join());a.attributeParameterValues&&(a.attributeParameterValues=JSON.stringify(a.attributeParameterValues));a.barriers&&(a.barriers=JSON.stringify(a.barriers));a.facilities&&(a.facilities=JSON.stringify(a.facilities));a.incidents&&(a.incidents=JSON.stringify(a.incidents));
a.outSR&&(a.outSR=a.outSR.wkid);a.overrides&&(a.overrides=JSON.stringify(a.overrides));a.polygonBarriers&&(a.polygonBarriers=JSON.stringify(a.polygonBarriers));a.polylineBarriers&&(a.polylineBarriers=JSON.stringify(a.polylineBarriers));a.restrictionAttributeNames&&(a.restrictionAttributeNames=a.restrictionAttributeNames.join());a.travelMode&&(a.travelMode=JSON.stringify(a.travelMode));return a};d.fromKebabImpedanceAttributes=function(a){const b={};for(const c of Object.keys(a)){const e=h.impedanceAttributeNameJsonMap.toJSON(c);
b[e]=a[c]}return b};d.getPrefixedProperties=function(a,b){if(g.isNone(a))return null;const c={},e=new RegExp(`^${b}`,"i");for(const k of Object.keys(a))if(e.test(k)){var f=k.substring(b.length);f=h.impedanceAttributeNameJsonMap.fromJSON(f);c[f]=a[k]}return c};d.getTimezoneOffset=function(a,b){return g.isNone(a)||g.isNone(b)?null:Math.round((a-b)/6E4)};d.routeParametersToQueryParameters=function(a){a=a.toJSON();a.accumulateAttributeNames&&(a.accumulateAttributeNames=a.accumulateAttributeNames.join());
a.attributeParameterValues&&(a.attributeParameterValues=JSON.stringify(a.attributeParameterValues));a.barriers&&(a.barriers=JSON.stringify(a.barriers));a.outSR&&(a.outSR=a.outSR.wkid);a.overrides&&(a.overrides=JSON.stringify(a.overrides));a.polygonBarriers&&(a.polygonBarriers=JSON.stringify(a.polygonBarriers));a.polylineBarriers&&(a.polylineBarriers=JSON.stringify(a.polylineBarriers));a.restrictionAttributeNames&&(a.restrictionAttributeNames=a.restrictionAttributeNames.join());a.stops&&(a.stops=JSON.stringify(a.stops));
a.travelMode&&(a.travelMode=JSON.stringify(a.travelMode));return a};d.serviceAreaParametersToQueryParameters=function(a){a=a.toJSON();a.accumulateAttributeNames&&(a.accumulateAttributeNames=a.accumulateAttributeNames.join());a.attributeParameterValues&&(a.attributeParameterValues=JSON.stringify(a.attributeParameterValues));a.barriers&&(a.barriers=JSON.stringify(a.barriers));a.defaultBreaks&&(a.defaultBreaks=a.defaultBreaks.join());a.excludeSourcesFromPolygons&&(a.excludeSourcesFromPolygons=a.excludeSourcesFromPolygons.join());
a.facilities&&(a.facilities=JSON.stringify(a.facilities));a.outSR&&(a.outSR=a.outSR.wkid);a.overrides&&(a.overrides=JSON.stringify(a.overrides));a.polygonBarriers&&(a.polygonBarriers=JSON.stringify(a.polygonBarriers));a.polylineBarriers&&(a.polylineBarriers=JSON.stringify(a.polylineBarriers));a.restrictionAttributeNames&&(a.restrictionAttributeNames=a.restrictionAttributeNames.join());a.travelMode&&(a.travelMode=JSON.stringify(a.travelMode));return a};d.setPrefixedProperties=function(a,b,c){if(!g.isNone(a)){b.attributes||
(b.attributes={});for(const e in a){const f=h.impedanceAttributeNameJsonMap.toJSON(e);b.attributes[`${c}${f}`]=a[e]}}};d.toKebabImpedanceAttributes=function(a){const b={};for(const c of Object.keys(a)){const e=h.impedanceAttributeNameJsonMap.fromJSON(c);b[e]=a[c]}return b};Object.defineProperties(d,{__esModule:{value:!0},[Symbol.toStringTag]:{value:"Module"}})});