// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.25/esri/copyright.txt for details.
//>>built
define("../../../chunks/_rollupPluginBabelHelpers ../../../chunks/tslib.es6 ../../../core/events ../../../core/maybe ../../../core/reactiveUtils ../../../core/accessorSupport/decorators/property ../../../core/arrayUtils ../../../core/accessorSupport/ensureType ../../../core/accessorSupport/decorators/subclass ../../Slider ./SliderWithDropdownViewModel ../../support/Popover ../../support/widgetUtils ../../support/jsxFactory".split(" "),function(m,f,p,k,q,g,e,w,r,t,u,v,x,h){e=function(n){function l(a,
d){var b=n.call(this,a,d)||this;b.viewModel=new u.SliderWithDropdownViewModel;b.buttonTooltip="";b.showDropDown=!0;b._dropdownAnchor=null;b._dropdownElement=null;b._popover=new v({owner:m._assertThisInitialized(b),placement:"bottom-start",anchorElement:()=>k.unwrap(b._dropdownAnchor),renderContentFunction:()=>b._renderPopover()});return b}m._inheritsLoose(l,n);var c=l.prototype;c.initialize=function(){this.addHandles(q.watch(()=>this.viewModel.isDropdownOpen,a=>{this._popover.open=a},q.initial))};
c.destroy=function(){this._popover.destroy()};c.renderThumbLabel=function(a){return h.tsx("div",{class:this.classes("esri-slider-with-dropdown__box","esri-slider__label",{["esri-slider-with-dropdown__box--drop-down-on"]:this.showDropDown,["esri-slider-with-dropdown__box--drop-down-off"]:!this.showDropDown})},n.prototype.renderThumbLabel.call(this,a),this.showDropDown&&h.tsx("div",{bind:this,afterCreate:this._onDropdownAnchorAfterCreate,class:"esri-slider-with-dropdown__dropdown-root"},h.tsx("button",
{class:this.classes("esri-interactive"," esri-widget__anchor esri-slider-with-dropdown__anchor",this.isDropdownOpen?"esri-slider-with-dropdown__anchor--open":"esri-slider-with-dropdown__anchor--closed"),bind:this,disabled:this.disabled,onclick:this._onAnchorClick,onpointerdown:this._killEvent,"aria-label":this.buttonTooltip,title:this.buttonTooltip,"aria-expanded":this.isDropdownOpen.toString(),"aria-haspopup":"listbox",type:"button"},this.currentItem?this.currentItem.name+" ":"")))};c._onDropdownAnchorAfterCreate=
function(a){this._dropdownAnchor=a};c._renderPopover=function(){return h.tsx("ol",{role:"listbox",afterCreate:this._onDropdownAfterCreate,"aria-label":this.buttonTooltip,bind:this,class:this.classes("esri-slider-with-dropdown__list"),tabindex:"-1",onkeydown:this._onDropdownKeyDown,onfocusout:this._onDropdownFocusOut,onpointerdown:this._killEvent},this.items.map((a,d)=>h.tsx("li",{class:d===this.currentIndex?this.classes("esri-interactive","esri-slider-with-dropdown__list-item","esri-slider-with-dropdown__list-item--selected"):
this.classes("esri-interactive","esri-slider-with-dropdown__list-item"),bind:this,onclick:this._onDropdownItemClick,"data-result":d,"aria-label":a.label.join(" "),role:"option","aria-selected":(d===this.currentIndex).toString(),onkeydown:this._onLiKeyDown,tabindex:"0"},a.label.map(b=>h.tsx("span",{bind:this},b)))))};c._onDropdownAfterCreate=function(a){this._dropdownElement=a;a=a.querySelector(".esri-slider-with-dropdown__list-item--selected")??a.firstChild;k.isSome(a)&&a instanceof HTMLElement&&
(a.scrollIntoView(),a.focus())};c._onAnchorClick=function(){if(this.disabled)return!1;this.viewModel.toggle();return!0};c._onDropdownItemClick=function(a){this.viewModel.selectItem(a.currentTarget["data-result"])};c._onDropdownFocusOut=function(a){a=a.relatedTarget;null===a&&(a=document.activeElement);k.isSome(this._dropdownElement)&&!this._dropdownElement.contains(a)&&k.isSome(this._dropdownAnchor)&&!this._dropdownAnchor.contains(a)&&(this.viewModel.isDropdownOpen=!1)};c._killEvent=function(a){a.stopPropagation();
return!0};c._onDropdownKeyDown=function(a){a.stopPropagation();"Escape"===p.eventKey(a)&&(this.viewModel.isDropdownOpen=!1)};c._onLiKeyDown=function(a){const d=a.target;switch(p.eventKey(a)){case "ArrowUp":d.previousElementSibling&&d.previousElementSibling.focus();break;case "ArrowDown":d.nextElementSibling&&d.nextElementSibling.focus();break;case "Enter":d.click()}};m._createClass(l,[{key:"items",get:function(){return this.viewModel.items},set:function(a){this.viewModel.items=a}},{key:"currentIndex",
get:function(){return this.viewModel.currentIndex},set:function(a){this.viewModel.currentIndex=a}},{key:"currentItem",get:function(){return this.viewModel.currentItem}},{key:"isDropdownOpen",get:function(){return this.viewModel.isDropdownOpen}}]);return l}(t);f.__decorate([g.property()],e.prototype,"viewModel",void 0);f.__decorate([g.property()],e.prototype,"buttonTooltip",void 0);f.__decorate([g.property()],e.prototype,"showDropDown",void 0);f.__decorate([g.property()],e.prototype,"items",null);
f.__decorate([g.property()],e.prototype,"currentIndex",null);f.__decorate([g.property()],e.prototype,"currentItem",null);f.__decorate([g.property()],e.prototype,"isDropdownOpen",null);return e=f.__decorate([r.subclass("esri.widgets.Daylight.SliderWithDropdown")],e)});