// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.25/esri/copyright.txt for details.
//>>built
define("../../chunks/_rollupPluginBabelHelpers ../../chunks/tslib.es6 ../../core/Error ../../core/maybe ../../core/accessorSupport/decorators/property ../../core/arrayUtils ../../core/accessorSupport/ensureType ../../core/accessorSupport/decorators/subclass ../../renderers/visualVariables/support/ColorSizeStop ../../renderers/visualVariables/support/ColorStop ../../renderers/visualVariables/support/SizeStop ./SmartMappingSliderBase ./ColorSizeSlider/ColorSizeSliderViewModel ./support/utils ../support/widgetUtils ../support/decorators/messageBundle ../support/jsxFactory".split(" "),
function(E,t,F,v,w,q,R,L,G,H,I,M,N,J,O,P,u){var D;q=D=function(K){function y(a,b){a=K.call(this,a,b)||this;a._bgFillId=null;a._backgroundFillColor="#e0e0e0";a._minRampFillWidth=.2;a._rampFillId=null;a._rampNode=null;a._maxRampFillWidth=1;a.messages=null;a.viewModel=new N;a._bgFillId=`${a.id}-bg-fill`;a._rampFillId=`${a.id}-linear-gradient`;return a}E._inheritsLoose(y,K);y.fromRendererResult=function(a,b){const {renderer:{authoringInfo:{univariateTheme:g}},color:{visualVariable:{stops:c}},size:{visualVariables:e},
statistics:k}=a,{avg:d,stddev:l}=k;if(!c)throw new F("ColorSizeSlider-fromRendererResult:invalid-renderer-result","'result' must include 'color' variable.");const m="above-and-below"===g;var h=a.renderer.authoringInfo.visualVariables[0];a=h.minSliderValue;h=h.maxSliderValue;const n=e.find(f=>"outline"!==f?.target&&!(f?.axis&&!f?.field&&!f?.valueExpression)&&(f?.field||f?.valueExpression)),p=n.stops,C=c.map((f,r)=>{const {color:z,label:A,value:B}=f;return new G({color:z,label:A,value:B,size:p&&0<p.length?
p[r].size:0===r?n.minSize:r===c.length-1?n.maxSize:null})});return new D({max:h,min:a,stops:C,primaryHandleEnabled:m,handlesSyncedToPrimary:m,persistSizeRangeEnabled:m,histogramConfig:{average:d,standardDeviation:l,bins:b?b.bins:[]}})};var x=y.prototype;x.updateFromRendererResult=function(a,b){const {renderer:{authoringInfo:{univariateTheme:g}},color:{visualVariable:{stops:c}},size:{visualVariables:e},statistics:k}=a,{avg:d,stddev:l}=k;if(!c)throw new F("ColorSizeSlider-fromRendererResult:invalid-renderer-result",
"'result' must include 'color' variable.");const m="above-and-below"===g;var h=a.renderer.authoringInfo.visualVariables[0];a=h.minSliderValue;h=h.maxSliderValue;const n=e.find(f=>"outline"!==f?.target&&!(f?.axis&&!f?.field&&!f?.valueExpression)&&(f?.field||f?.valueExpression)),p=n.stops,C=c.map((f,r)=>{const {color:z,label:A,value:B}=f;return new G({color:z,label:A,value:B,size:p&&0<p.length?p[r].size:0===r?n.minSize:r===c.length-1?n.maxSize:null})});this.set({max:h,min:a,stops:C,primaryHandleEnabled:m,
handlesSyncedToPrimary:m,persistSizeRangeEnabled:m,histogramConfig:{average:d,standardDeviation:l,bins:b?b.bins:[]}})};x.updateRenderer=function(a){const {stops:b}=this,g=b[0],c=b[b.length-1];var e=b[Math.floor(b.length/2)];a=a.clone();const k=a.visualVariables.map(d=>{if("size"===d.type){if("outline"===d?.target||d?.axis&&!d?.field&&!d?.valueExpression)return d;v.isSome(d.minSize)&&v.isSome(d.maxSize)?d.set({maxDataValue:c.value,minDataValue:g.value,maxSize:c.size,minSize:g.size}):d.stops&&d.set({stops:b.map(l=>
{const {label:m,size:h,value:n}=l;return new I({label:m,size:h,value:n})})})}else"color"===d.type&&d.set({stops:this.stops.map(l=>{const {color:m,label:h,value:n}=l;return new H({color:m,label:h,value:n})})});return d});a.visualVariables=k;1<a.classBreakInfos.length&&(e=e.value,a.classBreakInfos[0].maxValue=e,a.classBreakInfos[1].minValue=e);return a};x.updateVisualVariables=function(a){return a.map(b=>{const g=b.clone();if("size"===b.type){if("outline"===b?.target||b?.axis&&!b?.field&&!b?.valueExpression)return g;
if(v.isSome(b.minSize)&&v.isSome(b.maxSize)){var {stops:c}=this;b=c[0];c=c[c.length-1];g.set({maxDataValue:c.value,minDataValue:b.value,maxSize:c.size,minSize:b.size})}else b.stops&&g.set({stops:this.stops.map(e=>{const {label:k,size:d,value:l}=e;return new I({label:k,size:d,value:l})})})}else"color"===b.type&&g.set({stops:this.stops.map(e=>{const {color:k,label:d,value:l}=e;return new H({color:k,label:d,value:l})})});return g})};x.render=function(){const {label:a,primaryHandleEnabled:b,state:g,visibleElements:c}=
this,e="disabled"===g,k=this.classes("esri-color-size-slider","esri-widget","esri-widget--panel",{["esri-disabled"]:e,["esri-color-size-slider--primary-handle"]:b,["esri-color-size-slider--interactive-track"]:c.interactiveTrack});return u.tsx("div",{"aria-label":a,class:k},e?null:this.renderContent(this.renderRamp(),"esri-color-size-slider__slider-container","esri-color-size-slider__histogram-container"))};x.renderRamp=function(){const {_bgFillId:a,_rampFillId:b,viewModel:g,zoomOptions:c}=this,e=
g.getStopInfo();return u.tsx("div",{afterCreate:O.storeNode,bind:this,class:"esri-color-size-slider__ramp","data-node-ref":"_rampNode"},u.tsx("svg",{xmlns:"http://www.w3.org/2000/svg"},u.tsx("defs",null,this.renderRampFillDefinition(b,e),this.renderBackgroundFillDefinition(a)),u.tsx("rect",{x:"0",y:"0",fill:this._backgroundFillColor,height:"100%",width:"100%"}),this.renderPaths()),c?this.renderZoomCaps():null)};x.renderPaths=function(){if(this._rampNode){var {offsetHeight:a=0,offsetWidth:b=0}=this._rampNode;
if(!v.isNone(a)&&!v.isNone(b)){var {primaryHandleEnabled:g,stops:c,values:e,viewModel:{max:k,min:d},_bgFillId:l,_maxRampFillWidth:m,_minRampFillWidth:h,_rampFillId:n}=this,p=[m,h];c[0].size<c[c.length-1].size&&p.reverse();var C=e.slice().sort((B,Q)=>B>Q?1:-1),[f,r]=p,[z,A]=C;p=g?J.getDynamicPathForSizeStops({max:k,min:d,pathHeight:a,pathWidth:b,stops:c,padding:h}):J.getPathForSizeStops({bottomValue:z,bottomWidth:f,max:k,min:d,pathHeight:a,pathWidth:b,topValue:A,topWidth:r});return[u.tsx("path",{key:"background",
d:p,fill:`url(#${l})`}),u.tsx("path",{key:"fill",d:p,fill:`url(#${n})`})]}}};E._createClass(y,[{key:"handlesSyncedToPrimary",get:function(){return this.viewModel.handlesSyncedToPrimary},set:function(a){this.viewModel.handlesSyncedToPrimary=a}},{key:"label",get:function(){return this.messages?.widgetLabel??""},set:function(a){this._overrideIfSome("label",a)}},{key:"persistSizeRangeEnabled",get:function(){return this.viewModel.persistSizeRangeEnabled},set:function(a){this.viewModel.persistSizeRangeEnabled=
a}},{key:"primaryHandleEnabled",get:function(){return this.viewModel.primaryHandleEnabled},set:function(a){this.viewModel.primaryHandleEnabled=a}},{key:"stops",get:function(){return this.viewModel.stops},set:function(a){this.viewModel.stops=a}}]);return y}(M.SmartMappingSliderBase);t.__decorate([w.property()],q.prototype,"label",null);t.__decorate([w.property(),P.messageBundle("esri/widgets/smartMapping/ColorSizeSlider/t9n/ColorSizeSlider")],q.prototype,"messages",void 0);t.__decorate([w.property()],
q.prototype,"persistSizeRangeEnabled",null);t.__decorate([w.property()],q.prototype,"primaryHandleEnabled",null);t.__decorate([w.property()],q.prototype,"stops",null);t.__decorate([w.property()],q.prototype,"viewModel",void 0);return q=D=t.__decorate([L.subclass("esri.widgets.smartMapping.ColorSizeSlider")],q)});