// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.25/esri/copyright.txt for details.
//>>built
define("../../../../chunks/_rollupPluginBabelHelpers ../../../../chunks/tslib.es6 ../../../../core/Promise ../../../../core/promiseUtils ../../../../core/workers/workers ../../../../core/accessorSupport/decorators/property ../../../../core/arrayUtils ../../../../core/accessorSupport/ensureType ../../../../core/accessorSupport/decorators/subclass".split(" "),function(e,k,h,g,r,m,u,v,t){h=function(p){function l(b){b=p.call(this,b)||this;b._startupResolver=g.createResolver();b.isReady=!1;return b}e._inheritsLoose(l,
p);var d=l.prototype;d.initialize=function(){this._controller=new AbortController;this.addResolvingPromise(this._startWorker(this._controller.signal))};d.destroy=function(){this._controller.abort();this._connection&&this._connection.close()};d.startup=function(){var b=e._asyncToGenerator(function*(a,c,f,q){yield this.when();var n=this._controller.signal;n=Array.isArray(f.source)?{transferList:f.source,signal:n}:void 0;a=a.tileInfo.toJSON();yield this._connection.invoke("startup",{service:f,config:c,
tileInfo:a,tiles:q},n);this._startupResolver.resolve();this._set("isReady",!0)});return function(a,c,f,q){return b.apply(this,arguments)}}();d.updateTiles=function(){var b=e._asyncToGenerator(function*(a){yield this._startupResolver.promise;return g.ignoreAbortErrors(this._connection.invoke("updateTiles",a))});return function(a){return b.apply(this,arguments)}}();d.update=function(){var b=e._asyncToGenerator(function*(a){a={config:a};yield this._startupResolver.promise;return this._connection.invoke("update",
a)});return function(a){return b.apply(this,arguments)}}();d.applyUpdate=function(){var b=e._asyncToGenerator(function*(a){yield this._startupResolver.promise;return this._connection.invoke("applyUpdate",a)});return function(a){return b.apply(this,arguments)}}();d.setHighlight=function(){var b=e._asyncToGenerator(function*(a){yield this._startupResolver.promise;return g.ignoreAbortErrors(this._connection.invoke("controller.setHighlight",a))});return function(a){return b.apply(this,arguments)}}();
d.stop=function(){var b=e._asyncToGenerator(function*(){yield this._startupResolver.promise;if(!this.closed)return g.ignoreAbortErrors(this._connection.invoke("stop"))});return function(){return b.apply(this,arguments)}}();d.refresh=function(){var b=e._asyncToGenerator(function*(a){yield this._startupResolver.promise;return g.ignoreAbortErrors(this._connection.invoke("controller.refresh",a))});return function(a){return b.apply(this,arguments)}}();d.querySummaryStatistics=function(){var b=e._asyncToGenerator(function*(a,
c,f){yield this._startupResolver.promise;return this._connection.invoke("controller.querySummaryStatistics",{query:a.toJSON(),params:c},f)});return function(a,c,f){return b.apply(this,arguments)}}();d.queryAggregateSummaryStatistics=function(){var b=e._asyncToGenerator(function*(a,c,f){yield this._startupResolver.promise;return this._connection.invoke("controller.queryAggregateSummaryStatistics",{query:a.toJSON(),params:c},f)});return function(a,c,f){return b.apply(this,arguments)}}();d.queryUniqueValues=
function(){var b=e._asyncToGenerator(function*(a,c,f){yield this._startupResolver.promise;return this._connection.invoke("controller.queryUniqueValues",{query:a.toJSON(),params:c},f)});return function(a,c,f){return b.apply(this,arguments)}}();d.queryAggregateUniqueValues=function(){var b=e._asyncToGenerator(function*(a,c,f){yield this._startupResolver.promise;return this._connection.invoke("controller.queryAggregateUniqueValues",{query:a.toJSON(),params:c},f)});return function(a,c,f){return b.apply(this,
arguments)}}();d.queryClassBreaks=function(){var b=e._asyncToGenerator(function*(a,c,f){yield this._startupResolver.promise;return this._connection.invoke("controller.queryClassBreaks",{query:a.toJSON(),params:c},f)});return function(a,c,f){return b.apply(this,arguments)}}();d.queryAggregateClassBreaks=function(){var b=e._asyncToGenerator(function*(a,c,f){yield this._startupResolver.promise;return this._connection.invoke("controller.queryAggregateClassBreaks",{query:a.toJSON(),params:c},f)});return function(a,
c,f){return b.apply(this,arguments)}}();d.queryHistogram=function(){var b=e._asyncToGenerator(function*(a,c,f){yield this._startupResolver.promise;return this._connection.invoke("controller.queryHistogram",{query:a.toJSON(),params:c},f)});return function(a,c,f){return b.apply(this,arguments)}}();d.queryAggregateHistogram=function(){var b=e._asyncToGenerator(function*(a,c,f){yield this._startupResolver.promise;return this._connection.invoke("controller.queryAggregateHistogram",{query:a.toJSON(),params:c},
f)});return function(a,c,f){return b.apply(this,arguments)}}();d.queryFeatures=function(){var b=e._asyncToGenerator(function*(a,c){yield this._startupResolver.promise;return this._connection.invoke("controller.queryFeatures",a.toJSON(),c)});return function(a,c){return b.apply(this,arguments)}}();d.queryVisibleFeatures=function(){var b=e._asyncToGenerator(function*(a,c){yield this._startupResolver.promise;return this._connection.invoke("controller.queryVisibleFeatures",a.toJSON(),c)});return function(a,
c){return b.apply(this,arguments)}}();d.queryObjectIds=function(){var b=e._asyncToGenerator(function*(a,c){yield this._startupResolver.promise;return this._connection.invoke("controller.queryObjectIds",a.toJSON(),c)});return function(a,c){return b.apply(this,arguments)}}();d.queryFeatureCount=function(){var b=e._asyncToGenerator(function*(a,c){yield this._startupResolver.promise;return this._connection.invoke("controller.queryFeatureCount",a.toJSON(),c)});return function(a,c){return b.apply(this,
arguments)}}();d.queryExtent=function(){var b=e._asyncToGenerator(function*(a,c){return this._connection.invoke("controller.queryExtent",a.toJSON(),c)});return function(a,c){return b.apply(this,arguments)}}();d.queryLatestObservations=function(){var b=e._asyncToGenerator(function*(a,c){yield this._startupResolver.promise;return this._connection.invoke("controller.queryLatestObservations",a.toJSON(),c)});return function(a,c){return b.apply(this,arguments)}}();d.queryStatistics=function(){var b=e._asyncToGenerator(function*(a){yield this._startupResolver.promise;
return this._connection.invoke("controller.queryStatistics",a)});return function(a){return b.apply(this,arguments)}}();d.queryAggregates=function(){var b=e._asyncToGenerator(function*(a,c){yield this._startupResolver.promise;return this._connection.invoke("controller.queryAggregates",a.toJSON(),c)});return function(a,c){return b.apply(this,arguments)}}();d.queryAggregateCount=function(){var b=e._asyncToGenerator(function*(a,c){yield this._startupResolver.promise;return this._connection.invoke("controller.queryAggregateCount",
a.toJSON(),c)});return function(a,c){return b.apply(this,arguments)}}();d.queryAggregateIds=function(){var b=e._asyncToGenerator(function*(a,c){yield this._startupResolver.promise;return this._connection.invoke("controller.queryAggregateIds",a.toJSON(),c)});return function(a,c){return b.apply(this,arguments)}}();d.getObjectId=function(){var b=e._asyncToGenerator(function*(a){yield this._startupResolver.promise;return this._connection.invoke("controller.getObjectId",a)});return function(a){return b.apply(this,
arguments)}}();d.getDisplayId=function(){var b=e._asyncToGenerator(function*(a){yield this._startupResolver.promise;return this._connection.invoke("controller.getDisplayId",a)});return function(a){return b.apply(this,arguments)}}();d.getFeatures=function(){var b=e._asyncToGenerator(function*(a){yield this._startupResolver.promise;return this._connection.invoke("controller.getFeatures",a)});return function(a){return b.apply(this,arguments)}}();d.getAggregates=function(){var b=e._asyncToGenerator(function*(){yield this._startupResolver.promise;
return this._connection.invoke("controller.getAggregates")});return function(){return b.apply(this,arguments)}}();d.getAggregateValueRanges=function(){var b=e._asyncToGenerator(function*(){yield this._startupResolver.promise;return this._connection.invoke("controller.getAggregateValueRanges")});return function(){return b.apply(this,arguments)}}();d.mapValidDisplayIds=function(){var b=e._asyncToGenerator(function*(a){yield this._startupResolver.promise;return this._connection.invoke("controller.mapValidDisplayIds",
a)});return function(a){return b.apply(this,arguments)}}();d.onEdits=function(){var b=e._asyncToGenerator(function*(a){yield this._startupResolver.promise;return g.ignoreAbortErrors(this._connection.invoke("controller.onEdits",a))});return function(a){return b.apply(this,arguments)}}();d.enableEvent=function(){var b=e._asyncToGenerator(function*(a,c){yield this._startupResolver.promise;return g.ignoreAbortErrors(this._connection.invoke("controller.enableEvent",{name:a,value:c}))});return function(a,
c){return b.apply(this,arguments)}}();d.pauseStream=function(){return g.ignoreAbortErrors(this._connection.invoke("controller.pauseStream"))};d.resumeStream=function(){return g.ignoreAbortErrors(this._connection.invoke("controller.resumeStream"))};d._startWorker=function(){var b=e._asyncToGenerator(function*(a){try{this._connection=yield r.open("Pipeline",{client:this.client,strategy:"dedicated",signal:a})}catch(c){g.throwIfNotAbortError(c)}});return function(a){return b.apply(this,arguments)}}();
e._createClass(l,[{key:"tileRenderer",set:function(b){this.client.tileRenderer=b}},{key:"closed",get:function(){return this._connection.closed}}]);return l}(h.EsriPromise);k.__decorate([m.property()],h.prototype,"isReady",void 0);k.__decorate([m.property({constructOnly:!0})],h.prototype,"client",void 0);k.__decorate([m.property()],h.prototype,"tileRenderer",null);return h=k.__decorate([t.subclass("esri.views.2d.layers.support.FeatureLayerProxy")],h)});