// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.25/esri/copyright.txt for details.
//>>built
define("../../../chunks/_rollupPluginBabelHelpers ../../../chunks/tslib.es6 ../../../Graphic ../../../core/Error ../../../core/Logger ../../../core/maybe ../../../core/reactiveUtils ../../../core/accessorSupport/decorators/property ../../../core/arrayUtils ../../../core/accessorSupport/ensureType ../../../core/accessorSupport/decorators/subclass ../../../core/sql/WhereClause ../../../layers/buildingSublayers/BuildingComponentSublayer ../../../layers/support/FeatureFilter ../../../layers/support/fieldUtils ../../../rest/support/Query ./BuildingSublayerView3D ./I3SMeshView3D ./II3SMeshView3D ./i3s/BuildingFilterUtil ./i3s/I3SGeometryUtil ./i3s/I3SMeshViewFilter ./i3s/I3SQueryEngine ./i3s/I3SQueryFeatureAdapter ./i3s/I3SQueryFeatureStore ./i3s/I3SUtil ./support/DefinitionExpressionSceneLayerView ../../layers/BuildingComponentSublayerView ../../layers/support/popupUtils ../../support/Scheduler".split(" "),
function(r,k,D,x,t,e,y,l,g,Q,E,F,R,G,n,z,H,I,v,A,J,B,K,L,M,C,N,O,w,P){g=function(p){function u(){var a=p.apply(this,arguments)||this;a.type="building-component-sublayer-3d";a.layerView=null;a._elevationContext="scene";a._isIntegratedMesh=!1;a._supportsLabeling=!1;a.requiredFields=[];a.progressiveLoadFactor=1;a._queryEngine=null;return a}r._inheritsLoose(u,p);var d=u.prototype;d.initialize=function(){this.updatingHandles.add(()=>[this.sublayer.renderer,this.definitionExpressionFields,this.filterExpressionFields],
()=>this._updateRequiredFields());this.updatingHandles.add(()=>this.sublayer.renderer,b=>this._rendererChange(b),y.initial);const a=()=>this._filterChange();this.updatingHandles.add(()=>this.parsedDefinitionExpression,a);this.updatingHandles.add(()=>e.isSome(this._filter)?this._filter.sortedObjectIds:null,a);this.updatingHandles.add(()=>e.isSome(this._filter)?this._filter.parsedWhereClause:null,a);this.updatingHandles.add(()=>[e.isSome(this._filter)?this._filter.parsedGeometry:null,e.isSome(this.filter)?
this.filter.spatialRelationship:null],()=>this._geometryFilterChange());this.updatingHandles.add(()=>this.parsedFilterExpressions,()=>this._updateSymbologyOverride(),y.initial);this.addResolvingPromise(this._updateRequiredFields())};d.isUpdating=function(){return p.prototype.isUpdating.call(this)||e.isSome(this._filter)&&this._filter.updating};d._updateSymbologyOverride=function(){const a=this.parsedFilterExpressions;0<a.length?this._setSymbologyOverride((b,c)=>{for(const [f,h]of a)try{if(f.testFeature(b))return A.applyFilterMode(c,
h)}catch(m){this.logError(m)}return A.applyFilterMode(c,null)},this.filterExpressionFields):this._setSymbologyOverride(null,null)};d._createLayerGraphic=function(a){a=new D(null,null,a);a.layer=this.sublayer.layer;a.sourceLayer=this.sublayer;return a};d.canResume=function(){return p.prototype.canResume.call(this)&&(!this._controller||this._controller.rootNodeVisible)};d.fetchPopupFeatures=function(){var a=r._asyncToGenerator(function*(b,c){if(b=this._validateFetchPopupFeatures(c))throw b;if(e.isNone(c)||
!c.clientGraphics||0===c.clientGraphics.length)return[];const f=[],h=[];b=e.isSome(this.sublayer.associatedLayer)?yield this.sublayer.associatedLayer.load():this.sublayer;b=n.unpackFieldNames(this.sublayer.fieldsIndex,yield w.getRequiredFields(b,w.getFetchPopupTemplate(this.sublayer,c)));const m=new Set;for(const q of c.clientGraphics)n.populateMissingFields(b,q,m)?h.push(q):f.push(q);if(0===h.length)return f;e.isSome(this.sublayer.associatedLayer)&&(yield this.sublayer.associatedLayer.load().catch(()=>
t.getLogger(this.declaredClass).warn("Failed to load associated feature layer. Displaying popup attributes from cached attributes.")));return this.whenGraphicAttributes(h,Array.from(m)).catch(()=>h).then(q=>f.concat(q))});return function(b,c){return a.apply(this,arguments)}}();d._updateRequiredFields=function(){var a=r._asyncToGenerator(function*(){const b=n.fixFields(this.sublayer.fieldsIndex,[...(this.sublayer.renderer?yield this.sublayer.renderer.getRequiredFields(this.sublayer.fieldsIndex):[]),
...(this.definitionExpressionFields||[]),...(this.filterExpressionFields||[])]);this._set("requiredFields",b)});return function(){return a.apply(this,arguments)}}();d._validateFetchPopupFeatures=function(a){const {sublayer:b}=this,{popupEnabled:c}=b;if(!c)return new x("buildingscenelayerview3d:fetchPopupFeatures","Popups are disabled",{sublayer:b});if(!w.getFetchPopupTemplate(b,a))return new x("buildingscenelayerview3d:fetchPopupFeatures","Layer does not define a popup template",{sublayer:b})};d.getFilters=
function(){const a=p.prototype.getFilters.call(this);this.addSqlFilter(a,this.parsedDefinitionExpression,this.logError);e.isSome(this._filter)&&this._filter.addFilters(a,this.view,this._controller.crsIndex,this._collection);return a};d.createQuery=function(){const a={outFields:["*"],returnGeometry:!1,outSpatialReference:this.view.spatialReference};return e.isSome(this.filter)?this.filter.createQuery(a):new z(a)};d.queryExtent=function(a,b){return this._ensureQueryEngine().executeQueryForExtent(this._ensureQuery(a),
b?.signal)};d.queryFeatureCount=function(a,b){return this._ensureQueryEngine().executeQueryForCount(this._ensureQuery(a),b?.signal)};d.queryFeatures=function(a,b){return this._ensureQueryEngine().executeQuery(this._ensureQuery(a),b?.signal).then(c=>{if(!c?.features)return c;const f=this.sublayer,h=f.layer;for(const m of c.features)m.layer=h,m.sourceLayer=f;return c})};d.queryObjectIds=function(a,b){return this._ensureQueryEngine().executeQueryForIds(this._ensureQuery(a),b?.signal)};d._ensureQueryEngine=
function(){e.isNone(this._queryEngine)&&(this._queryEngine=this._createQueryEngine());return this._queryEngine};d._createQueryEngine=function(){const a=J.createGetFeatureExtent(this.view.spatialReference,this.view.renderSpatialReference,this._collection);return new K.I3SQueryEngine({layerView:this,priority:P.TaskPriority.FEATURE_QUERY_ENGINE,spatialIndex:new M.I3SQueryFeatureStore({featureAdapter:new L.I3SQueryFeatureAdapter({objectIdField:this.sublayer.objectIdField,attributeStorageInfo:this.sublayer.attributeStorageInfo,
getFeatureExtent:a}),toArray:()=>{const b=[];this._forAllFeatures((c,f,h)=>{b.push({id:c,index:f,meta:h});return v.ForAllFeaturesReturnType.CONTINUE},null,v.ForAllFeaturesVisibilityMode.ALL_IN_CLIPPING_AREA);return b},forAllFeatures:(b,c)=>this._forAllFeatures((f,h,m)=>b({id:f,index:h,meta:m}),c,v.ForAllFeaturesVisibilityMode.ALL_IN_CLIPPING_AREA),getFeatureExtent:a,sourceSpatialReference:C.getIndexCrs(this.sublayer),viewSpatialReference:this.view.spatialReference})})};d._ensureQuery=function(a){return this._addDefinitionExpressionToQuery(e.isNone(a)?
this.createQuery():z.from(a))};r._createClass(u,[{key:"i3slayer",get:function(){return this.sublayer}},{key:"layerUid",get:function(){return this.sublayer.layer.uid}},{key:"sublayerUid",get:function(){return this.sublayer.uid}},{key:"layerId",get:function(){return this.sublayer.layer.id}},{key:"sublayerId",get:function(){return this.sublayer.id}},{key:"layerPopupEnabled",get:function(){return this.sublayer.popupEnabled}},{key:"lodFactor",get:function(){return this.view.qualitySettings.sceneService.object.lodFactor}},
{key:"parsedFilterExpressions",get:function(){return"Overview"!==this.sublayer.modelName&&this.layerView?this.layerView.filterExpressions.map(([a,b])=>{let c;try{c=F.WhereClause.create(a,this.sublayer.fieldsIndex)}catch(f){return t.getLogger(this.declaredClass).error("Failed to parse filterExpression: "+f),null}if(!c.isStandardized)return t.getLogger(this.declaredClass).error("filterExpression is using non standard function"),null;a=[];C.findFieldsCaseInsensitive(c.fieldNames,this.sublayer.fields,
{missingFields:a});return 0<a.length?(t.getLogger(this.declaredClass).error(`filterExpression references unknown fields: ${a.join(", ")}`),null):[c,b]}).filter(a=>null!=a):[]}},{key:"filter",get:function(){return e.isSome(this._filter)?this._filter.viewFilter:null},set:function(a){e.isNone(a)||!B.I3SMeshViewFilter.checkSupport(a)?this._filter=null:e.isSome(this._filter)?this._filter.viewFilter=a:this._filter=new B.I3SMeshViewFilter({viewFilter:a,layerFieldsIndex:this.sublayer.fieldsIndex,loadAsyncModule:b=>
this._loadAsyncModule(b),addSqlFilter:(b,c)=>this.addSqlFilter(b,c,this.logError)})}},{key:"filterExpressionFields",get:function(){return n.fixFields(this.sublayer.fieldsIndex,this.parsedFilterExpressions.reduce((a,[b])=>a.concat(b.fieldNames),[]))}},{key:"availableFields",get:function(){var a=this.sublayer;const b=a.fieldsIndex;let c=this.requiredFields;if(a.outFields||a.layer.outFields)a=[...(a.outFields||[]),...(a.layer.outFields||[])],c=[...n.unpackFieldNames(b,a),...c];return n.fixFields(b,c)}}]);
return u}(N.DefinitionExpressionSceneLayerView(I.I3SMeshView3D(H.BuildingSublayerView3DMixin(O))));k.__decorate([l.property()],g.prototype,"i3slayer",null);k.__decorate([l.property()],g.prototype,"layerView",void 0);k.__decorate([l.property()],g.prototype,"lodFactor",null);k.__decorate([l.property({readOnly:!0})],g.prototype,"parsedFilterExpressions",null);k.__decorate([l.property({type:G})],g.prototype,"filter",null);k.__decorate([l.property()],g.prototype,"_filter",void 0);k.__decorate([l.property({type:[String],
readOnly:!0})],g.prototype,"filterExpressionFields",null);k.__decorate([l.property({type:[String],readOnly:!0})],g.prototype,"requiredFields",void 0);k.__decorate([l.property({type:[String],readOnly:!0})],g.prototype,"availableFields",null);return g=k.__decorate([E.subclass("esri.views.3d.layers.BuildingComponentSublayerView3D")],g)});