// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.25/esri/copyright.txt for details.
//>>built
define("../../../chunks/_rollupPluginBabelHelpers ../../../chunks/tslib.es6 ../../../core/Error ../../../core/maybe ../../../core/reactiveUtils ../../../core/accessorSupport/decorators/property ../../../core/arrayUtils ../../../core/accessorSupport/ensureType ../../../core/accessorSupport/decorators/subclass ../../../layers/graphics/hydratedFeatures ../../../layers/graphics/controllers/FeatureTileController3D ./FeatureLikeLayerView3D ./LayerView3D ./support/FeatureTileFetcher3DLayerViewContext ../support/EventedSet ../support/updatingProperties ../webgl-engine/lib/basicInterfaces ../../layers/FeatureLayerView ../../layers/LayerView ../../layers/RefreshableLayerView".split(" "),
function(m,e,v,n,l,g,d,I,w,x,y,z,A,B,C,D,q,E,F,G){d=function(r){function t(a){a=r.call(this,a)||this;a._controllerTotal=0;a._processorTotal=0;a.suspendResumeExtentMode="data";return a}m._inheritsLoose(t,r);var f=t.prototype;f.initialize=function(){this.handles.add(l.watch(()=>this._updatingRequiredFieldsPromise,a=>this.updatingHandles.addPromise(a),l.syncAndInitial))};f.destroy=function(){this.updatingHandles.removeAll();this.handles.removeAll();this._fetcherContext=n.destroyMaybe(this._fetcherContext)};
f.setVisibility=function(a,b){this.processor?.setObjectIdVisibility(a,b)};f.createQuery=function(){return r.prototype.createQuery.call(this)};f.queryFeatures=function(a,b){const c=()=>r.prototype.queryFeatures.call(this,a,b);return"mesh"===this.layer.geometryType?this._queryFeaturesMesh(this._ensureQuery(a),c):c()};f.beforeSetController=function(a){a.maximumNumberOfFeatures=this.maximumNumberOfFeatures};f.createController=function(){this._fetcherContext=new B.FeatureTileFetcher3DLayerViewContext({layerView:this,
returnZ:this.hasZ,returnM:this.hasM});const a=new y.FeatureTileController3D({layerView:this,context:this._fetcherContext,graphics:new C.EventedSet,extent:this.clippingExtent});this.updatingHandles.add(()=>a.serviceDataExtent,b=>{this.processor&&(this.processor.dataExtent=b)},l.initial);this.handles.add(l.watch(()=>this.suspended,b=>{b?a.suspend():a.resume()},l.syncAndInitial));this.updatingHandles.add(()=>this.processor?.displayFeatureLimit,b=>a.displayFeatureLimit=b,l.initial);this.handles.add(l.when(()=>
!this.updating,()=>{this._processorTotal=this._controllerTotal=0}));return a};f.doRefresh=function(){var a=m._asyncToGenerator(function*(b){b&&!this.suspended&&this.controller&&this.controller.refetch();this.processor.refreshFilter()});return function(b){return a.apply(this,arguments)}}();f.getUsedMemory=function(){return(this.processor?.usedMemory??0)+(this.controller?.memoryForUnusedFeatures??0)};f.getUnloadedMemory=function(){const a=this.controller?.expectedFeatureDiff??0,b=this.processor?.loadedFeatures??
0;return(this.processor?.unprocessedMemoryEstimate??0)+(0===b||20<a/b?0:a*(this.processor?.usedMemoryPerFeature??0))};f.ignoresMemoryFactor=function(){return this.controller?.hasMaximumNumberOfFeaturesOverride};f._queryFeaturesMesh=function(){var a=m._asyncToGenerator(function*(b,c){yield this._validateQueryFeaturesMesh(b);c=yield c();if(b&&b.outStatistics||n.isNone(this.graphics3DProcessor))return c;b=this.layer.objectIdField;const h=this.graphics3DProcessor.graphics3DGraphicsByObjectID,k=[];for(const p of c.features)if(p.geometry){const u=
h.get(p.attributes[b]);u&&(p.geometry=x.hydrateGeometry(u.graphic.geometry),k.push(p))}else k.push(p);c.features=k;return c});return function(b,c){return a.apply(this,arguments)}}();f._validateQueryFeaturesMesh=function(){var a=m._asyncToGenerator(function*(b){if(b){var c=k=>{throw new v("feature-layer-view:unsupported-query",`Queries on Mesh feature collection layers do not support '${k}'`);},h=["quantizationParameters","geometryPrecision","maxAllowableOffset"];for(const k of h)null!=b[k]&&c(k);
"returnM"in b&&b.returnM&&c("returnM");"returnCentroid"in b&&b.returnCentroid&&c("returnCentroid");n.isSome(b.outSpatialReference)&&!b.outSpatialReference.equals(this.view.spatialReference)&&c("outSpatialReference")}});return function(b){return a.apply(this,arguments)}}();m._createClass(t,[{key:"maximumNumberOfFeatures",get:function(){return this.controller?.maximumNumberOfFeatures??this._get("maximumNumberOfFeatures")},set:function(a){this._set("maximumNumberOfFeatures",a);this.controller&&(this.controller.maximumNumberOfFeatures=
a)}},{key:"maximumNumberOfFeaturesExceeded",get:function(){return this.controller?!(this.suspended||!this.controller.maximumNumberOfFeaturesExceeded):!1}},{key:"updatingProgressValue",get:function(){let a=0;if(this.controller?.updating){var b=this.controller.updatingRemaining,c=Math.max(this.controller.updatingTotal,this._controllerTotal);0<c&&(a=(c-b)/c,this._controllerTotal=c)}b=0;if(this.processor?.updating){c=this.processor.updatingRemaining;const h=Math.max(c,this._processorTotal);0<h&&(b=(h-
c)/h,this._processorTotal=h)}return.5*(a+b)}},{key:"updatePolicy",get:function(){if(!this.controller)return q.UpdatePolicy.ASYNC;switch(this.controller.mode){case "snapshot":const a=H[this.layer.geometryType];return null==a||this.controller.serviceDataCount>a?q.UpdatePolicy.ASYNC:q.UpdatePolicy.SYNC;case "tiles":return q.UpdatePolicy.ASYNC}}},{key:"hasZ",get:function(){const a=this.layer,b=a.capabilities&&a.capabilities.data;return b&&b.supportsZ?"returnZ"in a&&null!=a.returnZ?a.returnZ:b.supportsZ:
!1}},{key:"hasM",get:function(){const a=this.layer,b=a.capabilities&&a.capabilities.data;return b&&b.supportsM?"returnM"in a&&null!=a.returnM?a.returnM:!1:!1}},{key:"performanceInfo",get:function(){var a=this.controller?.displayFeatureLimit;a=n.isSome(a)&&a.averageSymbolComplexity;a=n.isSome(a)?`f:${a.primitivesPerFeature},v:${a.primitivesPerCoordinate}`:"n/a";a={...this._getResourceInfo(),storedFeatures:0,totalVertices:0,partial:this.maximumNumberOfFeaturesExceeded,mode:this.controller?.mode??"n/a",
symbolComplexity:a,nodes:this.controller?.tileDescriptors.length??0};if(this.controller&&a.displayedNumberOfFeatures){const b=this.controller.debug;a.storedFeatures=b.storedFeatures;a.totalVertices=b.totalVertices}return a}},{key:"test",get:function(){return{updatePolicy:this.updatePolicy,controller:this.controller,loadedGraphics:this.controller?.graphics}}}]);return t}(G(z.FeatureLikeLayerView3D(E(A.LayerView3D(F)))));e.__decorate([g.property()],d.prototype,"layer",void 0);e.__decorate([g.property()],
d.prototype,"controller",void 0);e.__decorate([g.property()],d.prototype,"_controllerTotal",void 0);e.__decorate([g.property()],d.prototype,"_processorTotal",void 0);e.__decorate([g.property()],d.prototype,"maximumNumberOfFeatures",null);e.__decorate([g.property()],d.prototype,"maximumNumberOfFeaturesExceeded",null);e.__decorate([g.property(D.updatingProgress)],d.prototype,"updatingProgress",void 0);e.__decorate([g.property({readOnly:!0})],d.prototype,"updatingProgressValue",null);e.__decorate([g.property({readOnly:!0})],
d.prototype,"updatePolicy",null);e.__decorate([g.property({readOnly:!0})],d.prototype,"hasZ",null);e.__decorate([g.property({readOnly:!0})],d.prototype,"hasM",null);e.__decorate([g.property()],d.prototype,"suspendResumeExtentMode",void 0);d=e.__decorate([w.subclass("esri.views.3d.layers.FeatureLayerViewBase3D")],d);const H={point:5E3,polygon:500,polyline:1E3};return d});