// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.25/esri/copyright.txt for details.
//>>built
define("../../../../chunks/_rollupPluginBabelHelpers ../../../../chunks/tslib.es6 ../../../../Graphic ../../../../arcade/functions/hash ../../../../core/compilerUtils ../../../../core/HandleOwner ../../../../core/maybe ../../../../core/promiseUtils ../../../../core/reactiveUtils ../../../../core/accessorSupport/decorators/property ../../../../core/arrayUtils ../../../../core/accessorSupport/ensureType ../../../../core/accessorSupport/decorators/subclass ../../../../core/accessorSupport/diffUtils ../../../../geometry/support/webMercatorUtils ../../../../renderers/support/randomRotationExpression ../../../../renderers/support/renderingInfoUtils ../../../../rest/support/Query ../interfaces ./constants ./Graphics3DCore ./Graphics3DElevationAlignment ./Graphics3DFrustumVisibility ./Graphics3DObjectStates ./Graphics3DScaleVisibility ./graphicUtils ../support/attributeUtils ../support/FeatureVisibilityFilter ../../webgl-engine/lib/basicInterfaces".split(" "),
function(q,e,r,z,A,d,k,t,m,f,O,P,B,u,v,C,w,D,E,F,G,H,I,J,K,L,x,M,n){d=function(y){function p(a){a=y.call(this,a)||this;a.type="graphics-3d";a._randomRotationRenderers=null;a.elevationFeatureExpressionEnabled=!1;a.scaleVisibilityEnabled=!1;a.filterVisibilityEnabled=!1;a.frustumVisibilityEnabled=!1;a.elevationAlignmentEnabled=!1;a.timeExtentEnabled=!1;a.setUidToIdOnAdd=!0;a.dataExtent=null;a.drapeSourceType=E.DrapeSourceType.Features;a.preferredUpdatePolicy=n.UpdatePolicy.ASYNC;a._suspendResumeExtent=
null;return a}q._inheritsLoose(p,y);var h=p.prototype;h.initialize=function(){const a=this.owner,c=new G.Graphics3DCore({owner:this,layer:this.layer,preferredUpdatePolicy:this.preferredUpdatePolicy,elevationFeatureExpressionEnabled:this.elevationFeatureExpressionEnabled,graphicSymbolSupported:!1,hasZ:a.hasZ,hasM:a.hasM,setUidToIdOnAdd:this.setUidToIdOnAdd,componentFactories:{deconflictor:b=>a.view.deconflictor.addGraphicsOwner(b),labeler:(b,g)=>a.view.labeler.addGraphicsOwner(b,g),elevationAlignment:this.elevationAlignmentEnabled?
(b,g)=>new H({graphicsCoreOwner:this,graphicsCore:b,queryGraphicUIDsInExtent:g,elevationProvider:a.view.elevationProvider}):null,scaleVisibility:this.scaleVisibilityEnabled?(b,g)=>new K({graphicsCoreOwner:this,layer:this.layer,queryGraphicUIDsInExtent:g,graphicsCore:b,basemapTerrain:a.view.basemapTerrain}):null,filterVisibility:(this.filterVisibilityEnabled||this.timeExtentEnabled)&&"multipatch"!==a.layer.geometryType?b=>new M.FeatureVisibilityFilter({context:{layerView:a,...b}}):null,objectStates:b=>
new J.Graphics3DObjectStates(b)}});this._set("graphicsCore",c);this.frustumVisibilityEnabled&&this._set("frustumVisibility",new I({graphicsCoreOwner:this}));this.elevationAlignment&&this.updatingHandles.add(()=>this.layer.elevationInfo,(b,g)=>{u.diff(b,g)&&this.updatingHandles.addPromise(this.graphicsCore.elevationInfoChange())});this.updatingHandles.add(()=>this.layer.labelsVisible,()=>this.graphicsCore.updateVisibilityInfo());this.updatingHandles.add(()=>this.layer.labelingInfo,(b,g)=>{u.diff(b,
g)&&this.graphicsCore.updateLabelingInfo()});this.updatingHandles.add(()=>this.preferredUpdatePolicy,b=>this.graphicsCore.preferredUpdatePolicy=b);this._set("initializePromise",this._initializeAsync());this.updatingHandles.addPromise(this.initializePromise)};h._initializeAsync=function(){var a=q._asyncToGenerator(function*(){yield t.logOnError(this.graphicsCore.initializePromise);const c=this.owner;this.updatingHandles.add(()=>this.renderer,b=>this.updatingHandles.addPromise(this.graphicsCore.rendererChange(b)));
this.updatingHandles.add(()=>c.fullOpacity,()=>this.graphicsCore.opacityChange());this._setupSuspendResumeExtent();this.updateClippingExtent&&(this.updatingHandles.add(()=>c.view.clippingArea,()=>this._updateClippingExtent()),this._updateClippingExtent());this.graphicsCore.startCreateGraphics();this.graphicsCore.labelsEnabled&&(yield t.logOnError(this.graphicsCore.updateLabelingInfo()))});return function(){return a.apply(this,arguments)}}();h.destroy=function(){this.handles.removeAll();this.updatingHandles.removeAll();
this._set("frustumVisibility",k.destroyMaybe(this.frustumVisibility));this._set("graphicsCore",k.destroyMaybe(this.graphicsCore));this._set("owner",null)};h.maskOccludee=function(a){const {set:c,handle:b}=this.objectStates.acquireSet(n.Object3DState.MaskOccludee,null);this.objectStates.setUid(c,a.uid);return b};h.highlight=function(a,c){if(a instanceof D){const {set:b,handle:g}=this.objectStates.acquireSet(n.Object3DState.Highlight,c);this.owner.queryObjectIds(a).then(l=>this.objectStates.setObjectIds(b,
l));return g}if("number"===typeof a||"string"===typeof a||a instanceof r)return this.highlight([a],c);"toArray"in a&&(a=a.toArray());if(Array.isArray(a)&&0<a.length){if(a[0]instanceof r)if(null!=x.attributeLookup(this.layer.fieldsIndex,a[0].attributes,c))a=a.map(b=>x.attributeLookup(this.layer.fieldsIndex,b.attributes,c));else{a=a.map(l=>l.uid);const {set:b,handle:g}=this.objectStates.acquireSet(n.Object3DState.Highlight,null);this.objectStates.setUids(b,a);return g}if("number"===typeof a[0]||"string"===
typeof a[0]){const {set:b,handle:g}=this.objectStates.acquireSet(n.Object3DState.Highlight,c);this.objectStates.setObjectIds(b,a);return g}}return N};h.whenGraphicBounds=function(a,c){return this.graphicsCore?.whenGraphicBounds(a,c)};h.computeAttachmentOrigin=function(a,c){return this.graphicsCore?.computeAttachmentOrigin(a,c)};h.notifyGraphicGeometryChanged=function(a){this.graphicsCore.notifyGraphicGeometryChanged(a)};h.notifyGraphicVisibilityChanged=function(a){this.graphicsCore.notifyGraphicVisibilityChanged(a)};
h.getRenderingInfo=function(a,c,b){b=w.getRenderingInfo(a,{renderer:c,arcade:b});if(k.isSome(b)&&b.color){const g=b.color;g[0]/=255;g[1]/=255;g[2]/=255}k.isSome(b)&&k.isSome(c)&&this._randomRotationRenderers?.has(c)&&(c=this._randomRotationRenderers.get(c),a=a.attributes[c],c=new z.XXH(0),c.updateFloatArray([a]),c.updateUint8Array([173]),b.heading=8.381E-8*c.digest());return b};h.getRenderingInfoAsync=function(a,c,b,g){return w.getRenderingInfoAsync(a,{renderer:c,arcade:b,...g})};h.getSymbolLayerSize=
function(a,c){return this.graphicsCore?.getSymbolLayerSize(a,c)};h.setObjectIdVisibility=function(a,c){this.graphicsCore?.setObjectIdVisibility(a,c)};h.refreshFilter=function(){k.isSome(this.filterVisibility)&&this.filterVisibility.reapply()};h.getGraphics3DGraphicByObjectId=function(a){return this.graphicsCore?.getGraphics3DGraphicByObjectId(a)};h._updateClippingExtent=function(){const a=this.owner.view.clippingArea;this.graphicsCore.setClippingExtent(a,this.owner.view.spatialReference)&&(this.updateClippingExtent(a)||
this.graphicsCore.recreateAllGraphics())};h._setupSuspendResumeExtent=function(){(this.frustumVisibility||this.scaleVisibility)&&this.handles.add(m.watch(()=>this.suspendResumeExtentMode,()=>{this.handles.remove("suspendResumeExtentMode");switch(this.suspendResumeExtentMode){case "computed":this.handles.add([m.watch(()=>this.graphicsCore.computedExtent,a=>this._updateSuspendResumeExtent(a),m.initial),m.watch(()=>this.graphicsCore.extentPadding,()=>this._updateSuspendResumeExtent(this.graphicsCore.computedExtent))],
"suspendResumeExtentMode");break;case "data":this.handles.add([m.when(()=>this.dataExtent,a=>this._updateSuspendResumeExtent(a),m.initial),m.watch(()=>this.graphicsCore.extentPadding,()=>this._updateSuspendResumeExtent(k.unwrap(this.dataExtent)))],"suspendResumeExtentMode");break;default:A.neverReached(this.suspendResumeExtentMode)}},m.initial))};h._updateSuspendResumeExtent=function(a){a?this._suspendResumeExtentChanged(this._extentToSuspendResumeRect(a,this._suspendResumeExtent)):this._suspendResumeExtentChanged(null)};
h._extentToSuspendResumeRect=function(a,c){const b=this.owner.view.spatialReference;if(!a.spatialReference.equals(b)){if(!v.canProject(a,b))return;a=v.project(a,b)}return L.enlargeExtent(a,c,F.SUSPEND_RESUME_EXTENT_OPTIMISM,this.graphicsCore.extentPadding)};h._suspendResumeExtentChanged=function(a){k.isSome(this.frustumVisibility)&&this.frustumVisibility.setExtent(a);k.isSome(this.scaleVisibility)&&this.scaleVisibility.setExtent(a)};q._createClass(p,[{key:"layer",get:function(){return this.owner.layer}},
{key:"renderer",get:function(){const {renderer:a,objectIdField:c}=this.layer;if(!a||!c||"heatmap"===a.type||!a.visualVariables)return a;const b=a.visualVariables.findIndex(l=>"rotation"===l.type&&null!=l.valueExpression&&C.matchRandomRotationExpression(l.valueExpression)===c&&(null==l.axis||"heading"===l.axis)&&"geographic"===l.rotationType);if(0>b)return a;const g=a.clone();g.visualVariables.splice(b,1);this._randomRotationRenderers||(this._randomRotationRenderers=new WeakMap);this._randomRotationRenderers.set(g,
c);return g}},{key:"scaleVisibility",get:function(){return this.graphicsCore?.scaleVisibility}},{key:"filterVisibility",get:function(){return this.graphicsCore?.filterVisibility}},{key:"elevationAlignment",get:function(){return this.graphicsCore?.elevationAlignment}},{key:"objectStates",get:function(){return this.graphicsCore?.objectStates}},{key:"suspendResumeExtentMode",get:function(){return"suspendResumeExtentMode"in this.owner?this.owner.suspendResumeExtentMode:"computed"}},{key:"scaleVisibilitySuspended",
get:function(){return k.isSome(this.scaleVisibility)&&this.scaleVisibility.suspended}},{key:"suspended",get:function(){return this.owner.suspended}},{key:"legendEnabled",get:function(){return k.isNone(this.frustumVisibility)||!this.frustumVisibility.suspended}},{key:"suspendInfo",get:function(){const a={};this.scaleVisibilitySuspended&&(a.outsideScaleRange=!0);k.isSome(this.frustumVisibility)&&this.frustumVisibility.suspended&&(a.outsideOfView=!0);return a}},{key:"updating",get:function(){return!!(this.graphicsCore?.updating||
k.isSome(this.frustumVisibility)&&this.frustumVisibility.updating||this.updatingHandles?.updating)}},{key:"updatingRemaining",get:function(){return this.graphicsCore?.updatingRemaining??0}},{key:"featureStore",get:function(){return this.graphicsCore?.featureStore}},{key:"view",get:function(){return this.owner.view}},{key:"loadedGraphics",get:function(){return this.owner.loadedGraphics}},{key:"fullOpacity",get:function(){return this.owner?.fullOpacity}},{key:"filter",get:function(){return"filter"in
this.owner?this.owner.filter:null}},{key:"slicePlaneEnabled",get:function(){return this.owner.slicePlaneEnabled}},{key:"updatePolicy",get:function(){return this.owner.updatePolicy}},{key:"featureSpatialReference",get:function(){return"featureSpatialReference"in this.owner?this.owner.featureSpatialReference:this.owner.view.spatialReference}},{key:"graphics3DGraphics",get:function(){return this.graphicsCore?.graphics3DGraphics}},{key:"graphics3DGraphicsByObjectID",get:function(){return this.graphicsCore?.graphics3DGraphicsByObjectID}},
{key:"symbolUpdateType",get:function(){return this.graphicsCore?.symbolUpdateType}},{key:"displayFeatureLimit",get:function(){const a=this.view.resourceController.memoryController.memoryFactor,c=this.graphicsCore?.displayFeatureLimit;return 1===a?c:{...c,maximumNumberOfFeatures:Math.ceil(c.maximumNumberOfFeatures*a),maximumTotalNumberOfFeatures:Math.ceil(c.maximumTotalNumberOfFeatures*a),minimumTotalNumberOfFeatures:Math.ceil(c.minimumTotalNumberOfFeatures*a)}}},{key:"usedMemory",get:function(){return this.graphicsCore?.usedMemory??
0}},{key:"loadedFeatures",get:function(){return this.graphicsCore?.numberOfGraphics??0}},{key:"usedMemoryPerFeature",get:function(){return this.graphicsCore?.usedMemoryPerGraphic??0}},{key:"unprocessedMemoryEstimate",get:function(){return this.graphicsCore?.unprocessedMemoryEstimate??0}},{key:"performanceInfo",get:function(){return{core:this.graphicsCore.performanceInfo,elevationUpdating:this.elevationAlignment.updating,visibilityFrustum:k.isNone(this.frustumVisibility)||!this.frustumVisibility.suspended,
visibilityScale:!this.scaleVisibilitySuspended}}}]);return p}(d.HandleOwner);e.__decorate([f.property()],d.prototype,"type",void 0);e.__decorate([f.property({constructOnly:!0})],d.prototype,"owner",void 0);e.__decorate([f.property()],d.prototype,"layer",null);e.__decorate([f.property()],d.prototype,"renderer",null);e.__decorate([f.property({constructOnly:!0})],d.prototype,"updateClippingExtent",void 0);e.__decorate([f.property({constructOnly:!0})],d.prototype,"elevationFeatureExpressionEnabled",void 0);
e.__decorate([f.property({constructOnly:!0})],d.prototype,"graphicsCore",void 0);e.__decorate([f.property({constructOnly:!0})],d.prototype,"scaleVisibilityEnabled",void 0);e.__decorate([f.property({constructOnly:!0})],d.prototype,"filterVisibilityEnabled",void 0);e.__decorate([f.property({constructOnly:!0})],d.prototype,"frustumVisibilityEnabled",void 0);e.__decorate([f.property({constructOnly:!0})],d.prototype,"elevationAlignmentEnabled",void 0);e.__decorate([f.property({constructOnly:!0})],d.prototype,
"timeExtentEnabled",void 0);e.__decorate([f.property({constructOnly:!0})],d.prototype,"setUidToIdOnAdd",void 0);e.__decorate([f.property()],d.prototype,"scaleVisibility",null);e.__decorate([f.property()],d.prototype,"filterVisibility",null);e.__decorate([f.property()],d.prototype,"elevationAlignment",null);e.__decorate([f.property({constructOnly:!0})],d.prototype,"frustumVisibility",void 0);e.__decorate([f.property()],d.prototype,"objectStates",null);e.__decorate([f.property()],d.prototype,"initializePromise",
void 0);e.__decorate([f.property()],d.prototype,"suspendResumeExtentMode",null);e.__decorate([f.property()],d.prototype,"dataExtent",void 0);e.__decorate([f.property()],d.prototype,"scaleVisibilitySuspended",null);e.__decorate([f.property()],d.prototype,"suspended",null);e.__decorate([f.property()],d.prototype,"legendEnabled",null);e.__decorate([f.property()],d.prototype,"suspendInfo",null);e.__decorate([f.property()],d.prototype,"updating",null);e.__decorate([f.property()],d.prototype,"updatingRemaining",
null);e.__decorate([f.property()],d.prototype,"featureStore",null);e.__decorate([f.property()],d.prototype,"view",null);e.__decorate([f.property()],d.prototype,"loadedGraphics",null);e.__decorate([f.property()],d.prototype,"fullOpacity",null);e.__decorate([f.property()],d.prototype,"filter",null);e.__decorate([f.property()],d.prototype,"slicePlaneEnabled",null);e.__decorate([f.property()],d.prototype,"drapeSourceType",void 0);e.__decorate([f.property()],d.prototype,"updatePolicy",null);e.__decorate([f.property()],
d.prototype,"preferredUpdatePolicy",void 0);e.__decorate([f.property()],d.prototype,"displayFeatureLimit",null);d=e.__decorate([B.subclass("esri.views.3d.layers.graphics.Graphics3DFeatureProcessor")],d);const N={remove(){},pause(){},resume(){}};return d});