// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.25/esri/copyright.txt for details.
//>>built
define("../../../../chunks/_rollupPluginBabelHelpers ../../../../core/maybe ../../../../chunks/vec3 ../../../../chunks/vec3f64 ../../../../geometry/support/aaBoundingBox ../../../../geometry/support/aaBoundingRect ./graphicUtils ../../webgl-engine/lib/basicInterfaces ../../webgl-engine/lib/ModelDirtyTypes".split(" "),function(t,u,v,p,g,w,x,y,n){let z=function(){function q(a,b,c,k){this.graphics3DSymbolLayer=a;this.renderGeometries=b;this.boundingBox=c;this._drapeSourceRenderer=k;this.type="draped";
this.stage=null;this.isElevationSource=this._addedToStage=this._visible=!1}var d=q.prototype;d.initialize=function(a){this.stage=a};d.setVisibility=function(a){if(null!=this.stage&&this._visible!==a)if((this._visible=a)&&!this._addedToStage)this._addedToStage=!0,this._drapeSourceRenderer.addGeometries(this.renderGeometries,n.DirtyOperation.ADD);else if(a||this._addedToStage){for(const b of this.renderGeometries)b.instanceParameters.visible=this._visible;this._drapeSourceRenderer.modifyGeometries(this.renderGeometries,
n.DirtyState.VISIBILITIES)}};d.destroy=function(){this.stage&&this._addedToStage&&this._drapeSourceRenderer.removeGeometries(this.renderGeometries,n.DirtyOperation.REMOVE);this._visible=this._addedToStage=!1;this.stage=null};d.getCenterObjectSpace=function(a=p.create()){return v.set(a,0,0,0)};d.getBoundingBoxObjectSpace=function(a=g.create()){return g.empty(a)};d.addObjectState=function(a,b){a===y.Object3DState.Highlight&&(this.renderGeometries.forEach(c=>{const k=c.addHighlight();b.addRenderGeometry(c,
k,this)}),this._addedToStage&&this._drapeSourceRenderer.modifyGeometries(this.renderGeometries,n.DirtyState.HIGHLIGHTS))};d.removeObjectState=function(a){this.renderGeometries.forEach(b=>{a.removeRenderGeometry(b)})};d.removeRenderGeometryObjectState=function(a,b){a.removeHighlight(b);this._addedToStage&&this._drapeSourceRenderer.modifyGeometries(this.renderGeometries,n.DirtyState.HIGHLIGHTS)};d.computeAttachmentOrigin=function(a){for(const b of this.renderGeometries)b.computeAttachmentOrigin(m)&&
(a.draped.origin[0]+=m[0],a.draped.origin[1]+=m[1],a.draped.num++)};d.getProjectedBoundingBox=function(){var a=t._asyncToGenerator(function*(b,c,k,h,e){g.empty(e);for(let l=0;l<this.renderGeometries.length;l++)this._getRenderGeometryProjectedBoundingRect(this.renderGeometries[l],b,r,k),g.expandWithRect(e,r);if(c){g.center(e,m);let l;b=x.demResolutionForBoundingBox(e,c.service.spatialReference,c);try{l=yield c.service.queryElevation(m[0],m[1],h,b,"ground")}catch(A){}u.isSome(l)&&(e[2]=Math.min(e[2],
l),e[5]=Math.max(e[5],l))}return e});return function(b,c,k,h,e){return a.apply(this,arguments)}}();d._getRenderGeometryProjectedBoundingRect=function(a,b,c,k){if(this.boundingBox)g.set(f,this.boundingBox);else{a=a.boundingSphere;const h=a[3];f[0]=a[0]-h;f[1]=a[1]-h;f[2]=a[2]-h;f[3]=a[0]+h;f[4]=a[1]+h;f[5]=a[2]+h}b(f,0,2);this.calculateRelativeScreenBounds&&k.push({location:g.center(f),screenSpaceBoundingRect:this.calculateRelativeScreenBounds()});return g.toRect(f,c)};return q}();const r=w.create(),
f=g.create(),m=p.create();return z});