// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.25/esri/copyright.txt for details.
//>>built
define("../../../../../../chunks/_rollupPluginBabelHelpers ../../../../../../core/maybe ../../definitions ../../enums ../../number ../../TurboLine ../../materialKey/MaterialKey ./templateUtils".split(" "),function(v,r,w,x,m,y,p,z){const A=(c,n,l)=>(e,a,b,f,d,g,k,h,q,t,u)=>{b=m.i1616to32(u,Math.ceil(16*c._halfWidth));k=m.i8888to32(Math.round(16*k),Math.round(16*h),Math.round(16*q),Math.round(16*t));d=m.i8888to32(16*d,16*g,0,c._bitset);g=c.out;g.vertexBounds(e,a,n,l);g.vertexWrite(m.i1616to32(8*e,8*
a));g.vertexWrite(c.id);g.vertexWrite(c._fillColor);g.vertexWrite(k);g.vertexWrite(b);g.vertexWrite(c._tl);g.vertexWrite(c._br);g.vertexWrite(d);g.vertexWrite(m.i1616to32(Math.ceil(16*c._halfReferenceWidth),0));g.vertexWrite(c.minMaxZoom);g.vertexEnd();return c.offset+c.vertexCount++},B=(c,n,l)=>(e,a,b,f,d,g,k,h,q,t,u)=>{b=m.i1616to32(16*c._halfWidth,16*c._halfReferenceWidth);k=m.i8888to32(16*k+128,16*h+128,16*q+128,16*t+128);h=c.out;q=c._bitset<<24|c.id;h.vertexBounds(e,a,n,l);h.vertexWrite(m.i1616to32(8*
e,8*a));h.vertexWrite(q);h.vertexWrite(c._fillColor);e=p.hasSimpleSymbology(c.key);e||(h.vertexWrite(0),h.vertexWrite(0));h.vertexWrite(0);h.vertexWrite(b);h.vertexWrite(k);e||h.vertexWrite(c.minMaxZoom);h.vertexEnd();return c.offset+c.vertexCount++},C=c=>(n,l,e)=>{const a=c.out;a.indexWrite(n);a.indexWrite(l);a.indexWrite(e);c.indexCount+=3};return c=>function(n){function l(...a){a=n.call(this,...a)||this;a.tessellationProperties={};a._tessellationOptions={halfWidth:0,pixelCoordRatio:1,offset:0};
a.geometryType=x.WGLGeometryType.LINE;return a}v._inheritsLoose(l,n);var e=l.prototype;e.writeGeometry=function(a,b,f,d){this._writeGeometry(a,b,f,d)};e._initializeTessellator=function(a){var b=p.LineMaterialKey.load(this._materialKey),f=p.FillMaterialKey.load(this._materialKey),d=this._tessellationOptions;b=b.vvSizeFieldStops||b.vvSizeMinMaxValue||b.vvSizeScaleStops||b.vvSizeUnitValue;a=this.tessellationProperties._halfWidth<w.THIN_LINE_HALF_WIDTH_THRESHOLD&&!a&&!b;this.tessellationProperties.minMaxZoom=
this._minMaxZoom;d.wrapDistance=65535;d.textured=this._isDashed||this._hasPattern;d.offset=this.tessellationProperties.offset;d.halfWidth=this.tessellationProperties._halfWidth;d=a?0:1;f=p.hasOutlineFillSymbology(f)?B:A;this._lineTessellator=new y.LineTessellation(f(this.tessellationProperties,d,d),C(this.tessellationProperties),a)};e._write=function(a,b,f,d){f="esriGeometryPoint"===b.geometryType;a.recordStart(b.getDisplayId(),this._materialKey,this.geometryType,f);this._writeGeometry(a,b,d,f);a.recordEnd()};
e._writeGeometry=function(a,b,f,d){f=f??b.readLegacyGeometryForDisplay();d=this._getLines(f,d);r.isNone(d)||this._writeVertices(a,b,d)};e._getLines=function(a,b){if(r.isNone(a))return null;a=a.paths||a.rings;return r.isNone(a)?null:z.clipLinesMarshall(a,b?256:16)};e._writeVertices=function(a,b,f){const d=b.getDisplayId(),g=a.vertexCount(),k=this.tessellationProperties;b=this._tessellationOptions;k.out=a;k.id=d;k.indexCount=0;k.vertexCount=0;k.offset=g;b.capType=this._capType;b.joinType=this._joinType;
a=p.FillMaterialKey.load(this._materialKey);this.tessellationProperties.key=p.hasOutlineFillSymbology(a)?a:p.LineMaterialKey.load(this._materialKey);for(const {line:h,start:q}of f)b.initialDistance=q%65535,this._lineTessellator.tessellate(h,b)};return l}(c)});