// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.25/esri/copyright.txt for details.
//>>built
define("../../../chunks/_rollupPluginBabelHelpers ../../../chunks/tslib.es6 ../../../core/Accessor ../../../core/maybe ../../../core/accessorSupport/decorators/property ../../../core/arrayUtils ../../../core/accessorSupport/ensureType ../../../core/accessorSupport/decorators/subclass ../../../chunks/vec2 ../../support/QueueProcessor".split(" "),function(x,m,h,B,p,G,H,C,D,E){function F(q,r){q.length=0;r.forEach(d=>q.push(d));return q}const w=new Set,u=[],t=new Map,y=[0,0];h=function(q){function r(a){a=
q.call(this,a)||this;a._keyToItem=new Map;a.concurrency=6;a.strategy="scale-first";a.tileInfoView=null;return a}x._inheritsLoose(r,q);var d=r.prototype;d.initialize=function(){const {concurrency:a,process:k}=this;this._queue=new E.QueueProcessor({concurrency:a,process:(b,g)=>{b=this._keyToItem.get(b);return k(b,{signal:g})},peeker:b=>b.values().next().value})};d.destroy=function(){this.clear();this._queue=B.destroyMaybe(this._queue)};d.abort=function(a){this._queue.abort("string"===typeof a?a:a.id)};
d.clear=function(){this._queue.clear();this._keyToItem.clear();this.notifyChange("updating")};d.has=function(a){return"string"===typeof a?this._keyToItem.has(a):this._keyToItem.has(a.id)};d.isOngoing=function(a){a="string"===typeof a?a:a.id;return this.has(a)&&this._queue.isOngoing(a)};d.pause=function(){this._queue.pause()};d.push=function(a,k){const b=a.key.id+"-"+k;if(this.has(b))return this.get(b);k=this._queue.push(b);const g=()=>{this._keyToItem.delete(b);this.notifyChange("updating")};this._keyToItem.set(b,
a);k.then(g,g);this.notifyChange("updating");return k};d.reset=function(){this._queue.reset();this.notifyChange("updating")};d.resume=function(){this._queue.resume()};d._peekByScaleFirst=function(a){if(!this.state)return a.values().next().value;const k=this.tileInfoView;let b=Number.NEGATIVE_INFINITY,g=Number.POSITIVE_INFINITY;a.forEach(e=>{e=this._keyToItem.get(e);const c=this.tileInfoView.getTileScale(e.key);t.has(c)||(t.set(c,[]),b=Math.max(c,b),g=Math.min(c,g));t.get(c).push(e.key);w.add(c)});
let f=this.state.scale;t.has(f)||(F(u,w),u.sort((e,c)=>e-c),f=u.reduce((e,c)=>Math.abs(c-f)<Math.abs(e-f)?c:e,u[0]));f=Math.min(f,b);f=Math.max(f,g);a=t.get(f);const l=k.getClosestInfoForScale(f),n=l.getColumnForX(this.state.center[0]),v=l.getRowForY(this.state.center[1]);a.sort((e,c)=>{const z=l.denormalizeCol(e.col,e.world),A=l.denormalizeCol(c.col,c.world);return Math.sqrt((n-z)*(n-z)+(v-e.row)*(v-e.row))-Math.sqrt((n-A)*(n-A)+(v-c.row)*(v-c.row))});w.clear();t.clear();return a[0].id};d._peekByCenterFirst=
function(a){if(!this.state)return a.values().next().value;const k=this.tileInfoView,b=this.state.center;let g=Number.POSITIVE_INFINITY,f;a.forEach(l=>{l=this._keyToItem.get(l);k.getTileCoords(y,l.key);const n=D.distance(y,b);n<g&&(g=n,f=l.key)});return f.id};x._createClass(r,[{key:"length",get:function(){return this._queue?this._queue.length:0}},{key:"onGoingCount",get:function(){return this._keyToItem.size}},{key:"updating",get:function(){return 0<this.length||0<this.onGoingCount}}]);return r}(h);
m.__decorate([p.property({constructOnly:!0})],h.prototype,"concurrency",void 0);m.__decorate([p.property({constructOnly:!0})],h.prototype,"process",void 0);m.__decorate([p.property()],h.prototype,"state",void 0);m.__decorate([p.property({constructOnly:!0})],h.prototype,"strategy",void 0);m.__decorate([p.property({constructOnly:!0})],h.prototype,"tileInfoView",void 0);m.__decorate([p.property({readOnly:!0})],h.prototype,"updating",null);return h=m.__decorate([C.subclass("esri.views.2d.tiling.PagedTileQueue")],
h)});