// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.25/esri/copyright.txt for details.
//>>built
define(["exports","../../../core/maybe","../PixelBlock"],function(y,D,E){function F(a){return D.isSome(a)&&"esri.layers.support.PixelBlock"===a.declaredClass&&a.pixels&&0<a.pixels.length}function Q(a,b,c,d,f){const e=a.length;f=E.createEmptyBand(f,e);if(b)for(let g=0;g<e;g++)b[g]&&(f[g]=c[a[g]-d]);else for(b=0;b<e;b++)f[b]=c[a[b]-d];return f}function R(a,b,c,d){const f=null!=c&&2<=c.length?new Set(c):null;c=1===c?.length?c[0]:null;const e=!!b?.length;for(let g=0;g<a.length;g++)if(d[g]){const k=a[g];
if(e){let h=!1;for(let p=0;p<b.length;p+=2)if(k>=b[p]&&k<=b[p+1]){h=!0;break}h||(d[g]=0)}d[g]&&(k===c||f?.has(k))&&(d[g]=0)}}function S(a,b){const c=a[0].length;for(let d=0;d<c;d++)if(b[d]){let f=!1;for(let e=0;e<a.length;e++)if(a[e][d]){f=!0;break}f||(b[d]=0)}}function T(a,b){const c=a[0].length;for(let d=0;d<c;d++)if(b[d]){let f=!1;for(let e=0;e<a.length;e++)if(0===a[e][d]){f=!0;break}f&&(b[d]=0)}}function U(a,b,c,d,f,e,g,k){return{xmin:f<=c*a?0:f<c*a+a?f-c*a:a,ymin:e<=d*b?0:e<d*b+b?e-d*b:b,xmax:f+
g<=c*a?0:f+g<c*a+a?f+g-c*a:a,ymax:e+k<=d*b?0:e+k<d*b+b?e+k-d*b:b}}function M(a,b,c,d,f,e){const {width:g,height:k}=c.block,{x:h,y:p}=c.offset,{width:q,height:m}=c.mosaic;c=U(g,k,d,f,h,p,q,m);let l=0;var n=0;if(e){var r=e.hasGCSSShiftTransform?360:e.halfWorldWidth??0,t=g*e.resolutionX;const u=e.startX+d*t;u<r&&u+t>r?n=e.rightPadding:u>=r&&(l=e.leftMargin-e.rightPadding,n=0)}c.xmax-=n;if("number"===typeof b)for(e=c.ymin;e<c.ymax;e++)for(n=(f*k+e-p)*q+(d*g-h)+l,r=c.xmin;r<c.xmax;r++)a[n+r]=b;else for(e=
c.ymin;e<c.ymax;e++)for(n=(f*k+e-p)*q+(d*g-h)+l,r=e*g,t=c.xmin;t<c.xmax;t++)a[n+t]=b[r+t]}function V(a,b,c={}){const {clipOffset:d,clipSize:f,alignmentInfo:e,blockWidths:g}=c;if(g)return ba(a,b,{blockWidths:g});var k=a.find(w=>F(w));if(D.isNone(k))return null;c=f?f.width:b.width;const h=f?f.height:b.height;var p=k.width,q=k.height;const m=b.width/p,l=b.height/q;b={offset:d||{x:0,y:0},mosaic:f||b,block:{width:p,height:q}};p=k.pixelType;q=E.getPixelArrayConstructor(p);var n=k.pixels.length;k=[];for(var r=
0;r<n;r++){var t=new q(c*h);for(let w=0;w<l;w++)for(let x=0;x<m;x++){var u=a[w*m+x];F(u)&&(u=u.pixels[r],M(t,u,b,x,w,e))}k.push(t)}let v;if(a.some(w=>D.isNone(w)||D.isSome(w.mask)&&0<w.mask.length))for(v=new Uint8Array(c*h),q=0;q<l;q++)for(n=0;n<m;n++)t=a[q*m+n],r=D.isSome(t)?t.mask:null,D.isSome(r)?M(v,r,b,n,q,e):t?M(v,1,b,n,q,e):M(v,0,b,n,q,e);a=new E({width:c,height:h,pixels:k,pixelType:p,mask:v});a.updateStatistics();return a}function ba(a,b,c){const d=a.find(n=>D.isSome(n));if(D.isNone(d))return null;
var f=a.some(n=>D.isSome(n)?!!n.mask:!0);const {width:e,height:g}=b;b=f?new Uint8Array(e*g):null;({blockWidths:c}=c);const k=[],h=d.getPlaneCount(),p=E.getPixelArrayConstructor(d.pixelType);if(f)for(let n=0,r=0;n<a.length;r+=c[n],n++)if(f=a[n],F(f)){var q=D.unwrap(f.mask);for(var m=0;m<g;m++)for(var l=0;l<c[n];l++)b[m*e+l+r]=null==q?255:q[m*f.width+l]}for(f=0;f<h;f++){q=new p(e*g);for(let n=0,r=0;n<a.length;r+=c[n],n++)if(m=a[n],F(m)&&(l=m.pixels[f],null!=l))for(let t=0;t<g;t++)for(let u=0;u<c[n];u++)q[t*
e+u+r]=l[t*m.width+u];k.push(q)}a=new E({width:e,height:g,mask:b,pixels:k,pixelType:d.pixelType});a.updateStatistics();return a}function W(a){if(!F(a))return null;const b=a.clone(),{width:c,height:d,pixels:f}=a;var e=f[0];const g=b.pixels[0];a=D.unwrap(a.mask);for(let p=2;p<d-1;p++){const q=new Map;for(var k=p-2;k<p+2;k++)for(var h=0;4>h;h++){const m=k*c+h;L(q,e[m],a?a[m]:1)}g[p*c]=X(q);g[p*c+1]=g[p*c+2]=g[p*c];for(k=3;k<c-1;k++)h=(p-2)*c+k+1,L(q,e[h],a?a[h]:1),h=(p-1)*c+k+1,L(q,e[h],a?a[h]:1),h=
p*c+k+1,L(q,e[h],a?a[h]:1),h=(p+1)*c+k+1,L(q,e[h],a?a[h]:1),h=(p-2)*c+k-3,N(q,e[h],a?a[h]:1),h=(p-1)*c+k-3,N(q,e[h],a?a[h]:1),h=p*c+k-3,N(q,e[h],a?a[h]:1),h=(p+1)*c+k-3,N(q,e[h],a?a[h]:1),g[p*c+k]=X(q);g[p*c+k+1]=g[p*c+k]}for(e=0;e<c;e++)g[e]=g[c+e]=g[2*c+e],g[(d-1)*c+e]=g[(d-2)*c+e];b.updateStatistics();return b}function X(a){if(0===a.size)return 0;let b=0,c=-1,d=0;const f=a.keys();let e=f.next();for(;!e.done;)d=a.get(e.value),d>b&&(c=e.value,b=d),e=f.next();return c}function N(a,b,c){0!==c&&(c=
a.get(b),1===c?a.delete(b):a.set(b,c-1))}function L(a,b,c){0!==c&&a.set(b,a.has(b)?a.get(b)+1:1)}function Y(a,b,c){let {x:d,y:f}=b;const {width:e,height:g}=c;if(0===d&&0===f&&g===a.height&&e===a.width)return a;const {width:k,height:h}=a;b=Math.max(0,f);const p=Math.max(0,d),q=Math.min(d+e,k),m=Math.min(f+g,h);if(0>q||0>m||!F(a))return null;d=Math.max(0,-d);f=Math.max(0,-f);var {pixels:l}=a,n=e*g,r=l.length;const t=[];for(var u=0;u<r;u++){var v=l[u],w=E.createEmptyBand(a.pixelType,n);for(let x=b;x<
m;x++){const C=x*k;let A=(x+f-b)*e+d;for(let H=p;H<q;H++)w[A++]=v[C+H]}t.push(w)}l=new Uint8Array(n);n=D.unwrap(a.mask);for(r=b;r<m;r++)for(u=r*k,v=(r+f-b)*e+d,w=p;w<q;w++)l[v++]=n?n[u+w]:1;a=new E({width:c.width,height:c.height,pixelType:a.pixelType,pixels:t,mask:l});a.updateStatistics();return a}function ca(a,b=!0){if(!F(a))return null;const {pixels:c,width:d,height:f,mask:e,pixelType:g}=a;a=[];const k=Math.round(d/2),h=Math.round(f/2),p=f-1,q=d-1;for(var m=0;m<c.length;m++){var l=c[m],n=E.createEmptyBand(g,
k*h),r=0;for(var t=0;t<f;t+=2)for(var u=0;u<d;u+=2){var v=l[t*d+u];if(b){var w=u===q?v:l[t*d+u+1];const x=t===p?v:l[t*d+u+d],C=u===q?x:t===p?w:l[t*d+u+d+1];n[r++]=(v+w+x+C)/4}else n[r++]=v}a.push(n)}m=null;if(D.isSome(e))for(m=new Uint8Array(k*h),l=0,n=0;n<f;n+=2)for(r=0;r<d;r+=2)t=e[n*d+r],b?(u=r===q?t:e[n*d+r+1],v=n===p?t:e[n*d+r+d],w=r===q?v:n===p?u:e[n*d+r+d+1],m[l++]=t*u*v*w?1:0):m[l++]=t;return new E({width:k,height:h,pixelType:g,pixels:a,mask:m})}function Z(a,b,c,d,f=.5){const {width:e,height:g}=
a,{width:k,height:h}=b;a=d.cols;d=d.rows;b=Math.ceil(k/a-.1/a);const p=Math.ceil(h/d-.1/d);let q,m,l,n,r;const t=b*a;var u=t*p*d;const v=new Float32Array(u),w=new Float32Array(u),x=new Uint32Array(u),C=new Uint32Array(u);let A=0,H,K;for(let I=0;I<p;I++)for(let J=0;J<b;J++){var z=12*(I*b+J);u=c[z];q=c[z+1];m=c[z+2];l=c[z+3];n=c[z+4];r=c[z+5];for(var B=0;B<d;B++){A=(I*d+B)*t+J*a;K=(B+.5)/d;for(let G=0;G<B;G++)H=(G+.5)/a,v[A+G]=(u*H+q*K+m)*e-f,w[A+G]=(l*H+n*K+r)*g-f,x[A+G]=Math.round(v[A+G]),C[A+G]=
Math.round(w[A+G])}z+=6;u=c[z];q=c[z+1];m=c[z+2];l=c[z+3];n=c[z+4];r=c[z+5];for(z=0;z<d;z++)for(A=(I*d+z)*t+J*a,K=(z+.5)/d,B=z;B<a;B++)H=(B+.5)/a,v[A+B]=(u*H+q*K+m)*e-f,w[A+B]=(l*H+n*K+r)*g-f,x[A+B]=Math.round(v[A+B]),C[A+B]=Math.round(w[A+B])}return{offsets_x:v,offsets_y:w,offsets_xi:x,offsets_yi:C,gridWidth:t}}y.NoDataInterpretation=void 0;(function(a){a[a.matchAny=0]="matchAny";a[a.matchAll=1]="matchAll"})(y.NoDataInterpretation||(y.NoDataInterpretation={}));y.MissingBandAction=void 0;(function(a){a[a.bestMatch=
0]="bestMatch";a[a.fail=1]="fail"})(y.MissingBandAction||(y.MissingBandAction={}));y.approximateTransform=function(a,b,c,d,f="nearest"){if(!F(a))return null;"majority"===f&&(a=W(a));const {pixels:e,mask:g,pixelType:k}=a,h=a.width;var p=a.height;const q=E.getPixelArrayConstructor(k),m=e.length,{width:l,height:n}=b;a=!1;for(let C=0;C<c.length;C+=3)-1===c[C]&&-1===c[C+1]&&-1===c[C+2]&&(a=!0);const {offsets_x:r,offsets_y:t,offsets_xi:u,offsets_yi:v,gridWidth:w}=Z({width:h,height:p},b,c,d,"majority"===
f?0:.5);let x;b=(C,A,H)=>{const K=C instanceof Float32Array||C instanceof Float64Array?0:.5;for(let z=0;z<n;z++){x=z*w;for(let B=0;B<l;B++){if(0>r[x]||0>t[x])C[z*l+B]=0;else if(H)C[z*l+B]=A[u[x]+v[x]*h];else{const I=Math.floor(r[x]),J=Math.floor(t[x]),G=Math.ceil(r[x]),O=Math.ceil(t[x]),P=r[x]-I,aa=t[x]-J;C[z*l+B]=!g||g[I+J*h]&&g[I+J*h]&&g[I+O*h]&&g[G+O*h]?(1-aa)*((1-P)*A[I+J*h]+P*A[G+J*h])+aa*((1-P)*A[I+O*h]+P*A[G+O*h])+K:A[u[x]+v[x]*h]}x++}}};c=[];for(p=0;p<m;p++)d=new q(l*n),b(d,e[p],"nearest"===
f||"majority"===f),c.push(d);f=new E({width:l,height:n,pixelType:k,pixels:c});if(D.isSome(g))f.mask=new Uint8Array(l*n),b(f.mask,g,!0);else if(a)for(f.mask=new Uint8Array(l*n),a=0;a<l*n;a++)f.mask[a]=0>r[a]||0>t[a]?0:1;f.updateStatistics();return f};y.clip=Y;y.colorize=function(a,b){if(!F(a)||!b||!b.indexedColormap&&!b.indexed2DColormap)return a;const c=a.clone();var d=c.pixels;let f=c.mask;const e=c.width*c.height;if(1!==d.length)return a;const {indexedColormap:g,indexed2DColormap:k,offset:h,alphaSpecified:p}=
b;a=0;d=d[0];b=new Uint8Array(d.length);const q=new Uint8Array(d.length),m=new Uint8Array(d.length);var l=0;if(g){const n=g.length-1;if(D.isSome(f))for(a=0;a<e;a++)f[a]&&(l=4*(d[a]-h),l<h||l>n?f[a]=0:(b[a]=g[l],q[a]=g[l+1],m[a]=g[l+2],f[a]=g[l+3]));else{f=new Uint8Array(e);for(a=0;a<e;a++)l=4*(d[a]-h),l<h||l>n?f[a]=0:(b[a]=g[l],q[a]=g[l+1],m[a]=g[l+2],f[a]=g[l+3]);c.mask=f}}else if(k)if(D.isSome(f))for(a=0;a<e;a++)f[a]&&(l=k[d[a]],b[a]=l[0],q[a]=l[1],m[a]=l[2],f[a]=l[3]);else{f=new Uint8Array(e);
for(a=0;a<e;a++)l=k[d[a]],b[a]=l[0],q[a]=l[1],m[a]=l[2],f[a]=l[3];c.mask=f}c.pixels=[b,q,m];c.statistics=null;c.pixelType="u8";c.maskIsAlpha=p;return c};y.compositeBands=function(a){if(!a?.length||a.some(h=>!F(h)))return null;if(1===a.length)return D.isSome(a[0])?a[0].clone():null;const {width:b,height:c,pixelType:d}=a[0];if(a.some(h=>h.width!==b||h.height!==c))return null;const f=a.map(({mask:h})=>h).filter(h=>null!=h);let e=null;f.length&&(e=new Uint8Array(b*c),e.set(f[0]),1<f.length&&T(f.slice(1),
e));const g=[];a.forEach(({pixels:h})=>g.push(...h));const k=[];a.map(({statistics:h})=>h).filter(h=>h?.length).forEach(h=>k.push(...h));return new E({pixelType:d,width:b,height:c,mask:e,pixels:g,statistics:k.length?k:null})};y.createColormapLUT=function(a){if(a){var b=a.colormap;if(b&&0!==b.length){b=b.sort((p,q)=>p[0]-q[0]);var c=0;0>b[0][0]&&(c=b[0][0]);var d=Math.max(256,b[b.length-1][0]-c+1),f=new Uint8Array(4*d),e=[],g=0,k=0,h=5===b[0].length;if(65536<d)return b.forEach(p=>{e[p[0]-c]=h?p.slice(1):
p.slice(1).concat([255])}),{indexed2DColormap:e,offset:c,alphaSpecified:h};if(a.fillUnspecified)for(a=b[k],g=a[0]-c;g<d;g++)f[4*g]=a[1],f[4*g+1]=a[2],f[4*g+2]=a[3],f[4*g+3]=h?a[4]:255,g===a[0]-c&&(a=k===b.length-1?a:b[++k]);else for(g=0;g<b.length;g++)a=b[g],k=4*(a[0]-c),f[k]=a[1],f[k+1]=a[2],f[k+2]=a[3],f[k+3]=h?a[4]:255;return{indexedColormap:f,offset:c,alphaSpecified:h}}}};y.createMaskLUT=function(a,b,c){if("u8"!==a&&"s8"!==a&&"u16"!==a&&"s16"!==a)return null;var d=a.includes("16")?65536:256;a=
a.includes("s")?-d/2:0;d=new Uint8Array(d);if(b)for(let e=0;e<b.length;e++){var f=Math.ceil(b[2*e]-a);const g=Math.floor(b[2*e+1]-a);for(;f<=g;f++)d[f]=255}if(c)for(b=0;b<c.length;b++)d[c[b]-a]=0;return{lut:d,offset:a}};y.createRemapLUT=function(a,b,c){if("u8"!==a&&"s8"!==a&&"u16"!==a&&"s16"!==a)return null;var d=a.includes("16")?65536:256;const f=a.includes("s")?-d/2:0;a=E.createEmptyBand(a,d);for(d=0;d<b.length;d++){const g=c[d];var e=Math.ceil(b[2*d]-f);const k=Math.floor(b[2*d+1]-f);for(;e<=k;e++)a[e]=
g}return{lut:a,offset:f}};y.extractBands=function(a,b){if(!b?.length||!F(a))return a;const c=a.pixels.length;return b&&b.some(d=>d>=c)||1===c&&1===b.length&&0===b[0]||c===b.length&&!b.some((d,f)=>d!==f)?a:new E({pixelType:a.pixelType,width:a.width,height:a.height,mask:a.mask,validPixelCount:a.validPixelCount,maskIsAlpha:a.maskIsAlpha,pixels:b.map(d=>a.pixels[d]),statistics:a.statistics&&b.map(d=>a.statistics[d])})};y.getClipBounds=U;y.getLocalArithmeticNorthRotations=function(a,b){const {coefficients:c,
spacing:d}=b,{offsets_x:f,offsets_y:e,gridWidth:g}=Z(a,a,c,{rows:d[0],cols:d[1]},.5),{width:k,height:h}=a;a=new Float32Array(k*h);b=180/Math.PI;for(let m=0;m<h;m++)for(let l=0;l<k;l++){var p=m*g+l,q=0===m?p:p-g;const n=m===h-1?p:p+g;p=f[q]-f[n];q=e[n]-e[q];isNaN(p)||isNaN(q)?a[m*k+l]=90:(q=Math.atan2(q,p)*b,q=(360+q)%360,a[m*k+l]=q)}return a};y.isValidPixelBlock=F;y.lookupBandValues=Q;y.lookupPixels=function(a,b){if(!F(a))return null;const {pixels:c,mask:d}=a,f=c.length;let e=b.lut;const {offset:g}=
b;e&&1===e[0].length&&(e=c.map(()=>e));const k=[];b=b.outputPixelType||"u8";for(let h=0;h<f;h++){const p=Q(c[h],d,e[h],g||0,b);k.push(p)}a=new E({width:a.width,height:a.height,pixels:k,mask:d,pixelType:b});a.updateStatistics();return a};y.mask=function(a,b){if(!F(a))return null;const {width:c,height:d,pixels:f}=a;var e=c*d;const g=new Uint8Array(e);a.mask?g.set(a.mask):g.fill(255);a=f.length;const {includedRanges:k,noDataValues:h,outputPixelType:p,matchAll:q,lookup:m}=b;if(m){e=[];for(b=0;b<a;b++){var l=
Q(f[b],g,m.lut,m.offset||0,"u8");e.push(l)}1===e.length?g.set(e[0]):q?S(e,g):T(e,g)}else if(q){b=[];for(l=0;l<a;l++){const n=new Uint8Array(e);n.set(g);R(f[l],k,h,n);b.push(n)}1===b.length?g.set(b[0]):S(b,g)}else for(e=0;e<a;e++)R(f[e],k,h,g);return new E({width:c,height:d,pixelType:p,pixels:f,mask:g})};y.mosaic=V;y.mosaicPixelData=function(a,b){if(!a||0===a.length)return null;var c=a.find(m=>m.pixelBlock);if(!c||D.isNone(c.pixelBlock))return null;var d=(c.extent.xmax-c.extent.xmin)/c.pixelBlock.width;
const f=(c.extent.ymax-c.extent.ymin)/c.pixelBlock.height,e=.01*Math.min(d,f),g=a.sort((m,l)=>Math.abs(m.extent.ymax-l.extent.ymax)>e?l.extent.ymax-m.extent.ymax:Math.abs(m.extent.xmin-l.extent.xmin)>e?m.extent.xmin-l.extent.xmin:0);var k=Math.min.apply(null,g.map(m=>m.extent.xmin));const h=Math.min.apply(null,g.map(m=>m.extent.ymin)),p=Math.max.apply(null,g.map(m=>m.extent.xmax)),q=Math.max.apply(null,g.map(m=>m.extent.ymax));a={x:Math.round((b.xmin-k)/d),y:Math.round((q-b.ymax)/f)};k={width:Math.round((p-
k)/d),height:Math.round((q-h)/f)};d={width:Math.round((b.xmax-b.xmin)/d),height:Math.round((b.ymax-b.ymin)/f)};if(Math.round(k.width/c.pixelBlock.width)*Math.round(k.height/c.pixelBlock.height)!==g.length||0>a.x||0>a.y||k.width<d.width||k.height<d.height)return null;c=g.map(m=>m.pixelBlock);c=V(c,k,{clipOffset:a,clipSize:d});return{extent:b,pixelBlock:c}};y.remap=function(a,b){if(!F(a))return null;const {width:c,height:d}=a,{inputRanges:f,outputValues:e,outputPixelType:g,noDataRanges:k,allowUnmatched:h}=
b;b=a.pixels[0];const p=E.createEmptyBand(g,b.length);h&&p.set(b);a=a.mask;const q=f.length/2;for(var m=0;m<d;m++)for(var l=0;l<c;l++){var n=m*c+l;if(!a||a[n]){var r=b[n];for(var t=q-1;0<=t;t--)if(r>=f[2*t]&&r<=f[2*t+1]){p[n]=e[t];break}}}m=a;if(k?.length)for(m=new Uint8Array(c*d),a&&m.set(a),l=0;l<d;l++)for(n=0;n<c;n++)if(r=l*c+n,!a||a[r]){t=b[r];for(let u=0;u<q;u+=2)if(t>=k[u]&&t<=k[u+1]){p[r]=0;m[r]=0;break}}return new E({width:c,height:d,pixelType:g,pixels:[p],mask:m})};y.remapColor=function(a,
b){if(!F(a))return null;a=a.clone();var {pixels:c}=a;const d=a.width*a.height,f=b.length,e=Math.floor(f/2),g=b[Math.floor(e)];c=c[0];let k,h,p,q,m,l,n=!1;const r=new Uint8Array(d),t=new Uint8Array(d),u=new Uint8Array(d);let v=a.mask;const w=4===b[0].mappedColor.length;v||(v=new Uint8Array(d),v.fill(w?255:1),a.mask=v);for(m=0;m<d;m++)if(v[m]){k=c[m];n=!1;l=e;h=g;p=0;for(q=f-1;1<q-p;){if(k===h.value){n=!0;break}k>h.value?p=l:q=l;l=Math.floor((p+q)/2);h=b[Math.floor(l)]}n||(k===b[p].value?(h=b[p],n=
!0):k===b[q].value?(h=b[q],n=!0):k<b[p].value?(n=!1,h=null):k>b[p].value&&(k<b[q].value?(h=b[p],n=!0):q===f-1?(n=!1,h=null):(h=b[q],n=!0)));n?(r[m]=h.mappedColor[0],t[m]=h.mappedColor[1],u[m]=h.mappedColor[2],v[m]=h.mappedColor[3]):r[m]=t[m]=u[m]=v[m]=0}a.pixels=[r,t,u];a.mask=v;a.pixelType="u8";a.maskIsAlpha=w;return a};y.resampleByMajority=W;y.setValidBoundary=function(a,b,c){if(!F(a))return null;const {width:d,height:f}=a,e=b.x;b=b.y;const g=c.width+e;c=c.height+b;if(0>e||0>b||g>d||c>f||0===e&&
0===b&&g===d&&c===f)return a;a.mask||(a.mask=new Uint8Array(d*f));const k=a.mask;for(let h=0;h<f;h++){const p=h*d;for(let q=0;q<d;q++)k[p+q]=h<b||h>=c||q<e||q>=g?0:1}a.updateStatistics();return a};y.split=function(a,b,c){if(!F(a))return null;const {width:d,height:f}=b;let {width:e,height:g}=a;const k=new Map,h={x:0,y:0};c=null==c?1:1+c;for(let p=0;p<c;p++){const q=Math.ceil(e/d),m=Math.ceil(g/f);for(let l=0;l<m;l++){h.y=l*f;for(let n=0;n<q;n++){h.x=n*d;const r=Y(a,h,b);k.set(`${p}/${l}/${n}`,r)}}p<
c-1&&(a=ca(a));e=Math.round(e/2);g=Math.round(g/2)}return k};Object.defineProperties(y,{__esModule:{value:!0},[Symbol.toStringTag]:{value:"Module"}})});