// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.25/esri/copyright.txt for details.
//>>built
define(["exports","../../../core/maybe","../PixelBlock","./pixelUtils"],function(I,J,L,K){function N(t){let {altitude:m,azimuth:b}=t;const {hillshadeType:v,pixelSizePower:a=1,pixelSizeFactor:k=1,scalingType:c,isGCS:d,resolution:B}=t;var h="multi-directional"===v?2*t.zFactor:t.zFactor;const {x:e,y:A}=B;t=h/(8*e);var C=h/(8*A);d&&.001<h&&(t/=111E3,C/=111E3);"adjusted"===c&&(d?(t=111E3*e,C=111E3*A,t=(h+t**a*k)/(8*t),C=(h+C**a*k)/(8*C)):(t=(h+e**a*k)/(8*e),C=(h+A**a*k)/(8*A)));var l=(90-m)*Math.PI/180;
h=Math.cos(l);let u=(360-b+90)*Math.PI/180,p=Math.sin(l)*Math.cos(u);l=Math.sin(l)*Math.sin(u);const w=[315,270,225,360,180,0],D=[60,60,60,60,60,90];var q=new Float32Array([3,5,3,2,1,4]);const f=q.reduce((x,G)=>x+G);q=q.map(x=>x/f);const g="multi-directional"===v?w.length:1,y=new Float32Array(6),E=new Float32Array(6),z=new Float32Array(6);if("multi-directional"===v)for(let x=0;x<g;x++)m=D[x],b=w[x],l=(90-m)*Math.PI/180,h=Math.cos(l),u=(360-b+90)*Math.PI/180,p=Math.sin(l)*Math.cos(u),l=Math.sin(l)*
Math.sin(u),y[x]=h,E[x]=p,z[x]=l;else y.fill(h),E.fill(p),z.fill(l);return{resolution:B,factor:[t,C],sinZcosA:p,sinZsinA:l,cosZ:h,sinZcosAs:E,sinZsinAs:z,cosZs:y,weights:q,hillshadeType:["traditional","multi-directional"].indexOf(v)}}I.aspect=function(t,m={}){if(!K.isValidPixelBlock(t))return t;const {width:b,height:v,mask:a}=t;var k=t.pixels[0];const c=new Uint8Array(b*v);J.isSome(a)&&c.set(a);const d=new Float32Array(b*v);var {resolution:B}=m;m=B?1/B.x:1;B=B?1/B.y:1;let h;let e,A,C,l;const u=J.isSome(a);
for(let q=1;q<v-1;q++){const f=q*b;for(let g=1;g<b-1;g++)if(a&&!a[f+g])d[f+g]=0;else{var p=0;if(u&&(p=a[f-b+g-1]+a[f-b+g]+a[f-b+g+1]+a[f+g-1]+a[f+g+1]+a[f+b+g-1]+a[f+b+g]+a[f+b+g+1],7>p)){d[f+g]=0;c[f+g]=0;continue}if(a&&7===p){p=a[f-b+g-1]?k[f-b+g-1]:k[f+g];var w=a[f-b+g]?k[f-b+g]:k[f+g];h=a[f-b+g+1]?k[f-b+g+1]:k[f+g];var D=a[f+g-1]?k[f+g-1]:k[f+g];e=a[f+g+1]?k[f+g+1]:k[f+g];A=a[f+b+g-1]?k[f+b+g-1]:k[f+g];C=a[f+b+g]?k[f+b+g]:k[f+g];l=a[f+b+g+1]?k[f+b+g+1]:k[f+g]}else p=k[f-b+g-1],w=k[f-b+g],h=k[f-
b+g+1],D=k[f+g-1],e=k[f+g+1],A=k[f+b+g-1],C=k[f+b+g],l=k[f+b+g+1];D=(h+e+e+l-(p+D+D+A))*m;p=(A+C+C+l-(p+w+w+h))*B;w=-1;if(0!==D||0!==p)w=90-57.29578*Math.atan2(p,-D),0>w&&(w+=360),360===w?w=0:360<w&&(w%=360);d[f+g]=w}}for(k=0;k<v;k++)d[k*b]=d[k*b+1],d[(k+1)*b-1]=d[(k+1)*b-2];for(k=1;k<b-1;k++)d[k]=d[k+b],d[k+(v-1)*b]=d[k+(v-2)*b];return new L({width:b,height:v,pixels:[d],mask:a?c:null,pixelType:"f32",validPixelCount:t.validPixelCount,statistics:[{minValue:0,maxValue:360}]})};I.calculateHillshadeParams=
N;I.hillshade=function(t,m){if(!K.isValidPixelBlock(t))return t;const {width:b,height:v,mask:a}=t,k=new Uint8Array(b*v);var c=1;if(J.isSome(a)){for(var d=0;d<a.length;d++)if(a[d]){c=a[d];break}k.set(a)}const {factor:B,sinZcosA:h,sinZsinA:e,cosZ:A,sinZcosAs:C,sinZsinAs:l,cosZs:u,weights:p}=N(m),[w,D]=B;({hillshadeType:d}=m);const q=t.pixels[0];m=new Uint8Array(b*v);let f;const g=J.isSome(a);for(let M=1;M<v-1;M++){const r=M*b;for(let n=1;n<b-1;n++)if(a&&!a[r+n])m[r+n]=0;else{var y=8;if(g&&(y=(a[r-b+
n-1]+a[r-b+n]+a[r-b+n+1]+a[r+n-1]+a[r+n+1]+a[r+b+n-1]+a[r+b+n]+a[r+b+n+1])/c,7>y)){m[r+n]=0;k[r+n]=0;continue}if(a&&7===y){var E=a[r-b+n-1]?q[r-b+n-1]:q[r+n];var z=a[r-b+n]?q[r-b+n]:q[r+n];var x=a[r-b+n+1]?q[r-b+n+1]:q[r+n];y=a[r+n-1]?q[r+n-1]:q[r+n];f=a[r+n+1]?q[r+n+1]:q[r+n];var G=a[r+b+n-1]?q[r+b+n-1]:q[r+n];var F=a[r+b+n]?q[r+b+n]:q[r+n];var H=a[r+b+n+1]?q[r+b+n+1]:q[r+n]}else E=q[r-b+n-1],z=q[r-b+n],x=q[r-b+n+1],y=q[r+n-1],f=q[r+n+1],G=q[r+b+n-1],F=q[r+b+n],H=q[r+b+n+1];y=(x+f+f+H-(E+y+y+G))*
w;E=(G+F+F+H-(E+z+z+x))*D;z=Math.sqrt(1+y*y+E*E);x=0;if("traditional"===d)y=255*(A+e*E-h*y)/z,0>y&&(y=0),x=y;else for(G=l.length,F=0;F<G;F++)H=255*(u[F]+l[F]*E-C[F]*y)/z,0>H&&(H=0),x+=H*p[F];m[r+n]=x&255}}for(c=0;c<v;c++)m[c*b]=m[c*b+1],m[(c+1)*b-1]=m[(c+1)*b-2];for(c=1;c<b-1;c++)m[c]=m[c+b],m[c+(v-1)*b]=m[c+(v-2)*b];return new L({width:b,height:v,pixels:[m],mask:a?k:null,pixelType:"u8",validPixelCount:t.validPixelCount,statistics:[{minValue:0,maxValue:255}]})};I.slope=function(t,m){if(!K.isValidPixelBlock(t))return t;
var b=m.zFactor,v=m.pixelSizePower??1,a=m.pixelSizeFactor??1;const k=m.slopeType;var c=m.isGCS;const {width:d,height:B,mask:h}=t;var e=t.pixels[0];const A=new Uint8Array(d*B);let C=1;if(J.isSome(h)){for(var l=0;l<h.length;l++)if(h[l]){C=h[l];break}A.set(h)}l=new Float32Array(d*B);const {x:u,y:p}=m.resolution;m=b/(8*u);var w=b/(8*p);c&&1E-4>Math.abs(b-1)&&(m/=111E3,w/=111E3);"adjusted"===k&&(c?(m=111E3*u,w=111E3*p,m=(b+m**v*a)/(8*m),w=(b+w**v*a)/(8*w)):(m=(b+u**v*a)/(8*u),w=(b+p**v*a)/(8*p)));let D,
q;let f,g,y,E;b=J.isSome(h);for(v=1;v<B-1;v++)for(a=v*d,c=1;c<d-1;c++)if(h&&!h[a+c])l[a+c]=0;else{var z=0;if(b&&(z=(h[a-d+c-1]+h[a-d+c]+h[a-d+c+1]+h[a+c-1]+h[a+c+1]+h[a+d+c-1]+h[a+d+c]+h[a+d+c+1])/C,7>z)){l[a+c]=0;A[a+c]=0;continue}if(h&&7===z){z=h[a-d+c-1]?e[a-d+c-1]:e[a+c];D=h[a-d+c]?e[a-d+c]:e[a+c];q=h[a-d+c+1]?e[a-d+c+1]:e[a+c];var x=h[a+c-1]?e[a+c-1]:e[a+c];f=h[a+c+1]?e[a+c+1]:e[a+c];g=h[a+d+c-1]?e[a+d+c-1]:e[a+c];y=h[a+d+c]?e[a+d+c]:e[a+c];E=h[a+d+c+1]?e[a+d+c+1]:e[a+c]}else z=e[a-d+c-1],D=
e[a-d+c],q=e[a-d+c+1],x=e[a+c-1],f=e[a+c+1],g=e[a+d+c-1],y=e[a+d+c],E=e[a+d+c+1];x=(q+f+f+E-(z+x+x+g))*m;z=(g+y+y+E-(z+D+D+q))*w;z=Math.sqrt(x*x+z*z);l[a+c]="percent-rise"===k?100*z:57.2957795*Math.atan(z)}for(e=0;e<B;e++)l[e*d]=l[e*d+1],l[(e+1)*d-1]=l[(e+1)*d-2];for(e=1;e<d-1;e++)l[e]=l[e+d],l[e+(B-1)*d]=l[e+(B-2)*d];return new L({width:d,height:B,pixels:[l],mask:h?A:null,pixelType:"f32",validPixelCount:t.validPixelCount,statistics:[{minValue:0,maxValue:"percent-rise"===k?100:360}]})};I.tintHillshade=
function(t,m,b,v){if(K.isValidPixelBlock(t)&&K.isValidPixelBlock(m)){var {min:a,max:k}=v;v=t.pixels[0];var {pixels:c,mask:d}=m;m=c[0];var B=255.00001/(k-a),h=new Uint8ClampedArray(m.length),e=new Uint8ClampedArray(m.length),A=new Uint8ClampedArray(m.length),C=b.length-1;for(let p=0;p<m.length;p++){if(d&&0===d[p])continue;var l=Math.floor((m[p]-a)*B);const [w,D]=b[0>l?0:l>C?C:l];var u=v[p];l=u*D;const q=l*(1-Math.abs(w%2-1));u-=l;switch(Math.floor(w)){case 0:h[p]=l+u;e[p]=q+u;A[p]=u;break;case 1:h[p]=
q+u;e[p]=l+u;A[p]=u;break;case 2:h[p]=u;e[p]=l+u;A[p]=q+u;break;case 3:h[p]=u;e[p]=q+u;A[p]=l+u;break;case 4:h[p]=q+u;e[p]=u;A[p]=l+u;break;case 5:case 6:h[p]=l+u,e[p]=u,A[p]=q+u}}t.pixels=[h,e,A];t.updateStatistics()}};Object.defineProperties(I,{__esModule:{value:!0},[Symbol.toStringTag]:{value:"Module"}})});