// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.25/esri/copyright.txt for details.
//>>built
define("../../../chunks/_rollupPluginBabelHelpers ../../../chunks/tslib.es6 ../../../core/maybe ../../../core/accessorSupport/decorators/property ../../../core/arrayUtils ../../../core/accessorSupport/ensureType ../../../core/accessorSupport/decorators/subclass ./Column ../../support/uriUtils".split(" "),function(q,k,p,l,e,z,x,y,u){e=function(w){function v(f){var a=w.call(this,f)||this;a.activeEditInfo=null;a.cellValueValidatorFunction=({oldValue:c,value:b})=>c!==b;a.editable=!1;a.inputRenderFunction=
({root:c,column:b,rowData:d})=>{if(!a.activeEditInfo?.updating&&a.editable){var g=a.getCellValue(b,d),h=a.createInputElement({root:c,column:b,rowData:d,value:g});a._set("activeEditInfo",{column:b,input:h,root:c,rowData:d,updating:!0,oldValue:g});b=a.createInputContainer();b.appendChild(h);a.removeCellContent(c);c.appendChild(b);h.focus();h instanceof HTMLInputElement&&h.select();a.grid?.notifyResize()}};a.loadingMessage="";a.inputType="text";a.maxLength=null;a.parseInputValueFunction=({input:c})=>
c.value;a.renderFunction=c=>{const {root:b,column:d,rowData:g}=c;var {activeEditInfo:h}=q._assertThisInitialized(a);if(!h||!h.updating){var m=a.getCellValue(d,g);h=a.cellValueFormatFunction({column:d,rowData:g,value:m});b.onclick=()=>b.focus();b.ondblclick=()=>a.inputRenderFunction(c);b.ontouchend=()=>a.inputRenderFunction(c);var n=a.grid?.getSlotElementByName(b.slot)?.parentElement;n&&!n.onkeydown&&(n.onkeydown=r=>{"Enter"!==r.key||a.activeEditInfo||a.inputRenderFunction(c);"Escape"===r.key&&a.activeEditInfo&&
a.cancel()});p.isSome(m)&&p.isSome(h)?b.title=h.toString():b.title&&b.removeAttribute("title");m=u.autoLink(a.messagesURIUtils,h);h?.toString()!==b.innerHTML&&m!==b.innerHTML&&(b.innerHTML=m)}};a.required=!1;a.store=null;a.updateRowItemFunction=({rowData:c,column:b,value:d})=>{p.assertIsSome(c);c.item[b.path]=d};a.updateStoreItemFunction=function(){var c=q._asyncToGenerator(function*({rowData:b,column:d,value:g}){p.assertIsSome(b);yield a.store?.updateItem({index:b.index,name:d.path,value:g})});return function(b){return c.apply(this,
arguments)}}();return a}q._inheritsLoose(v,w);var t=v.prototype;t.cancel=function(){var {activeEditInfo:f}=this;if(f){var {column:a,root:c,rowData:b,oldValue:d}=f;this._set("activeEditInfo",null);f=this.cellValueFormatFunction({column:a,rowData:b,value:d});f=u.autoLink(this.messagesURIUtils,f);c.innerHTML=f;this.grid?.notifyResize()}};t.createInputContainer=function(){const f=document.createElement("div");f.classList.add("esri-editor-column__cell-input--container");return f};t.createInputElement=
function({value:f}){const a=document.createElement("input");a.classList.add("esri-editor-column__cell-input");null!=this.maxLength&&(a.maxLength=this.maxLength);a.type=this.inputType;a.value=f;a.onblur=()=>{a.onblur=null;this.submit()};return a};t.submit=function(){var f=q._asyncToGenerator(function*(){var {activeEditInfo:a}=this;if(a){var {column:c,input:b,root:d,rowData:g,oldValue:h}=a;a=this.parseInputValueFunction({input:b,column:c,rowData:g});if(this.cellValueValidatorFunction({value:a,oldValue:h,
column:c,rowData:g})){d.innerHTML=this.loadingMessage;this.grid?.notifyResize();try{yield this.updateStoreItemFunction({rowData:g,column:c,value:a});this.updateRowItemFunction({rowData:g,column:c,value:a});const m=this.getCellValue(c,g),n=this.cellValueFormatFunction({column:c,rowData:g,value:m});p.isSome(m)&&p.isSome(n)?d.title=n.toString():d.title&&d.removeAttribute("title");const r=u.autoLink(this.messagesURIUtils,n);d.innerHTML=r;this.emit("value-change",{column:c,rowData:g,value:m});this._set("activeEditInfo",
null);this.grid?.notifyResize()}catch(m){this.cancel()}}else this.cancel()}});return function(){return f.apply(this,arguments)}}();return v}(y);k.__decorate([l.property({readOnly:!0})],e.prototype,"activeEditInfo",void 0);k.__decorate([l.property()],e.prototype,"cellValueValidatorFunction",void 0);k.__decorate([l.property()],e.prototype,"editable",void 0);k.__decorate([l.property()],e.prototype,"inputRenderFunction",void 0);k.__decorate([l.property({constructOnly:!0})],e.prototype,"loadingMessage",
void 0);k.__decorate([l.property()],e.prototype,"inputType",void 0);k.__decorate([l.property()],e.prototype,"maxLength",void 0);k.__decorate([l.property()],e.prototype,"parseInputValueFunction",void 0);k.__decorate([l.property()],e.prototype,"renderFunction",void 0);k.__decorate([l.property()],e.prototype,"required",void 0);k.__decorate([l.property()],e.prototype,"store",void 0);k.__decorate([l.property()],e.prototype,"updateRowItemFunction",void 0);k.__decorate([l.property()],e.prototype,"updateStoreItemFunction",
void 0);return e=k.__decorate([x.subclass("esri.widgets.FeatureTable.Grid.EditorColumn")],e)});