// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.25/esri/copyright.txt for details.
//>>built
define("exports ../../../chunks/_rollupPluginBabelHelpers ../../../chunks/tslib.es6 ../../../core/Accessor ../../../core/Evented ../../../core/maybe ../../../core/promiseUtils ../../../core/accessorSupport/decorators/property ../../../core/arrayUtils ../../../core/accessorSupport/ensureType ../../../core/accessorSupport/decorators/subclass ../../../geometry/support/spatialReferenceUtils ../layers/graphics/ElevationQuery".split(" "),function(l,t,r,w,x,n,u,v,C,D,y,z,A){function p(k,f,h,a,b,d,g){for(const e of f)f=
e.getElevation(h,a,b,d,g),n.isSome(f)&&(k=n.isSome(k)?Math.max(f,k):f);return k}l.CombinedElevationProvider=function(k){function f(a){a=k.call(this,a)||this;a._im=[];a._ground=[];a._scene=[];a._handles=new Map;a.lastElevationQuery=null;a.elevationCacheEnabled=!1;return a}t._inheritsLoose(f,k);var h=f.prototype;h.destroy=function(){this._elevationQueryCached=n.destroyMaybe(this._elevationQueryCached)};h.enableElevationCache=function(a){a||(this.lastElevationQuery=null);this.elevationCacheEnabled=a};
h.getElevation=function(a,b,d,g,e){if(this.elevationCacheEnabled&&null!=this.lastElevationQuery){var c=this.lastElevationQuery;if(a===c.x&&b===c.y&&d===c.z&&z.equals(g,c.spatialReference)&&e===c.queryContext)return c.result}c=p(null,this._im,a,b,d,g,e);n.isNone(c)&&(c=p(c,this._ground,a,b,d,g,e));"scene"===e&&(c=p(c,this._scene,a,b,d,g,e));this.elevationCacheEnabled&&(this.lastElevationQuery={x:a,y:b,z:d,spatialReference:g,queryContext:e,result:c});return c};h.queryElevation=function(a,b,d,g,e,c=
null,B=0){const q=u.createResolver();this._elevationQuery.queryElevation(a,b,c,B).then(m=>{"scene"===e&&(m=p(m,this._scene,a,b,d,g,e));q.resolve(m)}).catch(m=>{u.isAbortError(m)?q.reject(m):q.resolve(this.getElevation(a,b,d,g,e))});return q.promise};h.register=function(a,b){this._handles.set(b,b.on("elevation-change",d=>this.emit("elevation-change",d)));this._providersFromContext(a).push(b)};h.unregister=function(a){this._handles.has(a)&&(this._handles.get(a).remove(),this._handles.delete(a));for(const b of[this._im,
this._ground,this._scene]){const d=b.indexOf(a);-1<d&&b.splice(d,1)}};h._providersFromContext=function(a){switch(a){case "ground":return this._ground;case "im":return this._im;case "scene":return this._scene}};t._createClass(f,[{key:"spatialReference",get:function(){return this.view?.basemapTerrain?.spatialReference}},{key:"_elevationQuery",get:function(){n.isNone(this._elevationQueryCached)&&(this._elevationQueryCached=new A.ElevationQuery(this.view.resourceController.scheduler,this.view.spatialReference,
()=>this.view.map&&this.view.map.ground,{maximumAutoTileRequests:4}));return this._elevationQueryCached}}]);return f}(x.EventedMixin(w));r.__decorate([v.property({constructOnly:!0})],l.CombinedElevationProvider.prototype,"view",void 0);r.__decorate([v.property()],l.CombinedElevationProvider.prototype,"spatialReference",null);l.CombinedElevationProvider=r.__decorate([y.subclass("esri.views.3d.support.CombinedElevationProvider")],l.CombinedElevationProvider);Object.defineProperties(l,{__esModule:{value:!0},
[Symbol.toStringTag]:{value:"Module"}})});