// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.25/esri/copyright.txt for details.
//>>built
define("exports ../../../chunks/_rollupPluginBabelHelpers ../../../core/maybe ../../../chunks/vec3 ../../../geometry/support/clipRay ../../../geometry/support/frustum ../../../geometry/support/lineSegment ../../../geometry/support/ray ../../ViewingMode ./LaserlinePathData ../webgl-engine/lib/glUtil3D ../webgl-engine/lib/RenderSlot ../webgl-engine/materials/internal/MaterialUtil ../webgl-engine/shaders/LaserlinePathTechnique ../webgl-engine/shaders/LaserlinePathTechniqueConfiguration ../webgl-engine/shaders/LaserlineTechnique ../webgl-engine/shaders/LaserlineTechniqueConfiguration ../../webgl/enums".split(" "),
function(l,u,b,d,g,v,m,w,n,p,x,q,r,y,z,t,A,B){let C=function(){function h(a,e={contrastControlEnabled:!1}){this._config=e;this._technique=null;this._intersectsLineInfinite=this._intersectsLineEnabled=this._lineVerticalPlaneEnabled=this._pointDistanceEnabled=this._heightManifoldEnabled=!1;this._viewingMode=n.ViewingMode.Local;this._pathVerticalPlaneEnabled=!1;this._pathTechnique=this._pathVerticalPlaneData=null;this.canRender=!0;this._passParameters=r.copyParameters(a,new t.LaserlinePassParameters)}
var c=h.prototype;c.setParameters=function(a){r.updateParameters(this._passParameters,a)&&this._requestRender()};c.initializeRenderContext=function(a){this._context=a;this._quadVAO=x.createQuadVAO(a.renderContext.rctx);this._techniqueRepository=a.shaderTechniqueRepository;this._techniqueConfig=new A.LaserlineTechniqueConfiguration;a=new z.LaserlinePathTechniqueConfiguration;a.contrastControlEnabled=this._config.contrastControlEnabled;this._pathTechnique=this._techniqueRepository.acquire(y.LaserlinePathTechnique,
a)};c.uninitializeRenderContext=function(){this._quadVAO=b.disposeMaybe(this._quadVAO);this._technique=b.releaseMaybe(this._technique);this._pathVerticalPlaneData=b.disposeMaybe(this._pathVerticalPlaneData);this._pathTechnique=b.releaseMaybe(this._pathTechnique)};c.prepareTechnique=function(){return this.heightManifoldEnabled||this.pointDistanceEnabled||this.lineVerticalPlaneSegment||this.intersectsLineEnabled?(this._techniqueConfig.heightManifoldEnabled=this.heightManifoldEnabled,this._techniqueConfig.lineVerticalPlaneEnabled=
this.lineVerticalPlaneEnabled,this._techniqueConfig.pointDistanceEnabled=this.pointDistanceEnabled,this._techniqueConfig.intersectsLineEnabled=this.intersectsLineEnabled,this._techniqueConfig.contrastControlEnabled=this._config.contrastControlEnabled,this._techniqueConfig.spherical=this._viewingMode===n.ViewingMode.Global,this._technique=this._techniqueRepository.releaseAndAcquire(t.LaserlineTechnique,this._techniqueConfig,this._technique)):this._pathTechnique};c.render=function(a,e){(this.heightManifoldEnabled||
this.pointDistanceEnabled||this.lineVerticalPlaneSegment||this.intersectsLineEnabled)&&this._renderUnified(a,e);this.pathVerticalPlaneEnabled&&this._renderPath(a)};c._renderUnified=function(a,e){const k=a.rctx;this._updatePassParameters(a);k.bindTechnique(e,this._passParameters,a.bindParameters);k.bindVAO(this._quadVAO);k.drawArrays(B.PrimitiveType.TRIANGLE_STRIP,0,4)};c._renderPath=function(a){b.isNone(this._pathVerticalPlaneData)||b.isNone(this._pathTechnique)||(a.rctx.bindTechnique(this._pathTechnique,
{...this._passParameters,origin:this._pathVerticalPlaneData.origin},a.bindParameters),this._pathVerticalPlaneData.draw(a.rctx))};c._updatePassParameters=function(a){this._intersectsLineEnabled&&(a=a.bindParameters.camera,this._intersectsLineInfinite?(g.fromRay(w.wrap(this._passParameters.intersectsLineSegment.origin,this._passParameters.intersectsLineSegment.vector),f),f.c0=-Number.MAX_VALUE,v.intersectClipRay(a.frustum,f)&&(g.getStart(f,this._passParameters.lineStartWorld),g.getEnd(f,this._passParameters.lineEndWorld))):
(d.copy(this._passParameters.lineStartWorld,this._passParameters.intersectsLineSegment.origin),d.add(this._passParameters.lineEndWorld,this._passParameters.intersectsLineSegment.origin,this._passParameters.intersectsLineSegment.vector)))};c._requestRender=function(){this._context&&this._context.requestRender()};u._createClass(h,[{key:"renderSlots",get:function(){return[this._config.contrastControlEnabled?q.RenderSlot.LASERLINES_CONTRAST_CONTROL:q.RenderSlot.LASERLINES]}},{key:"needsLinearDepth",get:function(){return!0}},
{key:"heightManifoldEnabled",get:function(){return this._heightManifoldEnabled},set:function(a){this._heightManifoldEnabled!==a&&(this._heightManifoldEnabled=a,this._requestRender())}},{key:"heightManifoldTarget",get:function(){return this._passParameters.heightManifoldTarget},set:function(a){d.copy(this._passParameters.heightManifoldTarget,a);this._requestRender()}},{key:"pointDistanceEnabled",get:function(){return this._pointDistanceEnabled},set:function(a){a!==this._pointDistanceEnabled&&(this._pointDistanceEnabled=
a,this._requestRender())}},{key:"pointDistanceTarget",get:function(){return this._passParameters.pointDistanceTarget},set:function(a){d.copy(this._passParameters.pointDistanceTarget,a);this._requestRender()}},{key:"pointDistanceOrigin",get:function(){return this._passParameters.pointDistanceOrigin},set:function(a){d.copy(this._passParameters.pointDistanceOrigin,a);this._requestRender()}},{key:"lineVerticalPlaneEnabled",get:function(){return this._lineVerticalPlaneEnabled},set:function(a){a!==this._lineVerticalPlaneEnabled&&
(this._lineVerticalPlaneEnabled=a,this._requestRender())}},{key:"lineVerticalPlaneSegment",get:function(){return this._passParameters.lineVerticalPlaneSegment},set:function(a){m.copy(a,this._passParameters.lineVerticalPlaneSegment);this._requestRender()}},{key:"intersectsLineEnabled",get:function(){return this._intersectsLineEnabled},set:function(a){a!==this._intersectsLineEnabled&&(this._intersectsLineEnabled=a,this._requestRender())}},{key:"intersectsLineSegment",get:function(){return this._passParameters.intersectsLineSegment},
set:function(a){m.copy(a,this._passParameters.intersectsLineSegment);this._requestRender()}},{key:"intersectsLineRadius",get:function(){return this._passParameters.intersectsLineRadius},set:function(a){a!==this._passParameters.intersectsLineRadius&&(this._passParameters.intersectsLineRadius=a,this._requestRender())}},{key:"intersectsLineInfinite",get:function(){return this._intersectsLineInfinite},set:function(a){a!==this._intersectsLineInfinite&&(this._intersectsLineInfinite=a,this._requestRender())}},
{key:"viewingMode",get:function(){return this._viewingMode},set:function(a){a!==this._viewingMode&&(this._viewingMode=a,this._requestRender())}},{key:"pathVerticalPlaneEnabled",get:function(){return this._pathVerticalPlaneEnabled},set:function(a){a!==this._pathVerticalPlaneEnabled&&(this._pathVerticalPlaneEnabled=a,b.isSome(this._pathVerticalPlaneData)&&this._requestRender())}},{key:"pathVerticalPlaneVertices",set:function(a){b.isNone(this._pathVerticalPlaneData)&&(this._pathVerticalPlaneData=new p.LaserlinePathData(this._passParameters.renderCoordsHelper));
this._pathVerticalPlaneData.vertices=a;this.pathVerticalPlaneEnabled&&this._requestRender()}},{key:"pathVerticalPlaneBuffers",set:function(a){b.isNone(this._pathVerticalPlaneData)&&(this._pathVerticalPlaneData=new p.LaserlinePathData(this._passParameters.renderCoordsHelper));this._pathVerticalPlaneData.buffers=a;this.pathVerticalPlaneEnabled&&this._requestRender()}}]);return h}();const f=g.create();l.LaserLineRenderer=C;Object.defineProperties(l,{__esModule:{value:!0},[Symbol.toStringTag]:{value:"Module"}})});