// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.25/esri/copyright.txt for details.
//>>built
define("../../../../chunks/_rollupPluginBabelHelpers ../../../../chunks/tslib.es6 ../../../../core/events ../../../../core/HandleOwner ../../../../core/maybe ../../../../core/reactiveUtils ../../../../core/accessorSupport/decorators/property ../../../../core/arrayUtils ../../../../core/accessorSupport/ensureType ../../../../core/accessorSupport/decorators/subclass ../../../Widget ./ButtonMenuViewModel ../../../support/Popover ../../../support/widgetUtils ../../../support/jsxFactory".split(" "),function(p,
h,t,f,u,v,k,C,D,w,x,y,z,q,e){f=function(r){function m(a,b){a=r.call(this,a,b)||this;a._menuContentNode=null;a._popover=null;a._rootNode=null;a.disabled=!1;a.iconClass="";a.viewModel=new y;a._handleOutsideClick=a._handleOutsideClick.bind(p._assertThisInitialized(a));return a}p._inheritsLoose(m,r);var c=m.prototype;c.postInitialize=function(){this._popover=new z({owner:this,open:!!this.open,placement:q.isRTL(this.container)?"bottom-start":"bottom-end",renderContentFunction:this.renderMenuContent,anchorElement:this._rootNode});
this.handles.add(v.watch(()=>this.open,a=>this._popover?.set("open",a)));document.addEventListener("click",this._handleOutsideClick)};c.destroy=function(){this._popover?.destroy();this._popover=null;document.removeEventListener("click",this._handleOutsideClick)};c._handleOutsideClick=function(a){this.open&&this._rootNode&&this._menuContentNode&&(a=a.target,this._menuContentNode?.contains(a)||this._rootNode?.contains(a)||(this.open=!1))};c.render=function(){return e.tsx("div",{afterCreate:this._afterRootNodeCreate,
bind:this,"data-node-ref":"_rootNode",class:this.classes("esri-button-menu","esri-widget"),key:"menu"},this.renderMenuButton())};c.renderMenuButton=function(){const {iconClass:a,id:b,label:g,open:d}=this,n=this.classes("esri-button-menu__button",a??"esri-icon-menu",d?"esri-button-menu__button--selected":null);return e.tsx("button",{"aria-pressed":d.toString(),"aria-controls":`${b}-menu`,"aria-expanded":d.toString(),"aria-haspopup":"true","aria-label":g,bind:this,class:n,disabled:this.disabled,id:`${b}-button`,
title:g??"",selected:d,onclick:this._toggleOpen,tabindex:this.disabled?-1:0,type:"button"})};c.renderMenuContent=function(){const {id:a,open:b}=this;return e.tsx("div",{afterCreate:this._afterMenuContentNodeCreate,bind:this,class:"esri-button-menu__content","data-node-ref":"_menuContentNode",key:"esri-button-menu-content",hidden:!b},e.tsx("ul",{"aria-labelledby":`${a}-button`,bind:this,class:"esri-button-menu__item-wrapper",id:`${a}-menu`,role:"menu"},this.items?.length&&this.renderItems()))};c.renderItems=
function(){return this.items?.map((a,b)=>this.renderItem(a,b))};c.renderItem=function(a,b,g){const d=u.isSome(g)?`${this.id}-menu-item-${b}-${g}`:`${this.id}-menu-item-${b}`,n=`${d}-label`,A=this.classes("esri-button-menu__item",a.selectionEnabled?"esri-button-menu__item--selectable":null,a.selectionEnabled&&a.selected?"esri-button-menu__item--selected":null);return e.tsx("li",{afterCreate:this._afterMenuItemCreate,bind:this,class:A,"data-item-index":b,"data-item-subIndex":g,for:d,key:d,onkeydown:l=>
this._handleMenuItemKeydown(l,a),onclick:l=>this._handleMenuItemInteraction(l,a),role:"menuitem",tabindex:this.disabled?-1:0},e.tsx("input",{disabled:!0,checked:a.selected,class:"esri-button-menu__checkbox",id:d,name:d,tabindex:"-1",type:"checkbox"}),e.tsx("label",{bind:this,class:this.classes("esri-button-menu__button","esri-button-menu__item-label"),for:d,id:n},e.tsx("span",{class:this.classes("esri-button-menu__icon",a.iconClass),"aria-hidden":"true"}),e.tsx("span",{class:"esri-button-menu__item-label-content"},
a.label)),e.tsx("ul",{"aria-labelledby":n,class:"esri-button-menu__embedded-content-wrapper",id:`${this.id}-submenu`,role:"menu"},a?.items?.map((l,B)=>this.renderItem(l,b,B))))};c._afterRootNodeCreate=function(a){this._rootNode=a;this._popover?.set("anchorElement",()=>a)};c._handleMenuItemInteraction=function(a,b){b.selected=!b.selected;b.open=!(!b.selected||!b.items);b.autoCloseMenu&&this.set("open",!1);b.clickFunction&&b.clickFunction({event:a,item:b});a.stopPropagation()};c._handleMenuItemKeydown=
function(a,b){const g=t.eventKey(a);q.isActivationKey(g)&&this._handleMenuItemInteraction(a,b);"Escape"===g&&(this.open=!1,a.preventDefault(),a.stopPropagation())};c._afterMenuContentNodeCreate=function(a){this._menuContentNode=a;a.focus()};c._toggleOpen=function(){this.open=!this.open};c._afterMenuItemCreate=function(a){0===a["data-item-index"]&&a.focus()};p._createClass(m,[{key:"items",get:function(){return this.viewModel.items},set:function(a){this.viewModel.items=a}},{key:"open",get:function(){return this.viewModel.open},
set:function(a){this.viewModel.open=a}}]);return m}(f.HandleOwnerMixin(x));h.__decorate([k.property()],f.prototype,"disabled",void 0);h.__decorate([k.property()],f.prototype,"iconClass",void 0);h.__decorate([k.property()],f.prototype,"items",null);h.__decorate([k.property()],f.prototype,"open",null);h.__decorate([k.property()],f.prototype,"viewModel",void 0);return f=h.__decorate([w.subclass("esri.widgets.FeatureTable.Grid.support.ButtonMenu")],f)});