// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.25/esri/copyright.txt for details.
//>>built
define("../chunks/_rollupPluginBabelHelpers ../chunks/tslib.es6 ../core/promiseUtils ../core/unitUtils ../core/accessorSupport/decorators/property ../core/arrayUtils ../core/accessorSupport/ensureType ../core/accessorSupport/decorators/subclass ./Widget ./DirectLineMeasurement3D/DirectLineMeasurement3DViewModel ./support/decorators/accessibleHandler ./support/decorators/messageBundle ./support/jsxFactory ./support/widgetUtils".split(" "),function(w,d,E,F,e,c,K,G,H,x,y,z,b,L){c=function(A){function l(a,
m){a=A.call(this,a,m)||this;a.iconClass="esri-icon-measure-line";a.viewModel=new x;return a}w._inheritsLoose(l,A);var r=l.prototype;r.render=function(){const {supported:a,active:m,state:n,measurement:t,unit:I}=this.viewModel;var p="disabled"===n;const u="measuring"===n||"measured"===n,{messages:f,messagesUnits:B}=this;var v=m&&"ready"===n?b.tsx("section",{key:"esri-direct-line-measurement-3d__hint",class:"esri-direct-line-measurement-3d__hint"},b.tsx("p",{class:"esri-direct-line-measurement-3d__hint-text"},
f.hint)):null;const J=a?null:b.tsx("section",{key:"esri-direct-line-measurement-3d__unsupported",class:"esri-direct-line-measurement-3d__panel--error"},b.tsx("p",null,f.unsupported));var h=(g,C,D)=>{switch(C.state){case "available":return b.tsx("div",{key:`${D}-enabled`,class:"esri-direct-line-measurement-3d__measurement-item"},b.tsx("span",{class:"esri-direct-line-measurement-3d__measurement-item-title"},g),b.tsx("span",{"aria-live":"polite",class:"esri-direct-line-measurement-3d__measurement-item-value"},
C.text));case "unavailable":return b.tsx("div",{key:`${D}-disabled`,class:this.classes("esri-direct-line-measurement-3d__measurement-item","esri-direct-line-measurement-3d__measurement-item--disabled")},b.tsx("span",{class:"esri-direct-line-measurement-3d__measurement-item-title"},g))}};h=u?b.tsx("section",{key:"esri-direct-line-measurement-3d__measurement",class:"esri-direct-line-measurement-3d__measurement"},h(f.direct,t.directDistance,"direct"),h(f.horizontal,t.horizontalDistance,"horizontal"),
h(f.vertical,t.verticalDistance,"vertical")):null;var q=`${this.id}__units`,k=b.tsx("label",{class:"esri-direct-line-measurement-3d__units-label",for:q},f.unit);q=b.tsx("div",{class:"esri-direct-line-measurement-3d__units-select-wrapper"},b.tsx("select",{class:"esri-direct-line-measurement-3d__units-select esri-select",id:q,onchange:this._changeUnit,bind:this,value:I},this.viewModel.unitOptions.map(g=>b.tsx("option",{key:g,value:g},F.isMeasurementSystem(g)?B.systems[g]:B.units[g]?.pluralCapitalized))));
k=b.tsx("section",{key:"esri-direct-line-measurement-3d__units",class:"esri-direct-line-measurement-3d__units"},k,q);k=u?b.tsx("div",{key:"settings",class:"esri-direct-line-measurement-3d__settings"},k):null;p=!a||m&&!u?null:b.tsx("div",{class:"esri-direct-line-measurement-3d__actions"},b.tsx("button",{disabled:p,class:this.classes("esri-direct-line-measurement-3d__clear-button esri-button esri-button--primary",p&&"esri-button--disabled"),bind:this,onclick:this._newMeasurement,type:"button"},f.newMeasurement));
v=this.visible?b.tsx("div",{class:"esri-direct-line-measurement-3d__container"},J,v,k,h,p):null;return b.tsx("div",{"aria-label":f.widgetLabel,key:this,class:"esri-direct-line-measurement-3d esri-widget esri-widget--panel",role:"presentation"},v)};r._newMeasurement=function(){E.ignoreAbortErrors(this.viewModel.start())};r._changeUnit=function(a){a=a.target;if(a=a.options[a.selectedIndex])this.unit=a.value};w._createClass(l,[{key:"view",get:function(){return this.viewModel.view},set:function(a){this.viewModel.view=
a}},{key:"visible",get:function(){return this.viewModel.visible},set:function(a){this.viewModel.visible=a}},{key:"active",get:function(){return this.viewModel.active}},{key:"analysis",get:function(){return this.viewModel.analysis},set:function(a){this.viewModel.analysis=a}},{key:"label",get:function(){return this.messages?.widgetLabel??""},set:function(a){this._overrideIfSome("label",a)}},{key:"unitOptions",get:function(){return this.viewModel.unitOptions},set:function(a){this.viewModel.unitOptions=
a}},{key:"unit",get:function(){return this.viewModel.unit},set:function(a){this.viewModel.unit=a}}]);return l}(H);d.__decorate([e.property()],c.prototype,"view",null);d.__decorate([e.property()],c.prototype,"visible",null);d.__decorate([e.property()],c.prototype,"active",null);d.__decorate([e.property({constructOnly:!0,nonNullable:!0})],c.prototype,"analysis",null);d.__decorate([e.property()],c.prototype,"iconClass",void 0);d.__decorate([e.property()],c.prototype,"label",null);d.__decorate([e.property(),
z.messageBundle("esri/widgets/DirectLineMeasurement3D/t9n/DirectLineMeasurement3D")],c.prototype,"messages",void 0);d.__decorate([e.property(),z.messageBundle("esri/core/t9n/Units")],c.prototype,"messagesUnits",void 0);d.__decorate([e.property()],c.prototype,"uiStrings",void 0);d.__decorate([e.property({type:x})],c.prototype,"viewModel",void 0);d.__decorate([e.property()],c.prototype,"unitOptions",null);d.__decorate([e.property()],c.prototype,"unit",null);d.__decorate([y.accessibleHandler()],c.prototype,
"_newMeasurement",null);d.__decorate([y.accessibleHandler()],c.prototype,"_changeUnit",null);return c=d.__decorate([G.subclass("esri.widgets.DirectLineMeasurement3D")],c)});