// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.25/esri/copyright.txt for details.
//>>built
define("../chunks/_rollupPluginBabelHelpers ../chunks/tslib.es6 ../Basemap ../Viewpoint ../core/asyncUtils ../core/Collection ../core/collectionUtils ../core/JSONSupport ../core/Logger ../core/maybe ../core/promiseUtils ../core/reactiveUtils ../core/accessorSupport/decorators/property ../core/arrayUtils ../core/accessorSupport/decorators/cast ../core/accessorSupport/decorators/subclass ../core/accessorSupport/ensureType ../chunks/vec3 ../chunks/vec3f64 ../layers/Layer ../layers/mixins/OperationalLayer ../support/basemapUtils ../views/3d/support/mathUtils ../views/3d/support/viewpointUtils ../views/support/Scheduler ../webdoc/support/SlideThumbnail ./SunLighting ./VirtualLighting ./support/Description ./support/SlideEnvironment ./support/SlideGround ./support/SlideVisibleLayer ./support/Title".split(" "),
function(q,k,R,S,T,H,U,g,V,r,B,W,m,ja,v,X,C,I,D,Y,Z,J,aa,ba,ca,u,da,ea,y,K,L,M,w){function N(e){if("building-scene"===e.type||"map-image"===e.type)return e.allSublayers.toArray()}function O(e){if(e=N(e))return e.filter(l=>l.visible).map(l=>l.id)}function fa(e,l){e=l-e;43200<e&&(e-=86400);-43200>e&&(e+=86400);return e}let ha=0;const E=H.ofType(M.SlideVisibleLayer);g=function(e){function l(a){a=e.call(this,a)||this;a.id=Date.now().toString(16)+"-slide-"+ha++;a.title=new w;a.description=new y;a.thumbnail=
new u.SlideThumbnail;a.viewpoint=null;a.basemap=null;a.ground=null;a.environment=new K.SlideEnvironment;a.visibleLayers=new E;return a}q._inheritsLoose(l,e);var d=l.prototype;d.destroy=function(){this.visibleLayers.removeAll();this.basemap=null;this.thumbnail&&this.thumbnail.destroy();this.thumbnail=this.title=this.description=null};d.castTitle=function(a){return"string"===typeof a?new w({text:a}):C.ensureType(w,a)};d.castDescription=function(a){return"string"===typeof a?new y({text:a}):C.ensureType(y,
a)};d.castThumbnail=function(a){return"string"===typeof a?new u.SlideThumbnail({url:a}):C.ensureType(u.SlideThumbnail,a)};d.castBasemap=function(a){return J.ensureType(a)};d.castVisibleLayers=function(a){return a&&"function"===typeof a.map?a.map(b=>{if("string"===typeof b)return{id:b};if(b instanceof Y){const c=O(b);return{id:b.id,sublayerIds:c}}if(b.id)return{id:b.id,sublayerIds:b.sublayerIds};V.getLogger(this.declaredClass).warn('Invalid visible layer, expected { id }, Layer or "id"');return b}):
null};d.clone=function(){return new this.constructor({id:this.id,title:this.title.clone(),thumbnail:this.thumbnail.clone(),description:this.description&&this.description.clone()||null,viewpoint:this.viewpoint&&this.viewpoint.clone()||null,basemap:this.basemap&&this.basemap.clone()||null,ground:this.ground&&this.ground.clone()||null,visibleLayers:this.visibleLayers.clone(),environment:this.environment&&this.environment.clone()||null})};d._updateVisibleLayersFrom=function(a){const b=[];return B.eachAlways(this._getLayers(a.map).map(c=>
a.whenLayerView(c).then(f=>{if(f.visible){const h=O(c);b.push(new M.SlideVisibleLayer({id:f.layer.id,sublayerIds:h}))}})).toArray()).then(()=>{this.visibleLayers.removeAll();this.visibleLayers.addMany(b)})};d.updateFrom=function(a,b){b={screenshot:{format:"png",quality:80,width:120,height:75,disableDecorations:!0,...(b&&b.screenshot)}};return a.when(()=>{this.viewpoint=a.viewpoint.clone();this.environment.lighting="virtual"===a.environment.lighting.type?ea.prototype.clone.apply(a.environment.lighting):
da.prototype.clone.apply(a.environment.lighting);this.environment.weather=a.environment.weather.clone();this.basemap=a.map.basemap&&a.map.basemap.clone()||null;this.ground=a.map.ground?L.fromGround(a.map.ground):null;return this._updateVisibleLayersFrom(a)}).then(()=>a.takeScreenshot(b.screenshot)).then(c=>{this.thumbnail=new u.SlideThumbnail({url:c.dataUrl});return this})};d.applyTo=function(){var a=q._asyncToGenerator(function*(b,c){var f=this;r.isSome(this._applyToController)&&this._applyToController.abort();
let h=new AbortController;this._applyToController=h;const F=B.onAbortOrThrow(c,()=>h.abort()),n=b.resourceController.scheduler.registerTask(ca.TaskPriority.SLIDE);let z=!1;c={animate:!0,...c,signal:this._applyToController.signal};var p=function(){var A=q._asyncToGenerator(function*(){yield Promise.all([n.schedule(()=>z=f._setViewpointOfInterest(b,c)),n.schedule(()=>f._applyBasemap(b,c),c.signal)]);yield Promise.all([n.schedule(()=>f._applyLayerVisibility(b),c.signal),n.schedule(()=>f._applyGround(b),
c.signal),n.schedule(()=>f._applyViewpoint(b,c),c.signal)]);yield n.schedule(()=>b.environment.weather=f.environment.weather.clone())});return function(){return A.apply(this,arguments)}}();p=yield T.result(b.addUpdatingPromise(p()));z&&(b.contentCamera=null);n.remove();this._applyToController===h&&(this._applyToController=null);h=null;F?.remove();if(!1===p.ok)throw p.error;return this});return function(b,c){return a.apply(this,arguments)}}();d._applyBasemap=function(){var a=q._asyncToGenerator(function*(b,
c){if(this.basemap){try{yield this.basemap.load(c)}catch(f){if(B.isAbortError(f))throw f;}b.map.basemap=J.clonePreservingTiledLayers(this.basemap,b.map.basemap)}});return function(b,c){return a.apply(this,arguments)}}();d._applyGround=function(a){this.ground&&(a.map.ground=this.ground.cloneAndApplyTo(a.map.ground))};d._getLayers=function(a){const b=new H;this._collectLayers(a,b);this._collectLayers(a.ground,b);return b};d._collectLayers=function(a,b){a.layers.forEach(c=>{Z.isOperationalLayer(c)&&
(b.add(c),"layers"in c&&this._collectLayers(c,b))})};d._applyLayerVisibility=function(a){this.visibleLayers&&this._getLayers(a.map).forEach(b=>{var c=this.visibleLayers.find(h=>h.id===b.id);b.visible=null!=c;const f=c&&c.sublayerIds;c=N(b);f&&c&&c.forEach(h=>h.visible=f.includes(h.id))})};d._setViewpointOfInterest=function(a,b){if(a.state.fixedContentCamera||!this.viewpoint||b.ignoreViewpoint||!b.useDestinationCamera)return!1;b=ba.toCamera(a,this.viewpoint);a.contentCamera=b;return r.isSome(b)};d._applyViewpoint=
function(){var a=q._asyncToGenerator(function*(b,c){this._applyCachedCameraTrackingEnabled(b);if(this.viewpoint&&!c.ignoreViewpoint){r.isSome(this.viewpoint.camera)&&(this.viewpoint.camera.fov=b.camera.fov);if(c.animate&&this.get("environment.lighting.date"))return this._animateToLighting(b,c);c.animate&&(b.environment.applyLighting(this.environment.lighting.clone()),yield b.goTo(this.viewpoint,c));b.viewpoint=this.viewpoint}b.environment.applyLighting(this.environment.lighting.clone())});return function(b,
c){return a.apply(this,arguments)}}();d._animateToLighting=function(){var a=q._asyncToGenerator(function*(b,c){let f=null;"virtual"!==b.environment.lighting.type&&"virtual"!==this.environment.lighting.type&&("global"===b.viewingMode&&(f=this._animateLightingWithCamera(b,b.environment.lighting,this.environment.lighting)),b.environment.cachedCameraTrackingEnabled=b.environment.lighting.cameraTrackingEnabled,b.environment.lighting.cameraTrackingEnabled=!1);b.environment.lighting.directShadowsEnabled=
this.environment.lighting.directShadowsEnabled;"virtual"===this.environment.lighting.type||"virtual"===b.environment.lighting.type?(b.environment.applyLighting(this.environment.lighting.clone()),"virtual"!==b.environment.lighting.type&&(b.environment.cachedCameraTrackingEnabled=b.environment.lighting.cameraTrackingEnabled,b.environment.lighting.cameraTrackingEnabled=!1)):null!=this.environment.lighting.displayUTCOffset&&(b.environment.lighting.displayUTCOffset=this.environment.lighting.displayUTCOffset);
return b.goTo(this.viewpoint,c).then(()=>{this._applyCachedCameraTrackingEnabled(b);b.environment.applyLighting(this.environment.lighting.clone())}).catch(h=>{r.isNone(b.animation)&&this._applyCachedCameraTrackingEnabled(b);throw h;}).finally(()=>{r.removeMaybe(f)})});return function(b,c){return a.apply(this,arguments)}}();d._applyCachedCameraTrackingEnabled=function(a){r.isSome(a.environment.cachedCameraTrackingEnabled)&&(a.environment.lighting.cameraTrackingEnabled=a.environment.cachedCameraTrackingEnabled,
a.environment.cachedCameraTrackingEnabled=null)};d._getTime=function(a){const b=a.getTime();a=3600*a.getUTCHours()+60*a.getUTCMinutes()+a.getUTCSeconds();return[b,a]};d._setTime=function(a,b,c){a.setTime(b);a.setUTCHours(c/3600);a.setUTCMinutes(c%3600/60);a.setUTCSeconds(c%3600%60);return a};d._animateLightingWithCamera=function(a,b,c){const [f,h]=this._getTime(new Date(b.date.toString())),[F,n]=this._getTime(c.date),z=fa(h,n),p=a.renderCoordsHelper,A=D.create();p.toRenderCoords(a.camera.position,
A);const P=D.create(),G=D.create();r.isSome(this.viewpoint.camera)&&p.toRenderCoords(this.viewpoint.camera.position,P);const ia=new Date;return W.when(()=>a.camera,t=>{p.toRenderCoords(t.position,G);var x=I.squaredDistance(A,G);const Q=I.squaredDistance(P,G);t=0;0!==x+Q&&(t=x/(x+Q));x=f+(F-f)*t;t=aa.moduloPositive(h+z*t,86400);b.date=this._setTime(ia,x,t)})};l.createFrom=function(a,b){return(new this).updateFrom(a,b)};q._createClass(l,[{key:"visibleLayers",set:function(a){this._set("visibleLayers",
U.referenceSetter(a,this._get("visibleLayers"),E))}}]);return l}(g.JSONSupport);k.__decorate([m.property({type:String,json:{write:{isRequired:!0}}})],g.prototype,"id",void 0);k.__decorate([m.property({type:w,json:{default:()=>new w({text:""}),write:{isRequired:!0}}})],g.prototype,"title",void 0);k.__decorate([v.cast("title")],g.prototype,"castTitle",null);k.__decorate([m.property({type:y,json:{write:{overridePolicy(e){return{enabled:!(!e||!e.text)}}}}})],g.prototype,"description",void 0);k.__decorate([v.cast("description")],
g.prototype,"castDescription",null);k.__decorate([m.property({type:u.SlideThumbnail,json:{default:()=>new u.SlideThumbnail({url:""}),write:{isRequired:!0}}})],g.prototype,"thumbnail",void 0);k.__decorate([v.cast("thumbnail")],g.prototype,"castThumbnail",null);k.__decorate([m.property({type:S,nonNullable:!0,json:{write:{isRequired:!0}}})],g.prototype,"viewpoint",void 0);k.__decorate([m.property({type:R,json:{read:{source:"baseMap"},write:{target:"baseMap"}}})],g.prototype,"basemap",void 0);k.__decorate([v.cast("basemap")],
g.prototype,"castBasemap",null);k.__decorate([m.property({type:L,json:{write:!0}})],g.prototype,"ground",void 0);k.__decorate([m.property({type:E,json:{write:{isRequired:!0}}})],g.prototype,"visibleLayers",null);k.__decorate([v.cast("visibleLayers")],g.prototype,"castVisibleLayers",null);k.__decorate([m.property({type:K.SlideEnvironment,json:{write:!0}})],g.prototype,"environment",void 0);return g=k.__decorate([X.subclass("esri.webscene.Slide")],g)});