// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.25/esri/copyright.txt for details.
//>>built
define("exports ../../../../chunks/_rollupPluginBabelHelpers ../../../../core/maybe ../../../../chunks/mat3 ../../../../chunks/mat3f32 ./enums ./RenderBucket ./decluttering/config ../webgl/TiledDisplayObject".split(" "),function(p,t,u,m,q,k,n,v,r){r=function(l){function g(b,a,c,f,e,h,x,y=null){a=l.call(this,b,a,c,f,e,h,4096,4096)||this;a._memCache=y;a.type="vector-tile";a._referenced=0;a._hasSymbolBuckets=!1;a._memoryUsedByLayerData=0;a.layerData=new Map;a.layerCount=0;a.status="loading";a.allSymbolsFadingOut=
!1;a.lastOpacityUpdate=0;a.symbols=new Map;a.isCoverage=!1;a.neededForCoverage=!1;a.decluttered=!1;a.invalidating=!1;a.parentTile=null;a.childrenTiles=new Set;a._processed=!1;a._referenced=1;a.styleRepository=x;a.id=b.id;return a}t._inheritsLoose(g,l);var d=g.prototype;d.setData=function(b){this.changeDataImpl(b);this.requestRender();this.ready();this.invalidating=!1;this._processed=!0};d.deleteLayerData=function(b){let a=!1;for(const c of b)this.layerData.has(c)&&(b=this.layerData.get(c),this._memoryUsedByLayerData-=
b.memoryUsed,b.type===k.BucketType.SYMBOL&&this.symbols.has(c)&&(this.symbols.delete(c),a=!0),b.destroy(),this.layerData.delete(c),this.layerCount--);u.isSome(this._memCache)&&this._memCache.updateSize(this.key.id,this,this._memoryUsedByLayerData);a&&this.emit("symbols-changed");this.requestRender()};d.processed=function(){return this._processed};d.hasData=function(){return 0<this.layerCount};d.dispose=function(){"unloaded"!==this.status&&(w.delete(this),g._destroyRenderBuckets(this.layerData),this.layerData=
null,this._memoryUsedByLayerData=this.layerCount=0,this.destroy(),this.status="unloaded")};d.release=function(){return 0===--this._referenced?(this.dispose(),this.stage=null,!0):!1};d.retain=function(){++this._referenced};d.changeDataImpl=function(b){let a=!1;if(b){const {bucketsWithData:c,emptyBuckets:f}=b;b=this._createRenderBuckets(c);if(f&&0<f.byteLength){const e=new Uint32Array(f);for(const h of e)this._deleteLayerData(h)}for(const [e,h]of b)this._deleteLayerData(e),h.type===k.BucketType.SYMBOL&&
(this.symbols.set(e,h.symbols),a=!0),this._memoryUsedByLayerData+=h.memoryUsed,this.layerData.set(e,h),this.layerCount++;u.isSome(this._memCache)&&this._memCache.updateSize(this.key.id,this,this._memoryUsedByLayerData)}this._hasSymbolBuckets=!1;for(const [,c]of this.layerData)c.type===k.BucketType.SYMBOL&&(this._hasSymbolBuckets=!0);a&&this.emit("symbols-changed")};d.attachWithContext=function(b){this.stage={context:b,trashDisplayObject(a){a.processDetach()},untrashDisplayObject(){return!1}}};d.setTransform=
function(b){l.prototype.setTransform.call(this,b);var a=this.resolution/(b.resolution*b.pixelRatio);const c=this.width/this.rangeX*a;a*=this.height/this.rangeY;const f=[0,0];b.toScreen(f,[this.x,this.y]);const e=this.transforms.tileUnitsToPixels;m.identity(e);m.translate(e,e,f);m.rotate(e,e,Math.PI*b.rotation/180);m.scale(e,e,[c,a,1])};d._createTransforms=function(){return{dvs:q.create(),tileMat3:q.create(),tileUnitsToPixels:q.create()}};g._destroyRenderBuckets=function(b){if(b){var a=new Set;b.forEach(c=>
{a.has(c)||(c.destroy(),a.add(c))});b.clear()}};d._createRenderBuckets=function(b){const a=new Map,c=new Map;for(const f of b){b=this._deserializeBucket(f,c);for(const e of b.layerUIDs)a.set(e,b)}return a};d._deserializeBucket=function(b,a){let c=a.get(b);if(c)return c;switch((new Uint32Array(b))[0]){case k.BucketType.FILL:c=new n.FillRenderBucket(b,this.styleRepository);break;case k.BucketType.LINE:c=new n.LineRenderBucket(b,this.styleRepository);break;case k.BucketType.SYMBOL:c=new n.SymbolRenderBucket(b,
this.styleRepository,this);break;case k.BucketType.CIRCLE:c=new n.CircleRenderBucket(b,this.styleRepository)}a.set(b,c);return c};d._deleteLayerData=function(b){if(this.layerData.has(b)){var a=this.layerData.get(b);this._memoryUsedByLayerData-=a.memoryUsed;a.destroy();this.layerData.delete(b);this.layerCount--}};t._createClass(g,[{key:"hasSymbolBuckets",get:function(){return this._hasSymbolBuckets}},{key:"isFading",get:function(){return this._hasSymbolBuckets&&performance.now()-this.lastOpacityUpdate<
v.FADE_DURATION}},{key:"isHoldingForFade",get:function(){return this._hasSymbolBuckets&&(!this.allSymbolsFadingOut||performance.now()-this.lastOpacityUpdate<v.FADE_DURATION)}},{key:"wasRequested",get:function(){return"errored"===this.status||"loaded"===this.status||"reloading"===this.status}},{key:"referenced",get:function(){return this._referenced}},{key:"memoryUsage",get:function(){return(this._memoryUsedByLayerData+256)/(this._referenced||1)}}]);return g}(r.TiledDisplayObject);const w=new Map;
p.VectorTile=r;p.printAllocations=function(){w.forEach((l,g)=>{console.log(`\n${g.key}:`);l[0].forEach(d=>console.log(d));console.log("\x3d\x3d\x3d\x3d\x3d\x3d\x3d\x3d");l[1].forEach(d=>console.log(d))})};Object.defineProperties(p,{__esModule:{value:!0},[Symbol.toStringTag]:{value:"Module"}})});