// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.25/esri/copyright.txt for details.
//>>built
define("exports ../../../../chunks/_rollupPluginBabelHelpers ../../../../core/maybe ./basicInterfaces ./BoundingInfo ./ContentObject ./ContentObjectType ./geometryDataUtils ./Indices ./Util ./VertexAttribute".split(" "),function(r,t,w,n,x,p,y,u,q,z,f){p=function(v){function k(a,c=[],d=n.PrimitiveType.Triangle,e=null,l=-1){var b=v.call(this)||this;b._primitiveType=d;b.objectAndLayerIdColor=e;b.edgeIndicesLength=l;b.type=y.ContentObjectType.Geometry;b._vertexAttributes=new Map;b._indices=new Map;b._boundingInfo=
null;for(const [g,m]of a)m&&b._vertexAttributes.set(g,{...m});if(null==c||0===c.length){a=b._vertexAttributes.values().next().value;a=null==a?0:a.data.length/a.size;c=q.generateDefaultIndexArray(a);b.edgeIndicesLength=0>b.edgeIndicesLength?a:b.edgeIndicesLength;for(const g of b._vertexAttributes.keys())b._indices.set(g,c)}else for(const [g,m]of c)m&&(b._indices.set(g,q.compactIndices(m)),g===f.VertexAttribute.POSITION&&(b.edgeIndicesLength=0>b.edgeIndicesLength?b._indices.get(g).length:b.edgeIndicesLength));
return b}t._inheritsLoose(k,v);var h=k.prototype;h.cloneShallow=function(){const a=new k([],void 0,this._primitiveType,this.objectAndLayerIdColor,void 0),{_vertexAttributes:c,_indices:d}=a;this._vertexAttributes.forEach((e,l)=>c.set(l,e));this._indices.forEach((e,l)=>d.set(l,e));a.screenToWorldRatio=this.screenToWorldRatio;a._boundingInfo=this._boundingInfo;return a};h.getMutableAttribute=function(a){(a=this._vertexAttributes.get(a))&&!a.exclusive&&(a.data=Array.from(a.data),a.exclusive=!0);return a};
h.computeAttachmentOrigin=function(a){return this.primitiveType===n.PrimitiveType.Triangle?this._computeAttachmentOriginTriangles(a):this._computeAttachmentOriginPoints(a)};h._computeAttachmentOriginTriangles=function(a){const c=this.indices.get(f.VertexAttribute.POSITION),d=this.vertexAttributes.get(f.VertexAttribute.POSITION);return u.computeAttachmentOriginTriangles(d,c,a)};h._computeAttachmentOriginPoints=function(a){const c=this.indices.get(f.VertexAttribute.POSITION),d=this.vertexAttributes.get(f.VertexAttribute.POSITION);
return u.computeAttachmentOriginPoints(d,c,a)};h.invalidateBoundingInfo=function(){this._boundingInfo=null};h._calculateBoundingInfo=function(){const a=this.indices.get(f.VertexAttribute.POSITION);if(!a||0===a.length)return null;const c=this.primitiveType===n.PrimitiveType.Triangle?3:1;z.assert(0===a.length%c,"Indexing error: "+a.length+" not divisible by "+c);const d=q.generateDefaultIndexArray(a.length/c),e=this.vertexAttributes.get(f.VertexAttribute.POSITION);return e?new x.BoundingInfo(d,c,a,
e):null};t._createClass(k,[{key:"vertexAttributes",get:function(){return this._vertexAttributes}},{key:"indices",get:function(){return this._indices}},{key:"indexCount",get:function(){const a=this._indices.values().next().value;return a?a.length:0}},{key:"primitiveType",get:function(){return this._primitiveType}},{key:"faceCount",get:function(){return this.indexCount/3}},{key:"boundingInfo",get:function(){w.isNone(this._boundingInfo)&&(this._boundingInfo=this._calculateBoundingInfo());return this._boundingInfo}}]);
return k}(p.ContentObject);r.Geometry=p;Object.defineProperties(r,{__esModule:{value:!0},[Symbol.toStringTag]:{value:"Module"}})});