// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.25/esri/copyright.txt for details.
//>>built
define("exports ../../../../chunks/_rollupPluginBabelHelpers ../../../../core/maybe ../../../../chunks/mat4 ../../../../chunks/mat4f64 ../../../../chunks/vec3 ../../../../chunks/vec3f64 ../../../../chunks/vec4 ../../../../chunks/vec4f64 ../../../../geometry/support/ray ../../../ViewingMode ./IntersectorInterfaces ./intersectorUtils ./verticalOffsetUtils ../materials/renderers/utils".split(" "),function(x,D,e,I,E,g,r,N,O,k,J,p,P,F,Q){let U=function(){function d(a){this.options=new p.IntersectorOptions;
this._results=new R;this.transform=new F.IntersectorTransform;this.tolerance=1E-5;this.verticalOffset=null;this._ray=k.create();this._rayEnd=r.create();this._rayBeginTransformed=r.create();this._rayEndTransformed=r.create();this.viewingMode=null==a?J.ViewingMode.Global:a}var b=d.prototype;b.reset=function(a,c,f){this.resetWithRay(k.fromPoints(a,c,this._ray),f)};b.resetWithRay=function(a,c){this.camera=c;a!==this._ray&&k.copy(a,this._ray);0!==this.options.verticalOffset?this.viewingMode===J.ViewingMode.Local?
this._ray.origin[2]-=this.options.verticalOffset:this.verticalOffset=this.options.verticalOffset:this.verticalOffset=null;g.add(this._rayEnd,this._ray.origin,this._ray.direction);this._results.init(this._ray)};b.intersect=function(a=null,c,f,t,q){this.point=c;this.filterPredicate=t;this.tolerance=null==f?1E-5:f;c=F.getVerticalOffsetObject3D(this.verticalOffset);if(e.isSome(a)&&0<a.length){const m=q?h=>{q(h)&&this.intersectObject(h)}:h=>{this.intersectObject(h)};for(const h of a)a=h.getSpatialQueryAccelerator&&
h.getSpatialQueryAccelerator(),e.isSome(a)?(e.isSome(c)?a.forEachAlongRayWithVerticalOffset(this._ray.origin,this._ray.direction,m,c):a.forEachAlongRay(this._ray.origin,this._ray.direction,m),this.options.selectionMode&&this.options.hud&&a.forEachDegenerateObject(m)):h.objects.forAll(y=>m(y))}this.sortResults()};b.intersectObject=function(a){const c=a.geometryRecords;if(c){var f=a.transformation,t=F.getVerticalOffsetObject3D(this.verticalOffset);for(const q of c){const {geometry:m,material:h,instanceParameters:y}=
q;if(Q.isInstanceHidden(y))continue;const K=m.id;this.transform.setAndInvalidateLazyTransforms(f,q.getShaderTransformation());g.transformMat4(this._rayBeginTransformed,this.rayBegin,this.transform.inverse);g.transformMat4(this._rayEndTransformed,this.rayEnd,this.transform.inverse);const S=this.transform.transform;e.isSome(t)&&(t.objectTransform=this.transform);h.intersect(m,y,this.transform.transform,this,this._rayBeginTransformed,this._rayEndTransformed,(u,L,M,n,z,A)=>{if(0<=u&&(!e.isSome(this.filterPredicate)||
this.filterPredicate(this._ray.origin,this._rayEnd,u))){var l=n?this._results.hud:this._results,B=n?G=>{const T={object:a,geometryId:K,triangleNr:M,center:e.isSome(A)?[A[0],A[1],A[2]]:null};G.set(p.IntersectorType.HUD,T,u,L,E.IDENTITY,z)}:G=>G.set(p.IntersectorType.OBJECT,{object:a,geometryId:K,triangleNr:M},u,L,S,z);(null==l.min.drapedLayerOrder||z>=l.min.drapedLayerOrder)&&(null==l.min.dist||u<l.min.dist)&&B(l.min);this.options.store!==p.StoreResults.MIN&&(null==l.max.drapedLayerOrder||z<l.max.drapedLayerOrder)&&
(null==l.max.dist||u>l.max.dist)&&B(l.max);this.options.store===p.StoreResults.ALL&&(n?(n=new H(this._ray),B(n),this._results.hud.all.push(n)):(n=new v(this._ray),B(n),this._results.all.push(n)))}},q.shaderTransformation)}}};b.sortResults=function(a=this._results.all){a.sort((c,f)=>c.dist!==f.dist?e.unwrapOr(c.dist,0)-e.unwrapOr(f.dist,0):c.drapedLayerOrder!==f.drapedLayerOrder?e.unwrapOr(c.drapedLayerOrder,Number.MAX_VALUE)-e.unwrapOr(f.drapedLayerOrder,Number.MAX_VALUE):e.unwrapOr(f.drapedLayerGraphicOrder,
Number.MIN_VALUE)-e.unwrapOr(c.drapedLayerGraphicOrder,Number.MIN_VALUE))};D._createClass(d,[{key:"results",get:function(){return this._results}},{key:"ray",get:function(){return this._ray}},{key:"rayBegin",get:function(){return this._ray.origin}},{key:"rayEnd",get:function(){return this._rayEnd}}]);return d}(),R=function(){function d(){this.min=new v(k.create());this.max=new v(k.create());this.hud={min:new H(k.create()),max:new H(k.create()),all:[]};this.ground=new v(k.create());this.all=[]}d.prototype.init=
function(b){this.min.init(b);this.max.init(b);this.ground.init(b);this.all.length=0;this.hud.min.init(b);this.hud.max.init(b);this.hud.all.length=0};return d}(),v=function(){function d(a){this.intersector=p.IntersectorType.OBJECT;this.normal=r.create();this.transformation=E.create();this._ray=k.create();this.init(a)}var b=d.prototype;b.getIntersectionPoint=function(a){if(!P.isValidIntersectorResult(this))return!1;g.scale(C,this.ray.direction,this.dist);g.add(a,this.ray.origin,C);return!0};b.getTransformedNormal=
function(a){g.copy(w,this.normal);w[3]=0;N.transformMat4(w,w,this.transformation);g.copy(a,w);return g.normalize(a,a)};b.init=function(a){this.drapedLayerGraphicOrder=this.drapedLayerOrder=this.target=this.dist=null;this.intersector=p.IntersectorType.OBJECT;k.copy(a,this._ray)};b.set=function(a,c,f,t,q,m,h){this.intersector=a;this.dist=f;g.copy(this.normal,e.unwrapOr(t,r.UNIT_Z));I.copy(this.transformation,e.unwrapOr(q,E.IDENTITY));this.target=c;this.drapedLayerOrder=m;this.drapedLayerGraphicOrder=
h};b.copy=function(a){k.copy(a.ray,this._ray);this.intersector=a.intersector;this.dist=a.dist;this.target=a.target;this.drapedLayerOrder=a.drapedLayerOrder;this.drapedLayerGraphicOrder=a.drapedLayerGraphicOrder;g.copy(this.normal,a.normal);I.copy(this.transformation,a.transformation)};D._createClass(d,[{key:"ray",get:function(){return this._ray}},{key:"distanceInRenderSpace",get:function(){return e.isSome(this.dist)?(g.scale(C,this.ray.direction,this.dist),g.length(C)):null}}]);return d}(),H=function(d){function b(){var a=
d.apply(this,arguments)||this;a.intersector=p.IntersectorType.HUD;return a}D._inheritsLoose(b,d);return b}(v);const C=r.create(),w=O.create();x.DEFAULT_TOLERANCE=1E-5;x.newIntersector=function(d){return new U(d)};x.newIntersectorResult=function(d){return new v(d)};Object.defineProperties(x,{__esModule:{value:!0},[Symbol.toStringTag]:{value:"Module"}})});