// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.25/esri/copyright.txt for details.
//>>built
define("exports ../../../../chunks/_rollupPluginBabelHelpers ../../../../core/maybe ../../../../core/uid ../../../../chunks/mat4 ../../../../chunks/mat4f64 ../../../../chunks/vec3 ../../../../chunks/vec4f64 ../../support/mathUtils ./basicInterfaces ./geometryDataUtils ./InstanceParameters ./Object3DStateID ./VertexAttribute ../materials/renderers/utils".split(" "),function(h,l,d,q,r,g,k,t,u,v,w,x,y,m,n){let p=function(){function f(a,b,c={}){this.data=a;this.material=b;this.boundingSphere=t.create();
this.instanceParameters=new x.InstanceParameters;this._transformation=g.create();this._shaderTransformationDirty=!0;this.layerUid=d.unwrapOr(c.layerUid,null);this.graphicUid=d.unwrapOr(c.graphicUid,null);this.id=c.id?c.id:q.generateUID();this.boundingInfo=d.unwrapOr(c.boundingInfo,null);this.calculateShaderTransformation=d.unwrapOr(c.calculateShaderTransformation,null);this.castShadow=c.castShadow?c.castShadow:!1}var e=f.prototype;e.updateTransformation=function(a){a(this._transformation);this._shaderTransformationDirty=
!0;this.computeBoundingSphere(this._transformation,this.boundingSphere)};e.shaderTransformationChanged=function(){this._shaderTransformationDirty=!0};e.computeBoundingSphere=function(a,b,c=u.maxScale(a)){d.isNone(this.boundingInfo)||(k.transformMat4(b,this.boundingInfo.getCenter(),a),b[3]=this.boundingInfo.getBSRadius()*c)};e.getShaderTransformation=function(){if(d.isNone(this.calculateShaderTransformation))return d.unwrapOr(this.transformation,g.IDENTITY);this._shaderTransformationDirty&&(this._shaderTransformation||
(this._shaderTransformation=g.create()),r.copy(this._shaderTransformation,this.calculateShaderTransformation(d.unwrapOr(this.transformation,g.IDENTITY))),this._shaderTransformationDirty=!1);return this._shaderTransformation};e.computeAttachmentOrigin=function(a){if(this.material.computeAttachmentOrigin)return this.material.computeAttachmentOrigin(this,a)?(d.isSome(this._transformation)&&k.transformMat4(a,a,this._transformation),!0):!1;const b=this.indices.get(m.VertexAttribute.POSITION),c=this.vertexAttributes.get(m.VertexAttribute.POSITION);
return w.computeAttachmentOriginTriangles(c,b,a)?(d.isSome(this._transformation)&&k.transformMat4(a,a,this._transformation),!0):!1};e.addHighlight=function(){const a=new y.Object3DStateID(v.Object3DState.Highlight),b=this.instanceParameters;b.highlights=n.addObject3DStateID(b.highlights,a);return a};e.removeHighlight=function(a){const b=this.instanceParameters;b.highlights=n.removeObject3DStateID(b.highlights,a)};l._createClass(f,[{key:"transformation",get:function(){return this._transformation}},
{key:"hasShaderTransformation",get:function(){return d.isSome(this.calculateShaderTransformation)}},{key:"primitiveType",get:function(){return this.data.primitiveType}},{key:"indices",get:function(){return this.data.indices}},{key:"vertexAttributes",get:function(){return this.data.vertexAttributes}}]);return f}(),z=function(f){function e(){return f.apply(this,arguments)||this}l._inheritsLoose(e,f);return e}(p);h.RenderGeometry=p;h.ValidatedRenderGeometry=z;Object.defineProperties(h,{__esModule:{value:!0},
[Symbol.toStringTag]:{value:"Module"}})});