// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.25/esri/copyright.txt for details.
//>>built
define("require exports ../../../../chunks/_rollupPluginBabelHelpers ../../../../chunks/tslib.es6 ../../../../core/Accessor ../../../../core/maybe ../../../../core/promiseUtils ../../../../core/accessorSupport/decorators/property ../../../../core/arrayUtils ../../../../core/accessorSupport/ensureType ../../../../core/accessorSupport/decorators/subclass ../../../../support/requestImageUtils ../core/shaderTechnique/ShaderTechniqueConfiguration ./BlendWeightsTechnique ./BlurTechnique ./EdgeDetectTechnique ./glUtil3D ../shaders/SMAAPassParameters ../../../webgl/enums ../../../webgl/FramebufferObject ../../../webgl/Texture".split(" "),
function(u,h,p,l,v,e,m,q,F,G,w,x,y,z,A,B,C,D,b,r,E){h.SmaaRenderPass=function(t){function k(d,c){var a=t.call(this,{})||this;a._rctx=d;a._techniqueRep=c;a._passParameters=new D.SMAAPassParameters;a._isEnabled=!1;return a}p._inheritsLoose(k,t);var g=k.prototype;g.normalizeCtorArgs=function(){return{}};g.dispose=function(){this._abortController=e.abortMaybe(this._abortController);this.disable()};g._loadResources=function(d){if(e.isSome(this._abortController))return!1;if(e.isSome(this._passParameters.searchTexture))return!0;
this._abortController=new AbortController;const c=this._abortController.signal;(new Promise((a,f)=>u(["./SmaaRenderPassData"],a,f))).then(a=>this._loadTextures(a,c)).then(()=>d()).finally(()=>this._abortController=null);return!1};g._loadTextures=function(d,c){m.throwIfAborted(c);return Promise.all([this._loadTextureFromBase64(d.areaTexture,b.TextureSamplingMode.LINEAR,b.PixelFormat.RGB),this._loadTextureFromBase64(d.searchTexure,b.TextureSamplingMode.NEAREST,b.PixelFormat.LUMINANCE)]).then(([a,f])=>
{m.isAborted(c)?(a.dispose(),f.dispose(),m.throwIfAborted(c)):(this._passParameters.areaTexture=a,this._passParameters.searchTexture=f)})};g.enable=function(d){if(this._isEnabled)return!0;if(!this._edgeDetectTechnique||!this._blendWeightsTechnique||!this._blurTechnique){const c=new y.ShaderTechniqueConfiguration;this._edgeDetectTechnique=this._techniqueRep.releaseAndAcquire(B.EdgeDetectTechnique,c,this._edgeDetectTechnique);this._blendWeightsTechnique=this._techniqueRep.releaseAndAcquire(z.BlendWeightsTechnique,
c,this._blendWeightsTechnique);this._blurTechnique=this._techniqueRep.releaseAndAcquire(A.BlurTechnique,c,this._blurTechnique)}if(!this._loadResources(d))return!1;this._vao=C.createScreenSizeTriangleVAO(this._rctx);this._passParameters.edges=new r.FramebufferObject(this._rctx,{colorTarget:b.TargetType.TEXTURE,depthStencilTarget:b.DepthStencilTargetType.NONE},{target:b.TextureType.TEXTURE_2D,pixelFormat:b.PixelFormat.RGB,dataType:b.PixelType.UNSIGNED_BYTE,samplingMode:b.TextureSamplingMode.LINEAR,
wrapMode:b.TextureWrapMode.CLAMP_TO_EDGE,width:4,height:4});this._passParameters.blend=new r.FramebufferObject(this._rctx,{colorTarget:b.TargetType.TEXTURE,depthStencilTarget:b.DepthStencilTargetType.NONE},{target:b.TextureType.TEXTURE_2D,pixelFormat:b.PixelFormat.RGBA,dataType:b.PixelType.UNSIGNED_BYTE,samplingMode:b.TextureSamplingMode.LINEAR,wrapMode:b.TextureWrapMode.CLAMP_TO_EDGE,width:4,height:4});return this._isEnabled=!0};g.disable=function(){this._isEnabled&&(this._vao=e.disposeMaybe(this._vao),
this._passParameters.areaTexture=e.disposeMaybe(this._passParameters.areaTexture),this._passParameters.searchTexture=e.disposeMaybe(this._passParameters.searchTexture),this._passParameters.blend=e.disposeMaybe(this._passParameters.blend),this._passParameters.edges=e.disposeMaybe(this._passParameters.edges),this._isEnabled=!1)};g.render=function(d){const c=this._validPassParameters;if(!e.isNone(c)){c.colorTexture=d;var a=this._rctx,f=a.getBoundFramebufferObject(),n=d.descriptor.width;d=d.descriptor.height;
a.bindVAO(this._vao);a.setViewport(0,0,n,d);c.edges.resize(n,d);a.bindFramebuffer(c.edges);a.setClearColor(0,0,0,1);a.clear(b.ClearBufferBit.COLOR_BUFFER_BIT);a.bindTechnique(this._edgeDetectTechnique,c,null);a.drawArrays(b.PrimitiveType.TRIANGLES,0,3);c.blend.resize(n,d);a.bindFramebuffer(c.blend);a.setClearColor(0,0,1,1);a.clear(b.ClearBufferBit.COLOR_BUFFER_BIT);a.bindTechnique(this._blendWeightsTechnique,c,null);a.drawArrays(b.PrimitiveType.TRIANGLES,0,3);a.bindFramebuffer(f);a.setClearColor(0,
1,0,1);a.clear(b.ClearBufferBit.COLOR_BUFFER_BIT);a.bindTechnique(this._blurTechnique,c,null);a.drawArrays(b.PrimitiveType.TRIANGLES,0,3)}};g._loadTextureFromBase64=function(d,c,a){return x.requestImage(d).then(f=>new E.Texture(this._rctx,{pixelFormat:a,dataType:b.PixelType.UNSIGNED_BYTE,wrapMode:b.TextureWrapMode.CLAMP_TO_EDGE,width:f.width,height:f.height,samplingMode:c},f))};p._createClass(k,[{key:"updating",get:function(){return e.isSome(this._abortController)}},{key:"_validPassParameters",get:function(){return this._isEnabled?
this._passParameters:null}}]);return k}(v);l.__decorate([q.property()],h.SmaaRenderPass.prototype,"_abortController",void 0);l.__decorate([q.property({readOnly:!0})],h.SmaaRenderPass.prototype,"updating",null);h.SmaaRenderPass=l.__decorate([w.subclass("esri.views.3d.webgl-engine.lib.SmaaRenderPass")],h.SmaaRenderPass);Object.defineProperties(h,{__esModule:{value:!0},[Symbol.toStringTag]:{value:"Module"}})});