// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.25/esri/copyright.txt for details.
//>>built
define("../../chunks/_rollupPluginBabelHelpers ../../chunks/tslib.es6 ../../Basemap ../../core/Collection ../../core/HandleOwner ../../core/Loadable ../../core/maybe ../../core/reactiveUtils ../../core/accessorSupport/decorators/property ../../core/arrayUtils ../../core/accessorSupport/decorators/cast ../../core/accessorSupport/decorators/subclass ../../geometry/projection ../../geometry/support/spatialReferenceUtils ../../support/basemapUtils ./support/basemapCompatibilityUtils ./support/BasemapGalleryItem ./support/LocalBasemapsSource ./support/PortalBasemapsSource".split(" "),
function(p,e,A,q,c,r,t,u,g,F,B,C,m,v,D,w,x,E,k){const y=q.ofType(x);c=function(z){function l(a){a=z.call(this,a)||this;a._loadingProjectionEngine=!1;a.items=new y;a.source=new k;a.view=null;return a}p._inheritsLoose(l,z);var h=l.prototype;h.initialize=function(){const a=()=>this._recreateItems();this.handles.add([u.watch(()=>"ready"===this.state?this.compatibilityFunction:null,()=>this._updateItems()),u.on(()=>this.source?.basemaps,"change",a,{onListenerAdd:a})])};h.castSource=function(a){return Array.isArray(a)||
q.isCollection(a)?new E({basemaps:a}):a&&"esri.portal.Portal"===a.declaredClass?new k({portal:a}):!a||a instanceof k||!a.portal&&!a.query?a&&"basemaps"in a&&"state"in a&&"refresh"in a?a:null:new k(a)};h.basemapEquals=function(a,b){return D.contentEquals(a,b)};h.refresh=function(){this._recreateItems()};h.load=function(a){this.addResolvingPromise(r.isLoadable(this.source)?this.source.load(a):null);return Promise.resolve(this)};h._recreateItems=function(){const a=this.source?.basemaps,{view:b,compatibilityFunction:d}=
this;this.items.removeAll().forEach(f=>f.destroy());a&&this.items.addMany(a.map(f=>new x({basemap:f,compatibilityFunction:d,view:b})))};h._updateItems=function(){for(const a of this.items)a.compatibilityFunction=this.compatibilityFunction,a.view=this.view};p._createClass(l,[{key:"activeBasemap",get:function(){return this.view?.map?.basemap??null},set:function(a){if(this.view.map){var b="string"===typeof a?A.fromId(a):a;if(b&&this.view.ready){var d=b.spatialReference||this.items?.find(f=>this.basemapEquals(b,
f.basemap))?.spatialReference;if(d&&"spatialReferenceLocked"in this.view&&!this.view.spatialReferenceLocked){const f=this.view.spatialReference;!t.isSome(d)||v.equals(f,d)||m.canProjectWithoutEngine(this.view.spatialReference,d)||m.isLoaded()?(this.view.map.basemap=b,this._clearOverride("activeBasemap"),t.isSome(d)&&!v.equals(this.view.spatialReference,d)&&(this.view.spatialReference=d)):(this._override("activeBasemap",b),this._loadingProjectionEngine=!0,m.load().then(()=>{this._get("activeBasemap")===
a&&(this.view.map.basemap=a,this.view.spatialReference=d,this._clearOverride("activeBasemap"))},()=>{}).then(()=>{this._loadingProjectionEngine=!1}))}else this.view.map.basemap=b,this._clearOverride("activeBasemap")}else this.view.map.basemap=b,this._clearOverride("activeBasemap")}}},{key:"activeBasemapIndex",get:function(){const {state:a,items:b,activeBasemap:d}=this;if("ready"!==a)return-1;const f=b.findIndex(n=>n.basemap===d);return-1===f?b.findIndex(n=>this.basemapEquals(n.basemap,d)):f}},{key:"compatibilityFunction",
get:function(){return"3d"===this.view?.type?w.default3DCompatibility:w.default2DCompatibility},set:function(a){this._overrideIfSome("compatibilityFunction",a)}},{key:"state",get:function(){return this.view?.ready&&this.source?this._loadingProjectionEngine?"loading":"ready":"disabled"}}]);return l}(c.HandleOwnerMixin(r));e.__decorate([g.property()],c.prototype,"_loadingProjectionEngine",void 0);e.__decorate([g.property()],c.prototype,"activeBasemap",null);e.__decorate([g.property({readOnly:!0})],c.prototype,
"activeBasemapIndex",null);e.__decorate([g.property()],c.prototype,"compatibilityFunction",null);e.__decorate([g.property({readOnly:!0,type:y})],c.prototype,"items",void 0);e.__decorate([g.property()],c.prototype,"source",void 0);e.__decorate([B.cast("source")],c.prototype,"castSource",null);e.__decorate([g.property({readOnly:!0})],c.prototype,"state",null);e.__decorate([g.property()],c.prototype,"view",void 0);return c=e.__decorate([C.subclass("esri.widgets.BasemapGallery.BasemapGalleryViewModel")],
c)});