// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.25/esri/copyright.txt for details.
//>>built
define("../../../chunks/_rollupPluginBabelHelpers ../sources/Empty ../support/errorsupport ../support/FeatureSet ../support/IdSet ../support/shared ../../../geometry/geometryEngineAsync".split(" "),function(l,m,u,k,t,q,n){return function(v){function g(b){var a=v.call(this,b)||this;a._relation="";a._relationGeom=null;a._relationString="";a.declaredClass="esri.arcade.featureset.actions.SpatialFilter";a._relationString=b.relationString;a._parent=b.parentfeatureset;a._maxProcessing=40;a._relation=b.relation;
a._relationGeom=b.relationGeom;return a}l._inheritsLoose(g,v);var h=g.prototype;h._getSet=function(){var b=l._asyncToGenerator(function*(a){if(null===this._wset){yield this._ensureLoaded();const c=yield this._parent._getFilteredSet("esriSpatialRelRelation"!==this._relation?this._relation:this._relation+":"+this._relationString,this._relationGeom,null,null,a);this._checkCancelled(a);this._wset=new t(c._candidates.slice(0),c._known.slice(0),c._ordered,this._clonePageDefinition(c.pagesDefinition))}return this._wset});
return function(a){return b.apply(this,arguments)}}();h._isInFeatureSet=function(b){let a=this._parent._isInFeatureSet(b);if(a===q.IdState.NotInFeatureSet)return a;a=this._idstates[b];return void 0===a?q.IdState.Unknown:a};h._getFeature=function(b,a,c){return this._parent._getFeature(b,a,c)};h._getFeatures=function(b,a,c,e){return this._parent._getFeatures(b,a,c,e)};h._featureFromCache=function(b){return this._parent._featureFromCache(b)};h.executeSpatialRelationTest=function(){var b=l._asyncToGenerator(function*(a){if(null===
a.geometry)return!1;switch(this._relation){case "esriSpatialRelEnvelopeIntersects":const c=q.shapeExtent(this._relationGeom);a=q.shapeExtent(a.geometry);return n.intersects(c,a);case "esriSpatialRelIntersects":return n.intersects(this._relationGeom,a.geometry);case "esriSpatialRelContains":return n.contains(this._relationGeom,a.geometry);case "esriSpatialRelOverlaps":return n.overlaps(this._relationGeom,a.geometry);case "esriSpatialRelWithin":return n.within(this._relationGeom,a.geometry);case "esriSpatialRelTouches":return n.touches(this._relationGeom,
a.geometry);case "esriSpatialRelCrosses":return n.crosses(this._relationGeom,a.geometry);case "esriSpatialRelRelation":return n.relate(this._relationGeom,a.geometry,this._relationString??"")}});return function(a){return b.apply(this,arguments)}}();h._fetchAndRefineFeatures=function(){var b=l._asyncToGenerator(function*(a,c,e){var f=new t([],a,!1,null),d=Math.min(c,a.length);yield this._parent?._getFeatures(f,-1,d,e);this._checkCancelled(e);e=[];for(f=0;f<d;f++){const p=this._parent._featureFromCache(a[f]);
e.push(yield this.executeSpatialRelationTest(p))}for(d=0;d<c;d++)this._idstates[a[d]]=!0===e[d]?q.IdState.InFeatureSet:q.IdState.NotInFeatureSet;return"success"});return function(a,c,e){return b.apply(this,arguments)}}();h._getFilteredSet=function(){var b=l._asyncToGenerator(function*(a,c,e,f,d){yield this._ensureLoaded();a=yield this._parent._getFilteredSet("esriSpatialRelRelation"!==this._relation?this._relation:this._relation+":"+this._relationString,this._relationGeom,e,f,d);this._checkCancelled(d);
return null!==c?new t(a._candidates.slice(0).concat(a._known.slice(0)),[],a._ordered,this._clonePageDefinition(a.pagesDefinition)):new t(a._candidates.slice(0),a._known.slice(0),a._ordered,this._clonePageDefinition(a.pagesDefinition))});return function(a,c,e,f,d){return b.apply(this,arguments)}}();h._stat=function(){var b=l._asyncToGenerator(function*(a,c,e,f,d,p,r){if(""!==e)return{calculated:!1};const w=yield this._parent._stat(a,c,"esriSpatialRelRelation"!==this._relation?this._relation:this._relation+
":"+this._relationString,this._relationGeom,d,p,r);return!1===w.calculated?null===d&&""===e&&null===f?this._manualStat(a,c,p,r):{calculated:!1}:w});return function(a,c,e,f,d,p,r){return b.apply(this,arguments)}}();h._canDoAggregates=function(){var b=l._asyncToGenerator(function*(a,c,e,f,d){return""!==e||null!==f||null===this._parent?!1:this._parent._canDoAggregates(a,c,"esriSpatialRelRelation"!==this._relation?this._relation:this._relation+":"+this._relationString,this._relationGeom,d)});return function(a,
c,e,f,d){return b.apply(this,arguments)}}();h._getAggregatePagesDataSourceDefinition=function(){var b=l._asyncToGenerator(function*(a,c,e,f,d,p,r){if(null===this._parent)throw new u.FeatureSetError(u.FeatureSetErrorCodes.NeverReach);return this._parent._getAggregatePagesDataSourceDefinition(a,c,"esriSpatialRelRelation"!==this._relation?this._relation:this._relation+":"+this._relationString,this._relationGeom,d,p,r)});return function(a,c,e,f,d,p,r){return b.apply(this,arguments)}}();g.registerAction=
function(){k._featuresetFunctions.intersects=function(b){return null===b||void 0===b?new m({parentfeatureset:this}):new g({parentfeatureset:this,relation:"esriSpatialRelIntersects",relationGeom:b})};k._featuresetFunctions.envelopeIntersects=function(b){return null===b||void 0===b?new m({parentfeatureset:this}):new g({parentfeatureset:this,relation:"esriSpatialRelEnvelopeIntersects",relationGeom:b})};k._featuresetFunctions.contains=function(b){return null===b||void 0===b?new m({parentfeatureset:this}):
new g({parentfeatureset:this,relation:"esriSpatialRelContains",relationGeom:b})};k._featuresetFunctions.overlaps=function(b){return null===b||void 0===b?new m({parentfeatureset:this}):new g({parentfeatureset:this,relation:"esriSpatialRelOverlaps",relationGeom:b})};k._featuresetFunctions.within=function(b){return null===b||void 0===b?new m({parentfeatureset:this}):new g({parentfeatureset:this,relation:"esriSpatialRelWithin",relationGeom:b})};k._featuresetFunctions.touches=function(b){return null===
b||void 0===b?new m({parentfeatureset:this}):new g({parentfeatureset:this,relation:"esriSpatialRelTouches",relationGeom:b})};k._featuresetFunctions.crosses=function(b){return null===b||void 0===b?new m({parentfeatureset:this}):new g({parentfeatureset:this,relation:"esriSpatialRelCrosses",relationGeom:b})};k._featuresetFunctions.relate=function(b,a){return null===b||void 0===b?new m({parentfeatureset:this}):new g({parentfeatureset:this,relation:"esriSpatialRelRelation",relationGeom:b,relationString:a})}};
return g}(k)});