// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.25/esri/copyright.txt for details.
//>>built
define("exports ../../../chunks/_rollupPluginBabelHelpers ../../../chunks/tslib.es6 ../../../core/Accessor ../../../core/mathUtils ../../../core/maybe ../../../core/time ../../../core/accessorSupport/decorators/property ../../../core/arrayUtils ../../../core/accessorSupport/ensureType ../../../core/accessorSupport/decorators/subclass ../../../core/support/WatchUpdatingTracking ../../../geometry/projectionEllipsoid ./PrecipitationTechnique ./PrecipitationTechniqueConfiguration ../support/buffer/glUtil ../support/buffer/InterleavedLayout ../webgl-engine/lib/AnimationTimer ../webgl-engine/lib/VertexArrayObject ../webgl-engine/lib/VertexAttribute ../../webgl/BufferObject ../../webgl/enums ../../webgl/Util".split(" "),
function(d,r,k,B,t,c,C,l,J,K,D,E,F,e,m,u,v,G,H,w,x,p,y){d.Precipitation=function(z){function n(a){var b=z.call(this,a)||this;b._numParticles=25E4;b._rainSpeed=.1;b._snowSpeed=.01;b._passParameters=new e.PrecipitationPassParameters;b._animation=new G.AnimationTimer;b._updatingTracking=new E.WatchUpdatingTracking;b._passParameters.time=0;b._passParameters.radius=F.getReferenceEllipsoid(a.view.spatialReference).radius;b._shaderTechniqueRepository=a.context.shaderTechniqueRepository;return b}r._inheritsLoose(n,
z);var f=n.prototype;f.destroy=function(){this._updatingTracking.destroy();this._numParticles=0;this._snowTechniqueCached=c.releaseMaybe(this._snowTechniqueCached);this._rainTechniqueCached=c.releaseMaybe(this._rainTechniqueCached);this._vao=c.disposeMaybe(this._vao);this._instanceIdBuffer=c.disposeMaybe(this._instanceIdBuffer)};f.update=function(a){return this._animation.advance(a)};f.render=function(a,b,g){const q="rainy"===g?this._rainTechnique:this._snowTechnique;if(q.compiled){var h=a.rctx;this._ensureResources(h);
c.isNone(q)||c.isNone(this._vao)||c.isNone(this._instanceIdBuffer)||(c.isSome(a.bindParameters.cloudsFade.data)&&(this._passParameters.opacity=1-a.bindParameters.cloudsFade.fadeInOutHeight.factor),0>=this._passParameters.opacity||(b=.5>b?t.lerp(0,.35,2*b):t.lerp(.35,1,2*(b-.5)),this._passParameters.time=("rainy"===g?this._rainSpeed:this._snowSpeed)*C.secondsFromMilliseconds(this._animation.time)%1E5,a=h.bindTechnique(q,this._passParameters,a.bindParameters),h.bindVAO(this._vao),a.assertCompatibleVertexAttributeLocations(this._vao),
y.bindVertexBufferLayout(h,e.attributeLocations,this._instanceIdBuffer,A,0),h.capabilities.instancing.drawArraysInstanced(p.PrimitiveType.TRIANGLES,0,3,this._numParticles*b),y.unbindVertexBufferLayout(h,e.attributeLocations,this._instanceIdBuffer,A)))}else this.context.requestRender()};f._ensureResources=function(a){c.isNone(this._vao)&&(this._vao=this._createVertexArrayObject(a));c.isNone(this._instanceIdBuffer)&&(this._instanceIdBuffer=this._createInstanceIndices(a))};f._createInstanceIndices=function(a){const b=
[];for(let g=0;g<this._numParticles;g++)b.push(g);return x.BufferObject.createVertex(a,p.Usage.STATIC_DRAW,new Float32Array(b))};f._createVertexArrayObject=function(a){const b=new Float32Array([-1,0,1,1,0,-1,1,0,1]);return new H.VertexArrayObject(a,e.attributeLocations,{geometry:u.glLayout(I)},{geometry:x.BufferObject.createVertex(a,p.Usage.STATIC_DRAW,b)})};r._createClass(n,[{key:"updating",get:function(){return this._updatingTracking.updating}},{key:"_rainTechnique",get:function(){if(c.isNone(this._rainTechniqueCached)){const a=
new m.PrecipitationTechniqueConfiguration;a.type=m.PrecipitationType.Rain;this._rainTechniqueCached=this._shaderTechniqueRepository.acquire(e.PrecipitationTechnique,a)}return this._rainTechniqueCached}},{key:"_snowTechnique",get:function(){if(c.isNone(this._snowTechniqueCached)){const a=new m.PrecipitationTechniqueConfiguration;a.type=m.PrecipitationType.Snow;this._snowTechniqueCached=this._shaderTechniqueRepository.acquire(e.PrecipitationTechnique,a)}return this._snowTechniqueCached}}]);return n}(B);
k.__decorate([l.property({constructOnly:!0})],d.Precipitation.prototype,"context",void 0);k.__decorate([l.property({constructOnly:!0})],d.Precipitation.prototype,"view",void 0);k.__decorate([l.property({readOnly:!0})],d.Precipitation.prototype,"updating",null);k.__decorate([l.property()],d.Precipitation.prototype,"_updatingTracking",void 0);d.Precipitation=k.__decorate([D.subclass("esri.views.3d.environment.Precipitation")],d.Precipitation);const I=v.newLayout().vec3f(w.VertexAttribute.POSITION),
A=u.glLayout(v.newLayout().f32(w.VertexAttribute.INSTANCEFEATUREATTRIBUTE),1);Object.defineProperties(d,{__esModule:{value:!0},[Symbol.toStringTag]:{value:"Module"}})});