// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.25/esri/copyright.txt for details.
//>>built
define("../chunks/_rollupPluginBabelHelpers ./Dictionary ./ImmutableArray ../chunks/languageUtils ../geometry/Geometry ../geometry/Point ../geometry/support/jsonUtils ../layers/graphics/featureConversionUtils ../core/maybe ./executionError".split(" "),function(u,q,m,h,r,t,n,v,p,l){return function(){function g(){this.arcadeDeclaredClass="esri.arcade.Feature";this._layer=this.attributes=this._geometry=this._optimizedGeomDefinition=null;this.immutable=this._datesfixed=!0;this._datefields=null;this.immutable=
!0}g.createFromGraphic=function(a){const b=new g;b._geometry=p.isSome(a.geometry)?a.geometry:null;b.attributes=void 0===a.attributes?{}:null===a.attributes?{}:a.attributes;a._sourceLayer?(b._layer=a._sourceLayer,b._datesfixed=!1):a._layer?(b._layer=a._layer,b._datesfixed=!1):a.layer&&"fields"in a.layer?(b._layer=a.layer,b._datesfixed=!1):a.sourceLayer&&"fields"in a.sourceLayer&&(b._layer=a.sourceLayer,b._datesfixed=!1);return b};g.createFromArcadeFeature=function(a){const b=new g;b._datesfixed=a._datesfixed;
b.attributes=a.attributes;b._geometry=a._geometry;b._optimizedGeomDefinition=a._optimizedGeomDefinition;a._layer&&(b._layer=a._layer);return b};g.createFromOptimisedFeature=function(a,b,d){const c=new g;c._geometry=a.geometry?{geometry:a.geometry}:null;c._optimizedGeomDefinition=d;c.attributes=a.attributes||{};c._layer=b;c._datesfixed=!1;return c};g.createFromArcadeDictionary=function(a){const b=new g;b.attributes=a.field("attributes");null!==b.attributes?b.attributes instanceof q?(b.attributes=b.attributes.attributes,
null===b.attributes&&(b.attributes={})):b.attributes={}:b.attributes={};b._geometry=a.field("geometry");null!==b._geometry&&(b._geometry instanceof q?b._geometry=g.parseGeometryFromDictionary(b._geometry):b._geometry instanceof r||(b._geometry=null));return b};g.createFromGraphicLikeObject=function(a,b,d=null){const c=new g;null===b&&(b={});c.attributes=b;c._geometry=p.isSome(a)?a:null;c._layer=d;c._layer&&(c._datesfixed=!1);return c};var k=g.prototype;k.repurposeFromGraphicLikeObject=function(a,
b,d=null){null===b&&(b={});this.attributes=b;this._geometry=a?a:null;this._datesfixed=(this._layer=d)?!1:!0};k.castToText=function(a=!1){let b="";!1===this._datesfixed&&this._fixDates();for(const d in this.attributes){""!==b&&(b+=",");const c=this.attributes[d];null==c?b+=JSON.stringify(d)+":null":h.isBoolean(c)||h.isNumber(c)||h.isString(c)?b+=JSON.stringify(d)+":"+JSON.stringify(c):c instanceof r?b+=JSON.stringify(d)+":"+h.toStringExplicit(c):c instanceof m?b+=JSON.stringify(d)+":"+h.toStringExplicit(c,
null,a):c instanceof Array?b+=JSON.stringify(d)+":"+h.toStringExplicit(c,null,a):c instanceof Date?b=a?b+(JSON.stringify(d)+":"+JSON.stringify(c.getTime())):b+(JSON.stringify(d)+":"+JSON.stringify(c)):null!==c&&"object"===typeof c&&void 0!==c.castToText&&(b+=JSON.stringify(d)+":"+c.castToText(a))}return'{"geometry":'+(null===this.geometry()?"null":h.toStringExplicit(this.geometry()))+',"attributes":{'+b+"}}"};k._fixDates=function(){if(null!==this._datefields)0<this._datefields.length&&this._fixDateFields(this._datefields);
else{var a=[],b=this._layer.fields;for(let d=0;d<b.length;d++){const c=b[d],f=c.type;"date"!==f&&"esriFieldTypeDate"!==f||a.push(c.name)}this._datefields=a;0<a.length&&this._fixDateFields(a)}this._datesfixed=!0};k._fixDateFields=function(a){this.attributes={...this.attributes};for(let b=0;b<a.length;b++){let d=this.attributes[a[b]];if(null!==d)if(void 0===d)for(const c in this.attributes){if(c.toLowerCase()===a[b].toLowerCase()){d=this.attributes[c];null===d||d instanceof Date||(this.attributes[c]=
new Date(d));break}}else d instanceof Date||(this.attributes[a[b]]=new Date(d))}};k.geometry=function(){if(null===this._geometry||this._geometry instanceof r)return this._geometry;this._optimizedGeomDefinition?(this._geometry=p.unwrap(n.fromJSON(v.convertToGeometry(this._geometry,this._optimizedGeomDefinition.geometryType,this._optimizedGeomDefinition.hasZ,this._optimizedGeomDefinition.hasM))),this._geometry.spatialReference=this._optimizedGeomDefinition.spatialReference):this._geometry=p.unwrap(n.fromJSON(this._geometry));
return this._geometry};k.field=function(a){!1===this._datesfixed&&this._fixDates();var b=this.attributes[a];if(void 0!==b)return b;b=a.toLowerCase();for(const d in this.attributes)if(d.toLowerCase()===b)return this.attributes[d];if(this._hasFieldDefinition(b))return null;throw new l.ArcadeExecutionError(null,l.ExecutionErrorCodes.FieldNotFound,null,{key:a});};k._hasFieldDefinition=function(a){if(null===this._layer)return!1;for(let b=0;b<this._layer.fields.length;b++)if(this._layer.fields[b].name.toLowerCase()===
a)return!0;return!1};k.setField=function(a,b){if(this.immutable)throw new l.ArcadeExecutionError(null,l.ExecutionErrorCodes.Immutable,null);if(!1===h.isSimpleType(b))throw new l.ArcadeExecutionError(null,l.ExecutionErrorCodes.TypeNotAllowedInFeature,null);const d=a.toLowerCase();if(void 0===this.attributes[a])for(const c in this.attributes)if(c.toLowerCase()===d){this.attributes[c]=b;return}this.attributes[a]=b};k.hasField=function(a){const b=a.toLowerCase();if(void 0!==this.attributes[a])return!0;
for(const d in this.attributes)if(d.toLowerCase()===b)return!0;return this._hasFieldDefinition(b)?!0:!1};k.keys=function(){let a=[];const b={};for(var d in this.attributes)a.push(d),b[d.toLowerCase()]=1;if(null!==this._layer)for(d=0;d<this._layer.fields.length;d++){const c=this._layer.fields[d];1!==b[c.name.toLowerCase()]&&a.push(c.name)}return a=a.sort()};g.parseGeometryFromDictionary=function(a){a=g._convertDictionaryToJson(a,!0);void 0!==a.hasm&&(a.hasM=a.hasm,delete a.hasm);void 0!==a.hasz&&(a.hasZ=
a.hasz,delete a.hasz);void 0!==a.spatialreference&&(a.spatialReference=a.spatialreference,delete a.spatialreference);void 0!==a.rings&&(a.rings=this._fixPathArrays(a.rings,!0===a.hasZ,!0===a.hasZ));void 0!==a.paths&&(a.paths=this._fixPathArrays(a.paths,!0===a.hasZ,!0===a.hasM));void 0!==a.points&&(a.points=this._fixPointArrays(a.points,!0===a.hasZ,!0===a.hasM));return n.fromJSON(a)};g._fixPathArrays=function(a,b,d){const c=[];if(a instanceof Array)for(var f=0;f<a.length;f++)c.push(this._fixPointArrays(a[f],
b,d));else if(a instanceof m)for(f=0;f<a.length();f++)c.push(this._fixPointArrays(a.get(f),b,d));return c};g._fixPointArrays=function(a,b,d){const c=[];if(a instanceof Array)for(var f=0;f<a.length;f++){var e=a[f];e instanceof t?b&&d?c.push([e.x,e.y,e.z,e.m]):b?c.push([e.x,e.y,e.z]):d?c.push([e.x,e.y,e.m]):c.push([e.x,e.y]):e instanceof m?c.push(e.toArray()):c.push(e)}else if(a instanceof m)for(f=0;f<a.length();f++)e=a.get(f),e instanceof t?b&&d?c.push([e.x,e.y,e.z,e.m]):b?c.push([e.x,e.y,e.z]):d?
c.push([e.x,e.y,e.m]):c.push([e.x,e.y]):e instanceof m?c.push(e.toArray()):c.push(e);return c};g._convertDictionaryToJson=function(a,b=!1){const d={};for(const c in a.attributes){let f=a.attributes[c];f instanceof q&&(f=g._convertDictionaryToJson(f));b?d[c.toLowerCase()]=f:d[c]=f}return d};g.parseAttributesFromDictionary=function(a){const b={};for(const d in a.attributes){const c=a.attributes[d];if(h.isSimpleType(c))b[d]=c;else throw new l.ArcadeExecutionError(null,l.ExecutionErrorCodes.InvalidParameter,
null);}return b};g.fromJson=function(a){let b=null;null!==a.geometry&&void 0!==a.geometry&&(b=n.fromJSON(a.geometry));const d={};if(null!==a.attributes&&void 0!==a.attributes)for(const c in a.attributes){const f=a.attributes[c];if(null===f)d[c]=f;else if(h.isString(f)||h.isNumber(f)||h.isBoolean(f)||h.isDate(f))d[c]=f;else throw new l.ArcadeExecutionError(null,l.ExecutionErrorCodes.InvalidParameter,null);}return g.createFromGraphicLikeObject(b,d,null)};k.fullSchema=function(){return this._layer};
k.gdbVersion=function(){if(null===this._layer)return"";const a=this._layer.gdbVersion;return void 0===a?"":""===a&&this._layer.capabilities&&this._layer.capabilities.isVersioned?"SDE.DEFAULT":a};k.castAsJson=function(a){const b={attributes:{},geometry:!0===a?.keepGeometryType?this.geometry():this.geometry().toJSON()};for(const d in this.attributes){const c=this.attributes[d];void 0!==c&&(b.attributes[d]=h.castAsJson(c,a))}return b};k.castAsJsonAsync=function(){var a=u._asyncToGenerator(function*(b,
d){return this.castAsJson(d)});return function(){return a.apply(this,arguments)}}();return g}()});