// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.25/esri/copyright.txt for details.
//>>built
define("../../core/mathUtils ./CIMSymbolHelper ./rasterizingUtils ./Rect ./SDFHelper ./utils".split(" "),function(y,m,v,w,t,z){return function(){function x(a){this._resourceManager=a}var u=x.prototype;u.dispose=function(){this._rasterizationCanvas=null};u.rasterizeJSONResource=function(a,f,c){this._rasterizationCanvas||(this._rasterizationCanvas=document.createElement("canvas"));if("simple-fill"===a.type||"esriSFS"===a.type){const [g,h,k]=v.rasterizeSimpleFill(this._rasterizationCanvas,a.style,f);
return{size:[h,k],image:new Uint32Array(g.buffer),sdf:!1,simplePattern:!0,anchorX:0,anchorY:0,rasterizationScale:y.nextPowerOfTwo(Math.ceil(f))}}if("simple-line"===a.type||"esriSLS"===a.type||"line"===a.type&&a.dashTemplate){if("simple-line"===a.type||"esriSLS"===a.type)switch(f=m.slsDashToTemplateArray(a.style,a.cap),a.cap){case "butt":a="Butt";break;case "square":a="Square";break;default:a="Round"}else f=a.dashTemplate,a=a.cim.capStyle;const [g,h,k]=v.rasterizeDash(f,a);return{size:[h,k],image:new Uint32Array(g.buffer),
sdf:!0,simplePattern:!0,anchorX:0,anchorY:0}}let b,e,d=1;"simple-marker"===a.type||"esriSMS"===a.type||"line-marker"===a.type?(a=m.CIMSymbolHelper.fromSimpleMarker(a),e=t.getSDFInfo(a)):a.cim&&"CIMHatchFill"===a.cim.type?(a=m.CIMSymbolHelper.fromCIMHatchFill(a.cim,f),b=new w(a.frame.xmin,-a.frame.ymax,a.frame.xmax-a.frame.xmin,a.frame.ymax-a.frame.ymin),d=f):a.cim.markerPlacement&&"CIMMarkerPlacementInsidePolygon"===a.cim.markerPlacement.type?(a=m.CIMSymbolHelper.fromCIMInsidePolygon(a.cim),b=new w(a.frame.xmin,
-a.frame.ymax,a.frame.xmax-a.frame.xmin,a.frame.ymax-a.frame.ymin)):(a=a.cim,e=t.getSDFInfo(a));if(e&&!c){const [g,h,k]=t.buildSDF(e);return g?{size:[h,k],image:new Uint32Array(g.buffer),sdf:!0,simplePattern:!0,anchorX:0,anchorY:0,rasterizationScale:d}:null}const [l,n,p,q,r]=m.CIMSymbolHelper.rasterize(this._rasterizationCanvas,a,b,this._resourceManager,!c);return l?{size:[n,p],image:new Uint32Array(l.buffer),sdf:!1,simplePattern:!1,anchorX:q,anchorY:r}:null};u.rasterizeImageResource=function(a,f,
c,b){this._rasterizationCanvas||(this._rasterizationCanvas=document.createElement("canvas"));this._rasterizationCanvas.width=a;this._rasterizationCanvas.height=f;var e=this._rasterizationCanvas.getContext("2d");c instanceof ImageData?e.putImageData(c,0,0):(c.setAttribute("width",`${a}px`),c.setAttribute("height",`${f}px`),e.drawImage(c,0,0,a,f));c=e.getImageData(0,0,a,f);c=new Uint8Array(c.data);if(b)for(var d of b)if(d&&d.oldColor&&4===d.oldColor.length&&d.newColor&&4===d.newColor.length){const [l,
n,p,q]=d.oldColor,[r,g,h,k]=d.newColor;if(l!==r||n!==g||p!==h||q!==k)for(b=0;b<c.length;b+=4)l===c[b]&&n===c[b+1]&&p===c[b+2]&&q===c[b+3]&&(c[b]=r,c[b+1]=g,c[b+2]=h,c[b+3]=k)}for(b=0;b<c.length;b+=4)d=c[b+3]/255,c[b]*=d,c[b+1]*=d,c[b+2]*=d;e=c;d=a;b=f;if(512<=d||512<=b){e=d/b;1<e?(d=512,b=Math.round(512/e)):(b=512,d=Math.round(512*e));e=new Uint8Array(4*d*b);const l=new Uint8ClampedArray(e.buffer);z.resampleHermite(c,a,f,l,d,b,!1)}return{size:[d,b],image:new Uint32Array(e.buffer),sdf:!1,simplePattern:!1,
anchorX:0,anchorY:0}};return x}()});