// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.25/esri/copyright.txt for details.
//>>built
define("../../chunks/_rollupPluginBabelHelpers ../../chunks/tslib.es6 ../../assets ../../config ../../Graphic ../../PopupTemplate ../../symbols ../../core/Accessor ../../core/Collection ../../core/Error ../../core/Evented ../../core/Handles ../../core/Logger ../../core/maybe ../../core/promiseUtils ../../core/reactiveUtils ../../core/accessorSupport/decorators/property ../../core/arrayUtils ../../core/accessorSupport/ensureType ../../core/accessorSupport/decorators/subclass ../../geometry/Point ../../geometry/SpatialReference ../../intl/locale ../../intl/messages ../../portal/Portal ../../views/support/layerViewUtils ./LayerSearchSource ./LocatorSearchSource ./SearchSource ./support/geometryUtils ./support/locatorUtils ../support/geolocationUtils ../support/GoTo ../../symbols/TextSymbol ../../symbols/PictureMarkerSymbol ../../symbols/SimpleLineSymbol ../../symbols/SimpleFillSymbol".split(" "),
function(p,h,S,T,L,M,g,U,V,r,W,X,Y,w,y,E,k,ra,sa,Z,N,aa,ba,ca,O,da,x,P,ea,K,z,F,fa,ha,ia,ja,ka){function n(t,u){return t.hasOwnProperty(u)&&null!=t[u]&&""!==t[u]}const q=Y.getLogger("esri.widgets.Search.SearchViewModel"),G=V.ofType({key:t=>t.layer?"layer":"locator",base:ea,typeMap:{layer:x,locator:P}}),Q=aa.WGS84,la=/<(?:.|\s)*?>/g;g=function(t){function u(a){a=t.call(this,a)||this;a._handles=new X;a._gotoController=null;a._searching=null;a._createdFeatureLayers=[];a.autoNavigate=!0;a.autoSelect=
!0;a.defaultPopupTemplate=null;a.defaultSources=new G;a.defaultSymbols={point:new ia({url:S.getAssetUrl("esri/images/search/search-symbol-32.png"),size:24,width:24,height:24}),polyline:new ja({color:[130,130,130,1],width:2}),polygon:new ka({color:[235,235,235,.4],outline:{color:[130,130,130,1],width:2}})};a.includeDefaultSources=!0;a.maxInputLength=128;a.maxResults=6;a.maxSuggestions=6;a.messages=null;a.minSuggestCharacters=3;a.popupEnabled=!0;a.popupTemplate=null;a.portal=O.getDefault();a.resultCount=
null;a.resultGraphicEnabled=!0;a.resultGraphic=null;a.results=null;a.selectedSuggestion=null;a.searchAllEnabled=!0;a.selectedResult=null;a.sources=new G;a.suggestionDelay=350;a.suggestionCount=null;a.suggestions=null;a.suggestionsEnabled=!0;a.view=null;return a}p._inheritsLoose(u,t);var f=u.prototype;f.initialize=function(){var a=this;const b=function(){var c=p._asyncToGenerator(function*(){const d=yield ca.fetchMessageBundle("esri/widgets/Search/t9n/Search");a.messages=d;a.defaultPopupTemplate=new M({title:d.searchResult,
content:"{Match_addr}"})});return function(){return c.apply(this,arguments)}}();b();this._handles.add([E.watch(()=>[this.includeDefaultSources,this.view,this.portal],()=>this._update(),E.initial),ba.onLocaleChange(b)])};f.destroy=function(){this._destroyFeatureLayers();this._abortGoTo();this.clearGraphics();this._handles.destroy();this._handles=null};f.clear=function(){this.searchTerm=""};f.clearGraphics=function(){this._removeHighlight();this._closePopup();this.view&&this.view.graphics.remove(this.resultGraphic);
this._set("resultGraphic",null)};f.search=function(a,b){this.emit("search-start");this.clearGraphics();const c=this._createSuggestionForSearch(a);return this._searching=a=this.when().then(()=>this._getResultsFromSources(c,b).then(d=>{if(w.unwrap(b?.signal)?.aborted)return null;const e={activeSourceIndex:this.activeSourceIndex,searchTerm:c.text,numResults:0,numErrors:0,errors:[],results:[]};this._formatResponse(e,d,c);d=this._getFirstResult(e.results);const l=(c.location&&d?d.name:c.text).replace(la,
"");this._set("searchTerm",l);(c.key&&"number"===typeof c.sourceIndex||c.location)&&this._set("selectedSuggestion",c);this._set("results",e.results);this._set("resultCount",e.results.reduce((m,v)=>m+v.results.length,0));this.emit("search-complete",e);return this._selectFirstResult(d).then(()=>e)})).then(d=>{this._clearSearching();return d},d=>{this._clearSearching();throw d;})};f.searchNearby=function(a){if(!this.locationEnabled){var b=new r("searchNearby:geolocation-unsupported","Geolocation API is unsupported.",
{geolocation:navigator.geolocation});q.error(b);return Promise.reject(b)}this._searching=b=F.getCurrentPosition().then(c=>F.positionToPoint({position:c,view:this.view},a)).then(c=>this.search(c,a));b.catch(()=>{}).then(()=>this._clearSearching());return b};f.select=function(a){this.clearGraphics();if(!a){var b=new r("select:missing-parameter","Cannot select without a searchResult.",{searchResult:a});q.error(b);return Promise.reject(b)}const {view:c}=this,d=n(a,"sourceIndex")?a.sourceIndex:this._getSourceIndexOfResult(a),
e=this.allSources.at(d);if(!e)return b=new r("select:missing-source","Cannot select without a source.",{source:e}),q.error(b),Promise.reject(b);b=e instanceof x?this._getLayerSourcePopupTemplate(e):e.popupTemplate;const l=e.resultSymbol||this._getDefaultSymbol(a),m=n(e,"resultGraphicEnabled")?e.resultGraphicEnabled:this.resultGraphicEnabled,v=n(e,"autoNavigate")?e.autoNavigate:this.autoNavigate,H=n(e,"popupEnabled")?e.popupEnabled:this.popupEnabled,ma=H?b||this.popupTemplate||this.defaultPopupTemplate:
null,{feature:A}=a;if(!A)return b=new r("select:missing-feature","Cannot select without a feature.",{feature:A}),q.error(b),Promise.reject(b);const {attributes:na,geometry:R,layer:oa,sourceLayer:pa}=A,I=K.getPointFromGeometry(R);b={layerViewQuery:this._getLayerView(A),elevationQuery:c&&w.isSome(I)?K.getPointWithElevation(I,c).catch(()=>I):Promise.resolve(I)};return y.eachAlways(b).then(B=>{const C=B.layerViewQuery.value,qa=B.elevationQuery.value;l instanceof ha&&(l.text=a.name);B=c&&v?a.target||a.extent:
null;return(w.isSome(B)?this._goToSearchResult(B):Promise.resolve()).then(()=>{const D=C?A:new L({geometry:R,symbol:l,attributes:na,layer:oa,sourceLayer:pa,popupTemplate:ma});var J=H&&this.view?.popup;(J=J&&D.getEffectivePopupTemplate(J.defaultPopupTemplateEnabled))&&c.popup.open({features:[D],location:qa});C&&da.highlightsSupported(C)&&!J&&this._highlightFeature({graphic:D,layerView:C});!C&&m&&c&&c.graphics.push(D);this._setResultFloor(a);this._set("selectedResult",a);this._set("resultGraphic",D);
this.emit("select-result",{result:a,source:e,sourceIndex:d});return a})})};f.suggest=function(a,b,c){const d=a||this.searchTerm;this.emit("suggest-start",{searchTerm:d});return this._suggestTimer(b,c).then(()=>this._suggestImmediate(d,c).then(e=>{this._set("suggestions",e.results);this._set("suggestionCount",e.results.reduce((l,m)=>l+m.results.length,0));this.emit("suggest-complete",e);return e}))};f.when=function(){var a=p._asyncToGenerator(function*(){yield E.whenOnce(()=>!this.updating)});return function(){return a.apply(this,
arguments)}}();f._update=function(){var a=p._asyncToGenerator(function*(){const {portal:b,view:c}=this;if(this.includeDefaultSources){const d=this._updatingPromise=y.eachAlways([b?.load(),c?.when()]);if(this.destroyed)return;yield d;if(d!==this._updatingPromise)return}yield E.whenOnce(()=>this.messages);this.destroyed||this._updateDefaultSources();this._updatingPromise=null});return function(){return a.apply(this,arguments)}}();f._clearSearching=function(){this._searching=null};f._convertHelperServices=
function(){const a=this.portal?.helperServices?.geocode;return a?a.map(b=>{if(!1!==b.placefinding){var c=T.apiKey&&z.isArcGISWorldGeocoder(b.url)?{url:z.meteredArcGISLocatorUrl}:null;b=P.fromJSON({...b,...c});c=b.url;(z.isArcGISWorldGeocoder(c)||z.isProxiedArcGISWorldGeocoder(c)||z.isMeteredArcGISWorldGeocoder(c))&&b.set({singleLineFieldName:"SingleLine",outFields:b.outFields||["Addr_type","Match_addr","StAddr","City"],placeholder:b.placeholder||this.messages.placeholder,defaultZoomScale:"number"===
typeof b.defaultZoomScale?b.defaultZoomScale:2500});if(b.singleLineFieldName)return b}}).filter(Boolean):[]};f._destroyFeatureLayers=function(){this._createdFeatureLayers.forEach(a=>a?.destroy());this._createdFeatureLayers=[]};f._getLayerSources=function(a,b){const c=this.view?.map;return a.map(d=>{const e=c.findLayerById(d.id);if(e){d=this._getLayerJSON(d);var l=x.fromJSON(d);l.placeholder=b;this._getLayer(e,d).then(m=>{l.layer=m});return l}}).filter(Boolean).toArray()};f._getTableSources=function(a,
b){const c=this.view?.map;return a.map(d=>{const e=c.findTableById(d.id);if(e){d=this._getLayerJSON(d);var l=x.fromJSON(d);l.placeholder=b;this._getLayer(e,d).then(m=>{l.layer=m});return l}}).filter(Boolean).toArray()};f._convertApplicationProperties=function(){var a=this.view?.map?.applicationProperties?.viewing?.search;if(!a)return[];const {enabled:b,hintText:c,layers:d,tables:e}=a;if(!b)return[];a=this._getLayerSources(d,c);const l=this._getTableSources(e,c);return[...a,...l]};f._getSubLayer=function(){var a=
p._asyncToGenerator(function*(b,c){yield b.load();if(!b.allSublayers)throw Error();b=b.allSublayers.find(d=>d.id===c.subLayer);if(!b)throw Error();b=yield b.createFeatureLayer();this._createdFeatureLayers.push(b);return b});return function(b,c){return a.apply(this,arguments)}}();f._getBuildingSubLayer=function(){var a=p._asyncToGenerator(function*(b,c){yield b.load();b=b.allSublayers.find(d=>d.id===c.subLayer);if("building-component"!==b?.type)throw Error();yield b.load();if(null==b.associatedLayer)throw Error();
yield b.associatedLayer.load();return b});return function(b,c){return a.apply(this,arguments)}}();f._getLayer=function(a,b){return"feature"===a.type||"scene"===a.type||"csv"===a.type||"geojson"===a.type||"ogc-feature"===a.type?Promise.resolve(a):"map-image"===a.type?this._getSubLayer(a,b).catch(()=>{const c=new r("search:create-featurelayer","Could not create a FeatureLayer from the MapImageLayer",{layer:a});q.error(c);return null}):"building-scene"===a.type?this._getBuildingSubLayer(a,b):Promise.resolve(null)};
f._getLayerJSON=function(a){return"function"===typeof a.toJSON?a.toJSON():a};f._updateDefaultSources=function(){const {defaultSources:a,includeDefaultSources:b}=this;this._destroyFeatureLayers();a.removeAll();b&&a.addMany([...this._convertApplicationProperties(),...this._convertHelperServices()])};f._abortGoTo=function(){this._gotoController&&this._gotoController.abort();this._gotoController=null};f._clear=function(){this._abortGoTo();this._set("resultCount",null);this._set("results",null);this._set("suggestions",
null);this._set("suggestionCount",null);this._set("selectedResult",null);this._set("selectedSuggestion",null);this.emit("search-clear")};f._closePopup=function(){const a=this.view?.popup,{resultGraphic:b}=this;if(a&&b){var {selectedFeature:c}=a;c&&c===b&&a.close()}};f._suggestTimer=function(a,b){return y.after(null!=a?a:this.suggestionDelay,null,b&&b.signal)};f._createLocationForSearch=function(a){return a instanceof L?K.getPointFromGeometry(a.geometry):a instanceof N?a:Array.isArray(a)&&2===a.length?
new N({longitude:a[0],latitude:a[1]}):null};f._createSuggestionForSearch=function(a){if(a&&n(a,"key")&&n(a,"text")&&n(a,"sourceIndex"))return a;const b=this._createLocationForSearch(a),c="string"===typeof a?a:this.searchTerm,{selectedSuggestion:d,selectedResult:e}=this,l=(a=!a&&d&&e)&&d.location;return a&&d.key===e.key&&d.sourceIndex===e.sourceIndex||l?d:{location:w.unwrap(b),text:b?"":c,sourceIndex:null,key:null}};f._getFirstResult=function(a){let b=null;a&&a.some(c=>{({results:c}=c);c=c[0];const d=
!!c;d&&(b=c);return d});return b};f._selectFirstResult=function(a){return this.autoSelect&&a?this.select(a):Promise.resolve(null)};f._suggestImmediate=function(a,b){return this.when().then(()=>this._getSuggestionsFromSources(a,b)).then(c=>{if(w.unwrap(b?.signal)?.aborted)return null;const d={activeSourceIndex:this.activeSourceIndex,searchTerm:a,numResults:0,numErrors:0,errors:[],results:[]};this._formatResponse(d,c);return d})};f._formatSourceResponse=function(a,b,c){const d=b&&b.value||[];b=b&&b.error;
const e=this.allSources.at(c);b?(a.errors.push({sourceIndex:c,source:e,error:b}),q.error(b),a.numErrors++):(a.results.push({sourceIndex:c,source:e,results:d}),a.numResults+=d.length)};f._formatResponse=function(a,b,c){if(b)if(-1===a.activeSourceIndex){const d=c&&n(c,"sourceIndex")&&-1!==c.sourceIndex?c.sourceIndex:void 0;b.forEach((e,l)=>{this._formatSourceResponse(a,e,void 0!==d?d:l)})}else this._formatSourceResponse(a,b[0],a.activeSourceIndex)};f._getResultsFromSources=function(a,b){var {allSources:c}=
this;const d=!a.location&&n(a,"sourceIndex")?a.sourceIndex:this.activeSourceIndex,e=[];if(!c.length)return c=new r("search:no-sources-defined","At least one source is required.",{allSources:c}),q.error(c),Promise.reject(c);-1===d?c.forEach((l,m)=>{e.push(this._getResultsFromSource(a,m,b))}):e.push(this._getResultsFromSource(a,d,b));return y.eachAlways(e)};f._getSuggestionsFromSources=function(a,b){const {allSources:c,activeSourceIndex:d}=this,e=[];if(!c.length){const l=new r("suggest:no-sources-defined",
"At least one source is required.",{allSources:c});q.error(l);return Promise.reject(l)}-1===d?c.forEach((l,m)=>{e.push(this._getSuggestionsFromSource(a,m,b))}):e.push(this._getSuggestionsFromSource(a,d,b));return y.eachAlways(e)};f._getResultsFromSource=function(a,b,c){const d=this.allSources.at(b),{location:e=null}=a,l=this.view?.spatialReference||Q,m=n(d,"maxResults")?d.maxResults:this.maxResults,v=d instanceof x&&n(d,"exactMatch")?d.exactMatch:!1,{view:H}=this;return d.getResults({view:H,sourceIndex:b,
location:e,suggestResult:a,spatialReference:l,exactMatch:v,maxResults:m},c)};f._getSuggestionsFromSource=function(a,b,c){const d=this.allSources.at(b);var e=n(d,"suggestionsEnabled")?d.suggestionsEnabled:this.suggestionsEnabled,l=a.length,m=n(d,"minSuggestCharacters")?d.minSuggestCharacters:this.minSuggestCharacters;if(e&&a.trim()&&l>=m){e=this.view?.spatialReference||Q;l=n(d,"maxSuggestions")?d.maxSuggestions:this.maxSuggestions;({view:m}=this);const v=d instanceof x&&n(d,"exactMatch")?d.exactMatch:
!1;return d.getSuggestions({view:m,sourceIndex:b,suggestTerm:a,spatialReference:e,maxSuggestions:l,exactMatch:v},c)}return Promise.resolve(null)};f._getLayerSourcePopupTemplate=function(a){const {layer:b}=a;if(b)return n(a,"popupTemplate")?a.popupTemplate:b.popupTemplate};f._getSourceIndexOfResult=function(a){let b=null;this.results.some(c=>c.results.some(d=>d===a?(b=c.sourceIndex,!0):!1));return b};f._goToSearchResult=function(){var a=p._asyncToGenerator(function*(b){const c=!!b;this._abortGoTo();
const d=new AbortController;this._gotoController=d;yield this.callGoTo({target:{target:b},options:{animate:c,signal:d.signal}});this._gotoController=null});return function(b){return a.apply(this,arguments)}}();f._getDefaultSymbol=function(a){const {defaultSymbols:b}=this;a=a.feature?.geometry;if(w.isNone(a))return null;switch(a.type){case "point":case "multipoint":return b.point;case "polyline":return b.polyline;case "extent":case "polygon":return b.polygon;default:return null}};f._removeHighlight=
function(){this._handles.remove("highlight")};f._getLayerView=function(){var a=p._asyncToGenerator(function*(b){const {view:c}=this;if(!b||!c||"building-component"===b.layer.type||"subtype-sublayer"===b.layer.type)return null;({layer:b}=b);yield c.when();return c.whenLayerView(b)});return function(b){return a.apply(this,arguments)}}();f._highlightFeature=function(a){const {graphic:b,layerView:c}=a,{attributes:d,layer:e}=b;({objectIdField:a}=e);a=c.highlight(d&&d[a]||b);this._handles.add(a,"highlight")};
f._setResultFloor=function(a){const {view:b}=this;var c=a.feature?.attributes;(a=a.feature?.sourceLayer)&&"floorInfo"in a&&a?.floorInfo?.floorField&&c&&(c=c[a.floorInfo.floorField],b?.emit("select-result-floor",c))};p._createClass(u,[{key:"activeSource",get:function(){return this.allSources.at(this.activeSourceIndex)??null}},{key:"activeSourceIndex",get:function(){return 1!==this.allSources.length&&this.searchAllEnabled?-1:0},set:function(a){this._overrideIfSome("activeSourceIndex",a)}},{key:"allPlaceholder",
get:function(){return this.messages?.allPlaceholder},set:function(a){this._overrideIfSome("allPlaceholder",a)}},{key:"allSources",get:function(){const {sources:a,defaultSources:b,includeDefaultSources:c}=this,d="function"===typeof c?c.call(null,{sources:a,defaultSources:b}):c?b.concat(a):a,e=this._get("allSources")||new G;e.removeAll();e.addMany(d.filter(Boolean));return e}},{key:"locationEnabled",get:function(){return this._get("locationEnabled")||F.supported()},set:function(a){if(void 0===a)this._clearOverride("locationEnabled");
else{var b=F.supported();if(a&&!b){const c=new r("locationEnabled:geolocation-unsupported","Geolocation API is unsupported.",{geolocation:navigator.geolocation});q.error(c)}this._override("locationEnabled",!!a&&b)}}},{key:"placeholder",get:function(){const {allSources:a,activeSourceIndex:b,allPlaceholder:c}=this;if(-1===b)return c;const d=a.at(b);return d?d.placeholder:""}},{key:"searchTerm",get:function(){return this._get("searchTerm")||""},set:function(a){this._set("searchTerm",a||"");this.clearGraphics();
this.selectedSuggestion&&this.selectedSuggestion.text!==a&&this._set("selectedSuggestion",null);""===a&&this._clear()}},{key:"state",get:function(){return this._searching?"searching":this.updating?"loading":0===this.allSources.length?"disabled":"ready"}},{key:"updating",get:function(){return null!=this._updatingPromise}}]);return u}(fa.GoToMixin(W.EventedMixin(U)));g.ALL_INDEX=-1;h.__decorate([k.property()],g.prototype,"_searching",void 0);h.__decorate([k.property()],g.prototype,"_updatingPromise",
void 0);h.__decorate([k.property({readOnly:!0,value:null})],g.prototype,"activeSource",null);h.__decorate([k.property()],g.prototype,"activeSourceIndex",null);h.__decorate([k.property()],g.prototype,"allPlaceholder",null);h.__decorate([k.property({readOnly:!0})],g.prototype,"allSources",null);h.__decorate([k.property()],g.prototype,"autoNavigate",void 0);h.__decorate([k.property()],g.prototype,"autoSelect",void 0);h.__decorate([k.property()],g.prototype,"defaultPopupTemplate",void 0);h.__decorate([k.property({readOnly:!0})],
g.prototype,"defaultSources",void 0);h.__decorate([k.property()],g.prototype,"defaultSymbols",void 0);h.__decorate([k.property()],g.prototype,"includeDefaultSources",void 0);h.__decorate([k.property()],g.prototype,"locationEnabled",null);h.__decorate([k.property()],g.prototype,"maxInputLength",void 0);h.__decorate([k.property()],g.prototype,"maxResults",void 0);h.__decorate([k.property()],g.prototype,"maxSuggestions",void 0);h.__decorate([k.property()],g.prototype,"messages",void 0);h.__decorate([k.property()],
g.prototype,"minSuggestCharacters",void 0);h.__decorate([k.property({readOnly:!0})],g.prototype,"placeholder",null);h.__decorate([k.property()],g.prototype,"popupEnabled",void 0);h.__decorate([k.property({type:M})],g.prototype,"popupTemplate",void 0);h.__decorate([k.property({type:O})],g.prototype,"portal",void 0);h.__decorate([k.property()],g.prototype,"resultCount",void 0);h.__decorate([k.property()],g.prototype,"resultGraphicEnabled",void 0);h.__decorate([k.property({readOnly:!0})],g.prototype,
"resultGraphic",void 0);h.__decorate([k.property({readOnly:!0})],g.prototype,"results",void 0);h.__decorate([k.property({readOnly:!0})],g.prototype,"selectedSuggestion",void 0);h.__decorate([k.property()],g.prototype,"searchAllEnabled",void 0);h.__decorate([k.property({readOnly:!0})],g.prototype,"selectedResult",void 0);h.__decorate([k.property()],g.prototype,"searchTerm",null);h.__decorate([k.property({type:G})],g.prototype,"sources",void 0);h.__decorate([k.property({readOnly:!0})],g.prototype,"state",
null);h.__decorate([k.property()],g.prototype,"suggestionDelay",void 0);h.__decorate([k.property()],g.prototype,"suggestionCount",void 0);h.__decorate([k.property({readOnly:!0})],g.prototype,"suggestions",void 0);h.__decorate([k.property()],g.prototype,"suggestionsEnabled",void 0);h.__decorate([k.property({readOnly:!0})],g.prototype,"updating",null);h.__decorate([k.property()],g.prototype,"view",void 0);h.__decorate([k.property()],g.prototype,"clear",null);return g=h.__decorate([Z.subclass("esri.widgets.Search.SearchViewModel")],
g)});