// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.25/esri/copyright.txt for details.
//>>built
define("../../../chunks/_rollupPluginBabelHelpers ../../../chunks/tslib.es6 ../../../core/Accessor ../../../core/maybe ../../../core/accessorSupport/decorators/property ../../../core/arrayUtils ../../../core/accessorSupport/ensureType ../../../core/accessorSupport/decorators/subclass ../../../properties/defaultUnit ./AnalysisView3D ./interfaces ./DirectLineMeasurement/DirectLineMeasurementController ./DirectLineMeasurement/DirectLineMeasurementVisualization".split(" "),function(g,b,a,f,c,u,v,m,n,
p,q,r,t){a=function(h){function e(d){d=h.call(this,d)||this;d.type="direct-line-measurement-view-3d";d.analysis=null;d.result=null;d.measurementMode=q.MeasurementMode.Auto;d.elevationAlignedStartPoint=null;d.elevationAlignedEndPoint=null;return d}g._inheritsLoose(e,h);var k=e.prototype;k.initialize=function(){const d=this.view,l=this.analysis;this._analysisVisualization=new t.DirectLineMeasurementVisualization({view:d,analysis:l,analysisView:this});this._analysisController=new r.DirectLineMeasurementController({view:d,
analysis:l,viewData:this})};k.destroy=function(){this._analysisController=f.destroyMaybe(this._analysisController);this._analysisVisualization=f.destroyMaybe(this._analysisVisualization)};g._createClass(e,[{key:"updating",get:function(){return!!this._analysisVisualization?.loadingMessages}},{key:"viewMode",get:function(){return this._analysisVisualization.viewMode}},{key:"actualVisualizedMeasurement",get:function(){return this._analysisVisualization.actualVisualizedMeasurement}},{key:"visualElementOrientation",
get:function(){return this._analysisVisualization.visualElementOrientation},set:function(d){this._analysisVisualization.visualElementOrientation=d}},{key:"allowVisualElementsOrientationChange",get:function(){return this._analysisVisualization.allowVisualElementsOrientationChange},set:function(d){this._analysisVisualization.allowVisualElementsOrientationChange=d}},{key:"triangleCollapseRatioThreshold",get:function(){return this._analysisVisualization.triangleCollapseRatioThreshold},set:function(d){this._analysisVisualization.triangleCollapseRatioThreshold=
d}},{key:"directLabelText",get:function(){return this._analysisVisualization.labels.direct.text}},{key:"horizontalLabelText",get:function(){return this._analysisVisualization.labels.horizontal.text}},{key:"verticalLabelText",get:function(){return this._analysisVisualization.labels.vertical.text}},{key:"unit",get:function(){return f.unwrapOr(this.analysis.unit,this._defaultUnit)}},{key:"testData",get:function(){return this.destroyed?{labels:null,stripeLength:null,visualization:null,controller:null}:
{...this._analysisVisualization?.testData,visualization:this._analysisVisualization,controller:this._analysisController}}}]);return e}(p.AnalysisView3D(a));b.__decorate([c.property()],a.prototype,"updating",null);b.__decorate([c.property({readOnly:!0})],a.prototype,"type",void 0);b.__decorate([c.property({constructOnly:!0,nonNullable:!0})],a.prototype,"analysis",void 0);b.__decorate([c.property()],a.prototype,"result",void 0);b.__decorate([c.property()],a.prototype,"measurementMode",void 0);b.__decorate([c.property()],
a.prototype,"elevationAlignedStartPoint",void 0);b.__decorate([c.property()],a.prototype,"elevationAlignedEndPoint",void 0);b.__decorate([c.property({readOnly:!0})],a.prototype,"viewMode",null);b.__decorate([c.property({readOnly:!0})],a.prototype,"actualVisualizedMeasurement",null);b.__decorate([c.property()],a.prototype,"visualElementOrientation",null);b.__decorate([c.property()],a.prototype,"allowVisualElementsOrientationChange",null);b.__decorate([c.property()],a.prototype,"triangleCollapseRatioThreshold",
null);b.__decorate([c.property({readOnly:!0})],a.prototype,"directLabelText",null);b.__decorate([c.property({readOnly:!0})],a.prototype,"horizontalLabelText",null);b.__decorate([c.property({readOnly:!0})],a.prototype,"verticalLabelText",null);b.__decorate([c.property()],a.prototype,"_analysisVisualization",void 0);b.__decorate([c.property()],a.prototype,"_analysisController",void 0);b.__decorate([c.property()],a.prototype,"unit",null);b.__decorate([c.property(n.defaultUnitPropertyMetadata)],a.prototype,
"_defaultUnit",void 0);return a=b.__decorate([m.subclass("esri.views.3d.analysis.DirectLineMeasurementAnalysisView3D")],a)});