// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.25/esri/copyright.txt for details.
//>>built
define("exports ../../chunks/_rollupPluginBabelHelpers ../../kernel ../../request ../../core/maybe ../../core/promiseUtils ../FeatureLayer ../../portal/Portal ../../portal/PortalItem".split(" "),function(n,e,u,l,g,m,p,v,w){let x=function(){function q(c,a,b,d){this._parsedUrl=c;this._portalItem=a;this._apiKey=b;this.signal=d;this._rootDocument=null;if(c=this._parsedUrl?.path.match(/^(.*)\/SceneServer\/layers\/([\d]*)\/?$/i))this._urlParts={root:c[1],layerId:parseInt(c[2],10)}}var f=q.prototype;f.fetch=
function(){var c=e._asyncToGenerator(function*(){if(!this._urlParts)return null;var a=this._portalItem??(yield this._portalItemFromServiceItemId());if(g.isNone(a))return this._loadFromUrl();a=yield this._findAndLoadRelatedPortalItem(a);return g.isNone(a)?null:this._loadFeatureLayerFromPortalItem(a)});return function(){return c.apply(this,arguments)}}();f.fetchPortalItem=function(){var c=e._asyncToGenerator(function*(){if(!this._urlParts)return null;const a=this._portalItem??(yield this._portalItemFromServiceItemId());
return g.isNone(a)?null:this._findAndLoadRelatedPortalItem(a)});return function(){return c.apply(this,arguments)}}();f._fetchRootDocument=function(){var c=e._asyncToGenerator(function*(){if(g.isSome(this._rootDocument))return this._rootDocument;if(g.isNone(this._urlParts))return this._rootDocument={},{};const a={query:{f:"json",token:this._apiKey},responseType:"json",signal:this.signal},b=`${this._urlParts.root}/SceneServer`;try{this._rootDocument=(yield l(b,a)).data}catch{this._rootDocument={}}return this._rootDocument});
return function(){return c.apply(this,arguments)}}();f._fetchServiceOwningPortalUrl=function(){var c=e._asyncToGenerator(function*(){var a=this._parsedUrl?.path;const b=a?u.id?.findServerInfo(a):null;if(b?.owningSystemUrl)return b.owningSystemUrl;a=a?a.replace(/(.*\/rest)\/.*/i,"$1")+"/info":null;try{const d=(yield l(a,{query:{f:"json"},responseType:"json",signal:this.signal})).data.owningSystemUrl;if(d)return d}catch(d){m.throwIfAbortError(d)}return null});return function(){return c.apply(this,arguments)}}();
f._findAndLoadRelatedPortalItem=function(){var c=e._asyncToGenerator(function*(a){try{return(yield a.fetchRelatedItems({relationshipType:"Service2Service",direction:"reverse"},{signal:this.signal})).find(b=>"Feature Service"===b.type)||null}catch(b){return m.throwIfAbortError(b),null}});return function(a){return c.apply(this,arguments)}}();f._loadFeatureLayerFromPortalItem=function(){var c=e._asyncToGenerator(function*(a){yield a.load({signal:this.signal});const b=yield this._findMatchingAssociatedSublayerUrl(a.url??
"");return(new p({url:b,portalItem:a})).load({signal:this.signal})});return function(a){return c.apply(this,arguments)}}();f._loadFromUrl=function(){var c=e._asyncToGenerator(function*(){const a=yield this._findMatchingAssociatedSublayerUrl(`${this._urlParts?.root}/FeatureServer`);return(new p({url:a})).load({signal:this.signal})});return function(){return c.apply(this,arguments)}}();f._findMatchingAssociatedSublayerUrl=function(){var c=e._asyncToGenerator(function*(a){a=a.replace(/^(.*FeatureServer)(\/[\d]*\/?)?$/i,
"$1");var b={query:{f:"json"},responseType:"json",authMode:"no-prompt",signal:this.signal};const d=this._urlParts?.layerId;var h=this._fetchRootDocument();b=l(a,b);const [r,t]=yield Promise.all([b,h]);h=t&&t.layers;b=r.data&&r.data.layers;if(!Array.isArray(b))throw Error("expected layers array");if(!Array.isArray(h)){if(null!=d&&d<b.length)return`${a}/${b[d].id}`}else for(let k=0;k<Math.min(h.length,b.length);k++)if(h[k].id===d)return`${a}/${b[k].id}`;throw Error("could not find matching associated sublayer");
});return function(a){return c.apply(this,arguments)}}();f._portalItemFromServiceItemId=function(){var c=e._asyncToGenerator(function*(){var a=(yield this._fetchRootDocument()).serviceItemId;if(!a)return null;a=new w({id:a,apiKey:this._apiKey});const b=yield this._fetchServiceOwningPortalUrl();g.isSome(b)&&(a.portal=new v({url:b}));try{return a.load({signal:this.signal})}catch(d){return m.throwIfAbortError(d),null}});return function(){return c.apply(this,arguments)}}();return q}();n.FetchAssociatedFeatureLayer=
x;Object.defineProperties(n,{__esModule:{value:!0},[Symbol.toStringTag]:{value:"Module"}})});