// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.25/esri/copyright.txt for details.
//>>built
define(["exports","../../core/arrayUtils","./spatialReferenceUtils"],function(l,y,z){function p(a,b){const c=b[0]-a[0],e=b[1]-a[1];return 2<a.length&&2<b.length?(a=a[2]-b[2],Math.sqrt(c*c+e*e+a*a)):Math.sqrt(c*c+e*e)}function q(a,b,c){const e=a[0]+c*(b[0]-a[0]),g=a[1]+c*(b[1]-a[1]);return 2<a.length&&2<b.length?[e,g,a[2]+c*(b[2]-a[2])]:[e,g]}function r(a,b,c,e){let g=c[0];c=c[1];let d=e[0]-g,f=e[1]-c;if(0!==d||0!==f){const h=((a-g)*d+(b-c)*f)/(d*d+f*f);1<h?(g=e[0],c=e[1]):0<h&&(g+=d*h,c+=f*h)}d=a-
g;f=b-c;return d*d+f*f}function t(a,b,c){const e=a.length;let g=0,d=0,f=0;for(let h=0;h<e;h++){const k=a[h],m=a[(h+1)%e];let n=2;g+=k[0]*m[1]-m[0]*k[1];2<k.length&&2<m.length&&c&&(d+=k[0]*m[2]-m[0]*k[2],n=3);k.length>n&&m.length>n&&b&&(f+=k[0]*m[n]-m[0]*k[n])}return 0>=g&&0>=d&&0>=f}function u(a){const b=a.length;return 2<b&&y.equals(a[0],a[b-1])}function v(a){if("rings"in a)for(const b of a.rings)u(b)||b.push(b[0].slice())}function w(a,b){var c=z.getInfo(b);if(c){b=c.valid[0];c=c.valid[1];var e=
c-b;for(const g of a){a=Infinity;let d=-Infinity;for(const f of g){const h=x(f[0],b,c);a=Math.min(a,h);d=Math.max(d,h);f[0]=h}a=d-a;e-a<a&&g.forEach(f=>{0>f[0]&&(f[0]+=e)})}}}function x(a,b,c){const e=c-b;return a<b?c-(b-a)%e:a>c?b+(a-b)%e:a}l.closeRings=v;l.closeRingsAndFixWinding=function(a){if("rings"in a&&(v(a),0<a.rings.length&&!t(a.rings[0],a.hasM??!1,a.hasZ??!1)))for(const b of a.rings)b.reverse()};l.distanceFromPointToPolygon=function(a,b,c){c=c.rings;let e=!1,g=Infinity,d,f;for(let h=0;h<
c.length;h++){const k=c[h];for(let m=0,n=k.length-1;m<k.length;n=m++)d=k[m],f=k[n],d[1]>b!==f[1]>b&&a<(f[0]-d[0])*(b-d[1])/(f[1]-d[1])+d[0]&&(e=!e),g=Math.min(g,r(a,b,d,f))}return 0===g?0:(e?1:-1)*Math.sqrt(g)};l.distanceToSegmentSquared=r;l.geometryToCoordinates=function(a){if(!a)return null;if(Array.isArray(a))return a;const b=a.hasZ,c=a.hasM;if("point"===a.type)return c&&b?[a.x,a.y,a.z,a.m]:b?[a.x,a.y,a.z]:c?[a.x,a.y,a.m]:[a.x,a.y];if("polygon"===a.type)return a.rings.slice(0);if("polyline"===
a.type)return a.paths.slice(0);if("multipoint"===a.type)return a.points.slice(0);if("extent"===a.type){a=a.clone().normalize();if(!a)return null;let e=!1,g=!1;a.forEach(d=>{d.hasZ&&(e=!0);d.hasM&&(g=!0)});return a.map(d=>{const f=[[d.xmin,d.ymin],[d.xmin,d.ymax],[d.xmax,d.ymax],[d.xmax,d.ymin],[d.xmin,d.ymin]];if(e&&d.hasZ){var h=.5*(d.zmax-d.zmin);for(let k=0;k<f.length;k++)f[k].push(h)}if(g&&d.hasM)for(d=.5*(d.mmax-d.mmin),h=0;h<f.length;h++)f[h].push(d);return f})}return null};l.getLength=p;l.getMidpoint=
function(a,b){return q(a,b,.5)};l.getPathLength=function(a){const b=a.length;let c=0;for(let e=0;e<b-1;++e)c+=p(a[e],a[e+1]);return c};l.getPointOnPath=function(a,b){if(0>=b)return a[0];const c=a.length;let e=0;for(let g=0;g<c-1;++g){const d=p(a[g],a[g+1]);if(b-e<d)return q(a[g],a[g+1],(b-e)/d);e+=d}return a[c-1]};l.getRingArea=function(a){if(!a||3>a.length)return 0;let b=0;const c=a.length-1;for(let e=0;e<c;e++)b+=(a[e][0]-a[e+1][0])*(a[e][1]+a[e+1][1]);b+=(a[c][0]-a[0][0])*(a[c][1]+a[0][1]);return-.5*
b};l.isClockwise=t;l.isClosed=u;l.projectPointOnLine=function(a,b,c,e){const [g,d]=b,[f,h]=c[e],[k,m]=c[e+1];b=k-f;c=m-h;e=Math.min(1,Math.max(0,((g-f)*b+(d-h)*c)/(b*b+c*c)));a[0]=f+b*e;a[1]=h+c*e;return a};l.unnormalizeGeometryOnDatelineCrossing=function(a){if("polygon"!==a.type&&"polyline"!==a.type)return a;w("polygon"===a.type?a.rings:a.paths,a.spatialReference);return a};l.unnormalizeVerticesOnDatelineCrossing=w;l.unnormalizedCoordinate=x;Object.defineProperties(l,{__esModule:{value:!0},[Symbol.toStringTag]:{value:"Module"}})});