// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.25/esri/copyright.txt for details.
//>>built
define("exports ../../core/maybe ../../core/PriorityQueue ./aaBoundingRect ./boundsUtils ./centroid ./coordsUtils ./intersectsBase".split(" "),function(J,N,O,D,H,M,K,P){function I(b,a){var {rings:d}=a;a=0;for(const g of d){d=g.length;for(let k=1;k<d;++k){const c=g[k-1],l=g[k];c[1]>b[1]!==l[1]>b[1]&&(0<(l[0]-c[0])*(b[1]-c[1])-(l[1]-c[1])*(b[0]-c[0])?a++:a--)}}return 0!==a}function G(b,a,d){if(d&&I(b,a))return{coord:b,distance:0};d=Infinity;let g=0,k=0;const c=[0,0];({rings:a}=a);for(const l of a)if(!(2>
l.length))for(a=0;a<l.length-1;a++){K.projectPointOnLine(c,b,l,a);const n=E(b,c);n<d&&(d=n,g=c[0],k=c[1])}return{coord:[g,k],distance:Math.sqrt(d)}}function L(b,a,d,g){d=[a,0];let k=Infinity,c=Infinity,l=!1,n=!1;a=[[a,g[1]-1],[a,g[3]+1]];g=[0,0];const m=[0,0],t=[0,0],p=[[0,0],[0,0]],r=D.create();({rings:b}=b);for(const A of b)if(!(2>A.length))for(b=1;b<A.length;b++){p[0][0]=A[b-1][0];p[0][1]=A[b-1][1];p[1][0]=A[b][0];p[1][1]=A[b][1];a:{var h=r;var e=p;if(2>e.length){h=null;break a}h||(h=D.create());
const [q,u]=e[0],[x,y]=e[1];h[0]=Math.min(q,x);h[1]=Math.min(u,y);h[2]=Math.max(q,x);h[3]=Math.max(u,y)}if(null!==h){m[0]=a[0][0];m[1]=a[0][1];t[0]=a[1][0];t[1]=a[1][1];a:{h=r;e=m;var f=t;let q=z(e,h),u=z(f,h);const x=h[0],y=h[1],B=h[2],C=h[3];if(q&u){h=0;break a}if(!(q|u)){h=4;break a}const Q=(q?1:0)|(u?2:0);do{const v=f[0]-e[0],w=f[1]-e[1];if(v>w)q&3?(q&1?(e[1]+=w*(x-e[0])/v,e[0]=x):(e[1]+=w*(B-e[0])/v,e[0]=B),q=z(e,h)):u&3?(u&1?(f[1]+=w*(x-f[0])/v,f[0]=x):(f[1]+=w*(B-f[0])/v,f[0]=B),u=z(f,h)):
q?(q&4?(e[0]+=v*(y-e[1])/w,e[1]=y):(e[0]+=v*(C-e[1])/w,e[1]=C),q=z(e,h)):(u&4?(f[0]+=v*(y-f[1])/w,f[1]=y):(f[0]+=v*(C-f[1])/w,f[1]=C),u=z(f,h));else if(q&12?(q&4?(e[0]+=v*(y-e[1])/w,e[1]=y):(e[0]+=v*(C-e[1])/w,e[1]=C),q=z(e,h)):u&12?(u&4?(f[0]+=v*(y-f[1])/w,f[1]=y):(f[0]+=v*(C-f[1])/w,f[1]=C),u=z(f,h)):q?(q&1?(e[1]+=w*(x-e[0])/v,e[0]=x):(e[1]+=w*(B-e[0])/v,e[0]=B),q=z(e,h)):(u&1?(f[1]+=w*(x-f[0])/v,f[0]=x):(f[1]+=w*(B-f[0])/v,f[0]=B),u=z(f,h)),q&u){h=0;break a}}while(q|u);h=Q}0!==h&&P.segmentIntersects(a[0],
a[1],p[0],p[1],g)&&(h=g[1],k>c?h<k&&(k=h,l=!0):h<c&&(c=h,n=!0))}}l&&n?d[1]=(k+c)/2:d[0]=d[1]=NaN;return d}function z(b,a){return(b[0]<a[0]?1:0)|(b[0]>a[2]?1:0)<<1|(b[1]<a[1]?1:0)<<2|(b[1]>a[3]?1:0)<<3}function E(b,a){return(b[0]-a[0])*(b[0]-a[0])+(b[1]-a[1])*(b[1]-a[1])}function R(b,a){if(b<a)return-1;if(b>a)return 1;if(b===a)return 0;b=isNaN(b);a=isNaN(a);return b<a?-1:b>a?1:0}let F=function(b,a,d,g){this.x=b;this.y=a;this.cellSize=d;this.distancefromCellCenter=K.distanceFromPointToPolygon(b,a,g);
this.maxDistanceToPolygon=this.distancefromCellCenter+this.cellSize*Math.SQRT2};J.getLabelPoint=function(b){var {rings:a}=b;if(!a||0===a.length)return null;var d=H.getBoundsXY(D.create(),b);if(!d)return null;var g=8.8818E-14*(Math.abs(d[0])+Math.abs(d[2])+Math.abs(d[1])+Math.abs(d[3])+1),k=0,c=0;for(var l=0;l<a.length;l++){var n=K.getRingArea(a[l]);n>c&&(c=n,k=l)}if(Math.abs(c)<=2*g*g)return c=H.getPointsBounds(D.create(),a[k]),[(c[0]+c[2])/2,(c[1]+c[3])/2];var m=M.ringCentroid(a[k],!1,D.create());
if(null===m)return null;if(1===a.length&&4>a[0].length)return m;c=[[NaN,NaN],[NaN,NaN],[NaN,NaN],[NaN,NaN]];l=[NaN,NaN,NaN,NaN];n=[NaN,NaN,NaN,NaN];var t=!1,p=G(m,b,!0);0===p.distance&&(t=!0,c[0][0]=m[0],c[0][1]=m[1],p=G(m,b,!1));l[0]=p.distance;n[0]=0;var r=[NaN,NaN],h=!1;let e=.25,f=-1;a=H.getPointsBounds(D.create(),a[k]);k=NaN;do if(k=NaN,p=a[0],c[1]=L(b,p+(a[2]-p)*e,g,d),isNaN(c[1][0])||isNaN(c[1][1])||(p=G(c[1],b,!1),k=p.distance),!isNaN(k)&&k>g&&I(c[1],b))h=!0,l[1]=k,n[1]=E(c[1],m);else if(!isNaN(k)&&
k>f&&(f=k,r[0]=c[1][0],r[1]=c[1][1]),e-=.01,.1>e)if(0<=f)h=!0,l[1]=f,c[1][0]=r[0],c[1][1]=r[1],n[1]=E(c[1],m);else break;while(!h);h=!1;e=.5;f=-1;let A=.01,q=1;do if(k=NaN,p=a[0],c[2]=L(b,p+(a[2]-p)*e,g,d),isNaN(c[2][0])||isNaN(c[2][1])||(p=G(c[2],b,!1),k=p.distance),!isNaN(k)&&k>g&&I(c[2],b))h=!0,l[2]=k,n[2]=E(c[2],m);else if(!isNaN(k)&&k>f)f=k,r[0]=c[2][0],r[1]=c[2][1];else if(k>f&&(f=k,r[0]=c[2][0],r[1]=c[2][1]),e=.5+A*q,A+=.01,q*=-1,.3>e||.7<e)if(0<=f)h=!0,l[2]=f,c[2][0]=r[0],c[2][1]=r[1],n[2]=
E(c[2],m);else break;while(!h);h=!1;e=.75;f=-1;do if(k=NaN,p=a[0],c[3]=L(b,p+(a[2]-p)*e,g,d),isNaN(c[3][0])||isNaN(c[3][1])||(p=G(c[3],b,!1),k=p.distance),!isNaN(k)&&k>g&&I(c[3],b))h=!0,l[3]=k,n[3]=E(c[3],m);else if(k>f&&(f=k,r[0]=c[3][0],r[1]=c[3][1]),e+=.01,.9<e)if(0<=f)h=!0,l[3]=f,c[3][0]=r[0],c[3][1]=r[1],n[3]=E(c[3],m);else break;while(!h);b=[0,1,2,3];d=t?0:1;for(t=d;4>t;t++)for(m=d;3>m;m++)r=n[m],h=n[m+1],0<R(r,h)&&(g=b[m],b[m]=b[m+1],b[m+1]=g,n[m]=h,n[m+1]=r);n=d;for(t=g=0;4>d;d++){switch(d){case 0:t=
2*l[b[d]];break;case 1:t=1.66666666*l[b[d]];break;case 2:t=1.33333333*l[b[d]];break;case 3:t=l[b[d]]}t>g&&(g=t,n=b[d])}return c[n]};J.getPolylabelPoint=function(b){if(!b||!b.rings||0===b.rings.length)return null;var a=H.getPointsBounds(D.create(),b.rings[0]);if(!a)return null;var d=a[2]-a[0],g=a[3]-a[1];if(0===d||0===g)return[a[0]+d/2,a[1]+g/2];const k=Math.max(Math.min(d,g)/100,1),c=new O((m,t)=>t.maxDistanceToPolygon-m.maxDistanceToPolygon);g=Math.min(d,g);d=g/2;let l=0,n=0;for(l=a[0];l<a[2];l+=
g)for(n=a[1];n<a[3];n+=g)c.enqueue(new F(l+d,n+d,d,b));a=M.ringsCentroid(b.rings,!1);if(null===a)return null;for(a=new F(a[0],a[1],0,b);0<c.size;)g=N.unwrap(c.dequeue()),g.distancefromCellCenter>a.distancefromCellCenter&&(a=g),g.maxDistanceToPolygon-a.distancefromCellCenter<=k||(d=g.cellSize/2,c.enqueue(new F(g.x-d,g.y-d,d,b)),c.enqueue(new F(g.x+d,g.y-d,d,b)),c.enqueue(new F(g.x-d,g.y+d,d,b)),c.enqueue(new F(g.x+d,g.y+d,d,b)));return[a.x,a.y]};Object.defineProperties(J,{__esModule:{value:!0},[Symbol.toStringTag]:{value:"Module"}})});