// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.25/esri/copyright.txt for details.
//>>built
define("exports ../../../../core/compilerUtils ../../../../core/mathUtils ../../../../core/maybe ../../../../chunks/mat4 ../../../../chunks/mat4f64 ../../../../chunks/vec3 ../../../../chunks/vec3f64 ../../../../geometry/projectionEllipsoid ../../../../chunks/sphere ./common ./ConstraintTypes ./InteractionType ./TiltMode ../../state/utils/viewUtils".split(" "),function(v,C,k,L,M,N,h,D,E,w,l,F,x,t,q){function G(c,a,b=l.defaultConstraintOptions,d=!0){r.eyeCenterDistance=0;r.requiresTwoSteps=!1;const f=
y(c,a,b,void 0,r);if(0===f)return!1;M.fromRotation(u,-f,a.viewRight);switch(b.tiltMode){case t.TiltMode.LOOK_AROUND:h.transformMat4(m,a.viewForward,u);h.scale(m,m,r.eyeCenterDistance);a.center=h.add(n,a.eye,m);break;case t.TiltMode.TUMBLE:h.subtract(m,a.center,a.eye);h.transformMat4(m,m,u);a.eye=h.subtract(n,a.center,m);break;default:C.neverReached(b.tiltMode)}a.up=h.transformMat4(n,a.up,u);return r.requiresTwoSteps&&d?G(c,a,b,!1):!0}function y(c,a,b=l.defaultConstraintOptions,d=l.defaultConstraintOptions,
f){if(!c.state.constraints.tilt)return 0;var e=c.state.constraints.tilt(a.distance,O);if(b.interactionType!==x.InteractionType.NONE){var {interactionStartCamera:p,interactionFactor:H}=b,{min:P,max:Q}=e,g=y(c,p,l.defaultConstraintOptions,b),I=0===g?0:q.viewAngle(c.renderCoordsHelper,p.center,p.eye);e.min=P;e.max=Q;b.interactionType===x.InteractionType.TUMBLE?(l.hasConstraintType(b.selection,F.ConstraintTypes.ALTITUDE)&&J(c,p,e),l.adjustRangeForInteraction(g,I,!0,H,K,e)):l.adjustRangeForInteraction(g,
I,!1,H,K,e)}d.interactionType===x.InteractionType.TUMBLE&&l.hasConstraintType(d.selection,F.ConstraintTypes.ALTITUDE)&&J(c,d.interactionStartCamera,e);if(b.tiltMode===t.TiltMode.LOOK_AROUND||d.tiltMode===t.TiltMode.LOOK_AROUND){a:switch(f&&(f.requiresTwoSteps=!1),c.viewingMode){case "global":b=R;g=c.pointsOfInterest.centerOnSurfaceFrequent.estimatedSurfaceAltitude;d=g+E.getReferenceEllipsoid(c.spatialReference).radius;g=c.renderCoordsHelper.intersectManifold(a.ray,g,n);b.eyeCenterDistance=a.distance;
b.centerIsOnSurface=!1;L.isSome(g)?(b.eyeCenterDistance=h.distance(a.eye,g),b.tiltAtCenter=q.viewAngle(c.renderCoordsHelper,g,a.eye),b.centerIsOnSurface=!0):c.state.isLocal?b.tiltAtCenter=q.viewAngle(c.renderCoordsHelper,a.center,a.eye):(w.closestPointOnSilhouette(w.fromRadius(w.tmpSphere,d),a.ray,n),b.eyeCenterDistance=h.distance(a.eye,n),b.tiltAtCenter=k.acosClamped(-h.dot(a.viewForward,h.normalize(n,n))));b.radius=d;b.eyeRadius=h.length(a.eye);b.constraints=c.state.constraints;a=k.clamp(b.tiltAtCenter,
e.min,e.max);if(1E-9<Math.abs(b.tiltAtCenter-a)){if(b.centerIsOnSurface){{const {constraints:z,eyeCenterDistance:S,tiltAtCenter:A}=b;a=A;c=z.clampTilt(S,A);e=B(b,c);if(z.clampTilt(e,A)!==c)for(e=0;10>e&&1E-9<Math.abs(c-a);)d=(a+c)/2,g=B(b,d),g=z.clampTilt(g,d),1E-9<Math.abs(g-d)?a=d:c=d,e++;a=c}e=a;c=k.asinClamped(b.radius/b.eyeRadius*Math.sin(b.tiltAtCenter));e=k.asinClamped(b.radius/b.eyeRadius*Math.sin(e));c=b.eyeRadius>b.radius?c-e:e-c}else a=b.constraints.clampTilt(b.eyeCenterDistance,b.tiltAtCenter),
f&&a<Math.PI/2&&(f.requiresTwoSteps=!0,a=Math.PI/2-1E-5),c=b.tiltAtCenter-Math.PI/2-(a-Math.PI/2);f&&(f.eyeCenterDistance=B(b,a));f=c}else f=0;break a;case "local":d=q.viewAngle(c.renderCoordsHelper,a.center,a.eye);b=k.clamp(d,e.min,e.max);e=d-b;1E-9<Math.abs(e)?(f&&(d=c.pointsOfInterest.centerOnSurfaceFrequent.estimatedSurfaceAltitude,c=c.renderCoordsHelper.getAltitude(a.eye)-d,b=Math.cos(b),f.eyeCenterDistance=1E-4<Math.abs(b)?c/b:a.distance),f=e):f=0;break a;default:C.neverReached(c.viewingMode),
f=void 0}return f}f=q.viewAngle(c.renderCoordsHelper,a.center,a.eye);b=k.clamp(f,e.min,e.max);f-=b;f=1E-9<Math.abs(f)?f:0;return f}function B(c,a){if(!c.centerIsOnSurface)return c.eyeCenterDistance;a=Math.PI-k.clamp(a,0,Math.PI);const b=k.asinClamped(c.radius/c.eyeRadius*Math.sin(a)),d=Math.sin(Math.PI-a-b)/Math.sin(a);return c.eyeRadius<c.radius&&1<d?Math.sin(Math.PI-a-(Math.PI-b))/Math.sin(a)*c.eyeRadius:d*c.eyeRadius}function J(c,a,b){if(!c.state.isLocal){var d=c.state.constraints;if(d.altitude){var f=
h.squaredLength(a.center),e=Math.sqrt(f);a=a.distance;var p=E.getReferenceEllipsoid(c.spatialReference).radius;c=d.altitude.min+p;d=d.altitude.max+p;c=(c*c-a*a-f)/(-2*e*a);b.min=Math.max(b.min,Math.min(Math.PI-k.acosClamped((d*d-a*a-f)/(-2*e*a)),b.max));b.max=Math.min(b.max,Math.PI-k.acosClamped(c))}}}const m=D.create(),u=N.create(),n=D.create(),K=k.deg2rad(5),O={min:0,max:0},R={constraints:null,radius:0,eyeRadius:0,centerIsOnSurface:!0,eyeCenterDistance:0,tiltAtCenter:0},r={eyeCenterDistance:0,requiresTwoSteps:!1};
v.applyTiltConstraint=G;v.getTiltConstraintError=y;Object.defineProperties(v,{__esModule:{value:!0},[Symbol.toStringTag]:{value:"Module"}})});