// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.25/esri/copyright.txt for details.
//>>built
define("exports ../../chunks/_rollupPluginBabelHelpers ../../core/Error ../../layers/support/lazyLayerLoader ../PortalItem ./layersLoader ./portalItemUtils ../../support/requestPresets".split(" "),function(k,l,v,w,q,e,h,f){function r(a){switch(a.type){case "Map Service":return x(a);case "Feature Service":return y(a);case "Feature Collection":return z(a);case "Scene Service":return A(a);case "Image Service":return B(a);case "Stream Service":return{className:"StreamLayer"};case "Vector Tile Service":return{className:"VectorTileLayer"};
case "GeoJson":return{className:"GeoJSONLayer"};case "CSV":return{className:"CSVLayer"};case "KML":return{className:"KMLLayer"};case "WFS":return{className:"WFSLayer"};case "WMTS":return{className:"WMTSLayer"};case "WMS":return{className:"WMSLayer"};case "Feed":return{className:"StreamLayer"};default:return Promise.reject(new v("portal:unknown-item-type","Unknown item type '${type}'",{type:a.type}))}}function C(a){return(0,w.layerLookupMap[a.className])().then(b=>({constructor:b,properties:a.properties}))}
function x(a){return D(a).then(b=>b?{className:"TileLayer"}:{className:"MapImageLayer"})}function y(a){return h.hasTypeKeyword(a,"Oriented Imagery Layer")?E(a):t(a).then(b=>{if("object"===typeof b){const c={};null!=b.id&&(c.layerId=b.id);return{className:b.className||"FeatureLayer",properties:c}}return{className:"GroupLayer"}})}function A(a){return t(a).then(b=>{if("object"===typeof b){const c={};null!=b.id?(c.layerId=b.id,b=`${a.url}/layers/${b.id}`):b=a.url;if(Array.isArray(a.typeKeywords)&&0<a.typeKeywords.length){const d=
{IntegratedMesh:"IntegratedMeshLayer","3DObject":"SceneLayer",Point:"SceneLayer",PointCloud:"PointCloudLayer",Building:"BuildingSceneLayer"};for(const g of Object.keys(d))if(a.typeKeywords.includes(g))return{className:d[g]}}return f.requestArcGISServiceJSON(b).then(d=>{let g="SceneLayer";const u={Point:"SceneLayer","3DObject":"SceneLayer",IntegratedMesh:"IntegratedMeshLayer",PointCloud:"PointCloudLayer",Building:"BuildingSceneLayer"};d&&d.layerType&&u[d.layerType]&&(g=u[d.layerType]);return{className:g,
properties:c}})}return!1===b?f.requestArcGISServiceJSON(a.url).then(c=>"Voxel"===c?.layerType?{className:"VoxelLayer"}:{className:"GroupLayer"}):{className:"GroupLayer"}})}function z(a){return m.apply(this,arguments)}function m(){m=l._asyncToGenerator(function*(a){yield a.load();const b=h.hasTypeKeyword(a,"Map Notes"),c=h.hasTypeKeyword(a,"Markup");if(b||c)return{className:"MapNotesLayer"};if(h.hasTypeKeyword(a,"Route Layer"))return{className:"RouteLayer"};a=yield a.fetchData();return 1===e.getNumLayersAndTables(a)?
{className:"FeatureLayer"}:{className:"GroupLayer"}});return m.apply(this,arguments)}function B(a){return n.apply(this,arguments)}function n(){n=l._asyncToGenerator(function*(a){yield a.load();var b=a.typeKeywords?.map(c=>c.toLowerCase())??[];if(b.includes("elevation 3d layer"))return{className:"ElevationLayer"};if(b.includes("tiled imagery"))return{className:"ImageryTileLayer"};b=(yield a.fetchData())?.layerType;if("ArcGISTiledImageServiceLayer"===b)return{className:"ImageryTileLayer"};if("ArcGISImageServiceLayer"===
b)return{className:"ImageryLayer"};b=yield f.requestArcGISServiceJSON(a.url);a=b.cacheType?.toLowerCase();b=b.capabilities?.toLowerCase().includes("tilesonly");return"map"===a||b?{className:"ImageryTileLayer"}:{className:"ImageryLayer"}});return n.apply(this,arguments)}function E(a){return a.load().then(()=>a.fetchData()).then(b=>b.coverage?{className:"GroupLayer"}:{className:"OrientedImageryLayer",properties:b})}function D(a){return f.requestArcGISServiceJSON(a.url).then(b=>b.tileInfo)}function t(a){return!a.url||
a.url.match(/\/\d+$/)?Promise.resolve({}):a.load().then(()=>a.fetchData()).then(function(){var b=l._asyncToGenerator(function*(c){if("Feature Service"===a.type){var d=yield e.preprocessFSItemData(c,a.url);d=p(d);"object"===typeof d&&(c=e.getSubtypeGroupLayerIds(c),d.className=c.includes(d.id)?"SubtypeGroupLayer":"FeatureLayer");return d}return 0<e.getNumLayersAndTables(c)?p(c):f.requestArcGISServiceJSON(a.url).then(p)});return function(c){return b.apply(this,arguments)}}())}function p(a){return 1===
e.getNumLayersAndTables(a)?{id:e.getFirstLayerOrTableId(a)}:!1}k.fromItem=function(a){!a.portalItem||a.portalItem instanceof q||(a={...a,portalItem:new q(a.portalItem)});return a.portalItem.load().then(r).then(C).then(b=>new b.constructor({portalItem:a.portalItem,...b.properties}))};k.selectLayerClassPath=r;Object.defineProperties(k,{__esModule:{value:!0},[Symbol.toStringTag]:{value:"Module"}})});