// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.25/esri/copyright.txt for details.
//>>built
define("../../chunks/_rollupPluginBabelHelpers ../../chunks/tslib.es6 ../../Graphic ../../PopupTemplate ../../symbols ../../core/Clonable ../../core/JSONSupport ../../core/maybe ../../core/accessorSupport/decorators/property ../../core/arrayUtils ../../core/accessorSupport/ensureType ../../core/accessorSupport/decorators/subclass ../../geometry/Polyline ./networkEnums".split(" "),function(l,c,m,n,p,b,q,e,d,u,v,r,t,f){var h;b=h=function(k){function g(a){a=k.call(this,a)||this;a.directionLineType=null;
a.directionPointId=null;a.distance=null;a.duration=null;a.fromLevel=null;a.geometry=null;a.objectId=null;a.popupTemplate=null;a.symbol=null;a.toLevel=null;a.type="direction-line";return a}l._inheritsLoose(g,k);g.fromGraphic=function(a){return new h({directionLineType:f.directionLineTypeJsonMap.fromJSON(a.attributes.DirectionLineType),directionPointId:a.attributes.DirectionPointID,distance:a.attributes.Meters,duration:a.attributes.Minutes,fromLevel:a.attributes.FromLevel??null,geometry:a.geometry,
objectId:a.attributes.ObjectID??a.attributes.__OBJECTID,popupTemplate:a.popupTemplate,symbol:a.symbol,toLevel:a.attributes.ToLevel??null})};g.prototype.toGraphic=function(){const a={ObjectID:e.unwrap(this.objectId),DirectionLineType:e.isSome(this.directionLineType)?f.directionLineTypeJsonMap.toJSON(this.directionLineType):null,DirectionPointID:e.unwrap(this.directionPointId),Meters:e.unwrap(this.distance),Minutes:e.unwrap(this.duration)};e.isSome(this.fromLevel)&&(a.FromLevel=this.fromLevel);e.isSome(this.toLevel)&&
(a.ToLevel=this.toLevel);return new m({geometry:this.geometry,attributes:a,symbol:this.symbol,popupTemplate:this.popupTemplate})};return g}(b.ClonableMixin(q.JSONSupport));b.fields=[{name:"ObjectID",alias:"ObjectID",type:"esriFieldTypeOID",editable:!1,nullable:!1,domain:null},{name:"DirectionLineType",alias:"Line Type",type:"esriFieldTypeInteger",editable:!0,nullable:!0,visible:!0,domain:{type:"codedValue",name:"esriDirectionsLineType",codedValues:[{name:"Unknown",code:0},{name:"Segment",code:1},
{name:"Maneuver Segment",code:2},{name:"Restriction violation",code:3},{name:"Scale cost barrier crossing",code:4},{name:"Heavy Traffic",code:5},{name:"Slow Traffic",code:6},{name:"Moderate Traffic",code:7}]}},{name:"DirectionPointID",alias:"Direction Point ID",type:"esriFieldTypeInteger",editable:!0,nullable:!0,visible:!1},{name:"FromLevel",alias:"Start from 3D Level",type:"esriFieldTypeInteger",editable:!0,nullable:!0,visible:!1},{name:"Meters",alias:"Length in Meters",type:"esriFieldTypeDouble",
editable:!0,nullable:!0,visible:!0},{name:"Minutes",alias:"Duration in Minutes",type:"esriFieldTypeDouble",editable:!0,nullable:!0,visible:!0},{name:"ToLevel",alias:"End at 3D Level",type:"esriFieldTypeInteger",editable:!0,nullable:!0,visible:!1}];b.popupInfo={title:"Direction Lines",fieldInfos:[{fieldName:"DirectionLineType",label:"Line Type",isEditable:!1,tooltip:"",visible:!0,stringFieldOption:"textbox"},{fieldName:"Meters",label:"Length in Meters",isEditable:!1,tooltip:"",visible:!0,format:{places:2,
digitSeparator:!0},stringFieldOption:"textbox"},{fieldName:"Minutes",label:"Duration in Minutes",isEditable:!1,tooltip:"",visible:!0,format:{places:2,digitSeparator:!0},stringFieldOption:"textbox"},{fieldName:"DirectionPointID",label:"Direction Point ID",isEditable:!1,tooltip:"",visible:!0,format:{places:0,digitSeparator:!0},stringFieldOption:"textbox"},{fieldName:"FromLevel",label:"Start from 3D Level",isEditable:!1,tooltip:"",visible:!1,format:{places:0,digitSeparator:!0},stringFieldOption:"textbox"},
{fieldName:"ToLevel",label:"End at 3D Level",isEditable:!1,tooltip:"",visible:!1,format:{places:0,digitSeparator:!0},stringFieldOption:"textbox"}],description:null,showAttachments:!1,mediaInfos:[]};c.__decorate([d.property({type:f.directionLineTypeJsonMap.apiValues,json:{read:{source:"attributes.DirectionLineType",reader:f.directionLineTypeJsonMap.read}}})],b.prototype,"directionLineType",void 0);c.__decorate([d.property({json:{read:{source:"attributes.DirectionPointID"}}})],b.prototype,"directionPointId",
void 0);c.__decorate([d.property({json:{read:{source:"attributes.Meters"}}})],b.prototype,"distance",void 0);c.__decorate([d.property({json:{read:{source:"attributes.Minutes"}}})],b.prototype,"duration",void 0);c.__decorate([d.property({json:{read:{source:"attributes.FromLevel"}}})],b.prototype,"fromLevel",void 0);c.__decorate([d.property({type:t})],b.prototype,"geometry",void 0);c.__decorate([d.property({json:{read:{source:"attributes.ObjectID"}}})],b.prototype,"objectId",void 0);c.__decorate([d.property({type:n})],
b.prototype,"popupTemplate",void 0);c.__decorate([d.property({types:p.symbolTypes})],b.prototype,"symbol",void 0);c.__decorate([d.property({json:{read:{source:"attributes.ToLevel"}}})],b.prototype,"toLevel",void 0);c.__decorate([d.property({readOnly:!0,json:{read:!1}})],b.prototype,"type",void 0);return b=h=c.__decorate([r.subclass("esri.rest.support.DirectionLine")],b)});