// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.25/esri/copyright.txt for details.
//>>built
define(["require","exports","../../chunks/_rollupPluginBabelHelpers"],function(e,h,f){const g=a=>Object.freeze(Object.defineProperty({__proto__:null,default:a},Symbol.toStringTag,{value:"Module"})),k={ArcGISAnnotationLayer:()=>Promise.resolve(null),ArcGISDimensionLayer:function(){var a=f._asyncToGenerator(function*(){return(yield new Promise((b,c)=>e(["../DimensionLayer"],d=>b(g(d)),c))).default});return function(){return a.apply(this,arguments)}}(),ArcGISFeatureLayer:function(){var a=f._asyncToGenerator(function*(){return(yield new Promise((b,
c)=>e(["../FeatureLayer"],d=>b(g(d)),c))).default});return function(){return a.apply(this,arguments)}}(),ArcGISImageServiceLayer:function(){var a=f._asyncToGenerator(function*(){return(yield new Promise((b,c)=>e(["../ImageryLayer"],d=>b(g(d)),c))).default});return function(){return a.apply(this,arguments)}}(),ArcGISImageServiceVectorLayer:()=>Promise.resolve(null),ArcGISMapServiceLayer:function(){var a=f._asyncToGenerator(function*(){return(yield new Promise((b,c)=>e(["../MapImageLayer"],d=>b(g(d)),
c))).default});return function(){return a.apply(this,arguments)}}(),ArcGISSceneServiceLayer:function(){var a=f._asyncToGenerator(function*(){return(yield new Promise((b,c)=>e(["../SceneLayer"],d=>b(g(d)),c))).default});return function(){return a.apply(this,arguments)}}(),ArcGISStreamLayer:function(){var a=f._asyncToGenerator(function*(){return(yield new Promise((b,c)=>e(["../StreamLayer"],d=>b(g(d)),c))).default});return function(){return a.apply(this,arguments)}}(),ArcGISTiledElevationServiceLayer:function(){var a=
f._asyncToGenerator(function*(){return(yield new Promise((b,c)=>e(["../ElevationLayer"],d=>b(g(d)),c))).default});return function(){return a.apply(this,arguments)}}(),ArcGISTiledImageServiceLayer:function(){var a=f._asyncToGenerator(function*(){return(yield new Promise((b,c)=>e(["../ImageryTileLayer"],d=>b(g(d)),c))).default});return function(){return a.apply(this,arguments)}}(),ArcGISTiledMapServiceLayer:function(){var a=f._asyncToGenerator(function*(){return(yield new Promise((b,c)=>e(["../TileLayer"],
d=>b(g(d)),c))).default});return function(){return a.apply(this,arguments)}}(),BingMapsAerial:function(){var a=f._asyncToGenerator(function*(){return(yield new Promise((b,c)=>e(["../BingMapsLayer"],d=>b(g(d)),c))).default});return function(){return a.apply(this,arguments)}}(),BingMapsRoad:function(){var a=f._asyncToGenerator(function*(){return(yield new Promise((b,c)=>e(["../BingMapsLayer"],d=>b(g(d)),c))).default});return function(){return a.apply(this,arguments)}}(),BingMapsHybrid:function(){var a=
f._asyncToGenerator(function*(){return(yield new Promise((b,c)=>e(["../BingMapsLayer"],d=>b(g(d)),c))).default});return function(){return a.apply(this,arguments)}}(),BuildingSceneLayer:function(){var a=f._asyncToGenerator(function*(){return(yield new Promise((b,c)=>e(["../BuildingSceneLayer"],d=>b(g(d)),c))).default});return function(){return a.apply(this,arguments)}}(),CSV:function(){var a=f._asyncToGenerator(function*(){return(yield new Promise((b,c)=>e(["../CSVLayer"],d=>b(g(d)),c))).default});
return function(){return a.apply(this,arguments)}}(),GeoRSS:function(){var a=f._asyncToGenerator(function*(){return(yield new Promise((b,c)=>e(["../GeoRSSLayer"],d=>b(g(d)),c))).default});return function(){return a.apply(this,arguments)}}(),GeoJSON:function(){var a=f._asyncToGenerator(function*(){return(yield new Promise((b,c)=>e(["../GeoJSONLayer"],d=>b(g(d)),c))).default});return function(){return a.apply(this,arguments)}}(),GroupLayer:function(){var a=f._asyncToGenerator(function*(){return(yield new Promise((b,
c)=>e(["../GroupLayer"],d=>b(g(d)),c))).default});return function(){return a.apply(this,arguments)}}(),IntegratedMeshLayer:function(){var a=f._asyncToGenerator(function*(){return(yield new Promise((b,c)=>e(["../IntegratedMeshLayer"],d=>b(g(d)),c))).default});return function(){return a.apply(this,arguments)}}(),KML:function(){var a=f._asyncToGenerator(function*(){return(yield new Promise((b,c)=>e(["../KMLLayer"],d=>b(g(d)),c))).default});return function(){return a.apply(this,arguments)}}(),LineOfSightLayer:function(){var a=
f._asyncToGenerator(function*(){return(yield new Promise((b,c)=>e(["../LineOfSightLayer"],d=>b(g(d)),c))).default});return function(){return a.apply(this,arguments)}}(),OGCFeatureLayer:function(){var a=f._asyncToGenerator(function*(){return(yield new Promise((b,c)=>e(["../OGCFeatureLayer"],d=>b(g(d)),c))).default});return function(){return a.apply(this,arguments)}}(),OpenStreetMap:function(){var a=f._asyncToGenerator(function*(){return(yield new Promise((b,c)=>e(["../OpenStreetMapLayer"],d=>b(g(d)),
c))).default});return function(){return a.apply(this,arguments)}}(),OrientedImageryLayer:function(){var a=f._asyncToGenerator(function*(){return(yield new Promise((b,c)=>e(["../OrientedImageryLayer"],d=>b(g(d)),c))).default});return function(){return a.apply(this,arguments)}}(),PointCloudLayer:function(){var a=f._asyncToGenerator(function*(){return(yield new Promise((b,c)=>e(["../PointCloudLayer"],d=>b(g(d)),c))).default});return function(){return a.apply(this,arguments)}}(),VectorTileLayer:function(){var a=
f._asyncToGenerator(function*(){return(yield new Promise((b,c)=>e(["../VectorTileLayer"],d=>b(g(d)),c))).default});return function(){return a.apply(this,arguments)}}(),Voxel:function(){var a=f._asyncToGenerator(function*(){return(yield new Promise((b,c)=>e(["../VoxelLayer"],d=>b(g(d)),c))).default});return function(){return a.apply(this,arguments)}}(),WebTiledLayer:function(){var a=f._asyncToGenerator(function*(){return(yield new Promise((b,c)=>e(["../WebTileLayer"],d=>b(g(d)),c))).default});return function(){return a.apply(this,
arguments)}}(),WFS:function(){var a=f._asyncToGenerator(function*(){return(yield new Promise((b,c)=>e(["../WFSLayer"],d=>b(g(d)),c))).default});return function(){return a.apply(this,arguments)}}(),SubtypeGroupLayer:function(){var a=f._asyncToGenerator(function*(){return(yield new Promise((b,c)=>e(["../SubtypeGroupLayer"],d=>b(g(d)),c))).default});return function(){return a.apply(this,arguments)}}(),WMS:function(){var a=f._asyncToGenerator(function*(){return(yield new Promise((b,c)=>e(["../WMSLayer"],
d=>b(g(d)),c))).default});return function(){return a.apply(this,arguments)}}(),RasterDataLayer:()=>Promise.resolve(null),RasterDataElevationLayer:()=>Promise.resolve(null)};h.typeModuleMap=k;Object.defineProperties(h,{__esModule:{value:!0},[Symbol.toStringTag]:{value:"Module"}})});