/*
All material copyright ESRI, All Rights Reserved, unless otherwise specified.
See https://js.arcgis.com/4.25/esri/copyright.txt for details.
*/
import{j as e,h as t}from"../widgets/Widget.js";
/*!
 * All material copyright ESRI, All Rights Reserved, unless otherwise specified.
 * See https://github.com/Esri/calcite-components/blob/master/LICENSE.md for details.
 * v1.0.0-beta.97
 */function n(e){return"checked"in e}const o=new WeakMap,a=new WeakSet;function r(e){const{formEl:t}=e;return!!t&&("requestSubmit"in t?t.requestSubmit():t.submit(),!0)}function d(e){var t;null===(t=e.formEl)||void 0===t||t.reset()}function s(t){const{el:r,value:d}=t,s=e(r,"form");if(!s||function(e,t){const n="calciteInternalFormComponentRegister";let o=!1;return e.addEventListener(n,(e=>{o=e.composedPath().some((e=>a.has(e))),e.stopPropagation()}),{once:!0}),t.dispatchEvent(new CustomEvent(n,{bubbles:!0,composed:!0})),o}(s,r))return;t.formEl=s,t.defaultValue=d,n(t)&&(t.defaultChecked=t.checked);const c=(t.onFormReset||u).bind(t);s.addEventListener("reset",c),o.set(t.el,c),a.add(r)}function u(){n(this)?this.checked=this.defaultChecked:this.value=this.defaultValue}function c(e){const{el:t,formEl:n}=e;if(!n)return;const r=o.get(t);n.removeEventListener("reset",r),o.delete(t),e.formEl=null,a.delete(t)}function l(e,t){e.defaultValue=t}const i=e=>{e.target.dispatchEvent(new CustomEvent("calciteInternalHiddenInputChange",{bubbles:!0}))},f=e=>e.removeEventListener("change",i);function m(e,t,o){var a;const{defaultValue:r,disabled:d,name:s,required:u}=e;t.defaultValue=r,t.disabled=d,t.name=s,t.required=u,t.tabIndex=-1,n(e)?(t.defaultChecked=e.defaultChecked,t.value=e.checked?o||"on":"",d||e.checked||(t.disabled=!0)):t.value=o||"",null===(a=e.syncHiddenFormInput)||void 0===a||a.call(e,t)}const h=({component:e})=>(function(e){const{el:t,formEl:n,name:o,value:a}=e,{ownerDocument:r}=t,d=t.querySelectorAll('input[slot="hidden-form-input"]');if(!n||!o)return void d.forEach((e=>{f(e),e.remove()}));const s=Array.isArray(a)?a:[a],u=[],c=new Set;let l;d.forEach((t=>{const n=s.find((e=>e==t.value));null!=n?(c.add(n),m(e,t,n)):u.push(t)})),s.forEach((t=>{if(c.has(t))return;let n=u.pop();n||(n=r.createElement("input"),n.slot="hidden-form-input"),l||(l=r.createDocumentFragment()),l.append(n),n.addEventListener("change",i),m(e,n,t)})),l&&t.append(l),u.forEach((e=>{f(e),e.remove()}))}(e),t("slot",{name:"hidden-form-input"}));export{h as H,l as a,s as c,c as d,d as r,r as s};
