// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.25/esri/copyright.txt for details.
//>>built
define("../../../chunks/_rollupPluginBabelHelpers ../../../chunks/tslib.es6 ../../../intl ../../../core/accessorSupport/decorators/property ../../../core/arrayUtils ../../../core/accessorSupport/ensureType ../../../core/accessorSupport/decorators/subclass ../../Widget ./support/relationshipUtils ./support/univariateUtils ../support/styleUtils ../../support/Heading ../../support/widgetUtils ../../support/decorators/messageBundle ../../support/jsxFactory ../../../intl/number".split(" "),function(E,
w,u,y,N,O,F,G,H,p,m,I,P,J,b,K){const C={display:"flex",alignItems:"flex-start"},z={marginLeft:"3px"},v={display:"table-cell",verticalAlign:"middle"};u=function(D){function A(a,c){a=D.call(this,a,c)||this;a.activeLayerInfos=null;a.headingLevel=3;a.messages=null;a.type="classic";return a}E._inheritsLoose(A,D);var q=A.prototype;q.render=function(){var a=this.activeLayerInfos;a=a&&a.toArray().map(c=>this._renderLegendForLayer(c)).filter(c=>!!c);return b.tsx("div",null,a&&a.length?a:b.tsx("div",{class:"esri-legend__message"},
this.messages.noLegend))};q._renderLegendForLayer=function(a){if(!a.ready)return null;var c=!!a.children.length;const d=`${"esri-legend__"}${a.layer.uid}-version-${a.version}`,f=a.title?I.Heading({level:this.headingLevel,class:this.classes("esri-widget__heading","esri-legend__service-label")},a.title):null;if(c)return c=a.children.map(e=>this._renderLegendForLayer(e)).toArray(),b.tsx("div",{key:d,class:this.classes("esri-legend__service","esri-legend__group-layer")},f,c);if((c=a.legendElements)&&
!c.length)return null;c=c.map(e=>this._renderLegendForElement(e,a.layer,a.effectList)).filter(e=>!!e);return c.length?b.tsx("div",{key:d,class:this.classes("esri-legend__service",{["esri-legend__group-layer-child"]:!!a.parent}),tabIndex:0},f,b.tsx("div",{class:"esri-legend__layer"},c)):null};q._renderLegendForElement=function(a,c,d,f){var e="color-ramp"===a.type,g="opacity-ramp"===a.type;const k="size-ramp"===a.type;let l=null;if("symbol-table"===a.type||k){var h=a.infos.map(x=>this._renderLegendForElementInfo(x,
c,d,k,a.legendType)).filter(x=>!!x);h.length&&(l=b.tsx("div",{class:"esri-legend__layer-body"},h))}else"color-ramp"===a.type||"opacity-ramp"===a.type||"heatmap-ramp"===a.type||"stretch-ramp"===a.type?l=this._renderLegendForRamp(a,c.opacity):"relationship-ramp"===a.type?l=H.renderRelationshipRamp(a,this.id,c.opacity,d):"pie-chart-ramp"===a.type?l=this._renderPieChartRamp(a):"univariate-above-and-below-ramp"===a.type?l=this._renderUnivariateAboveAndBelowRamp(a,c.opacity,d):"univariate-color-size-ramp"===
a.type&&(l=this._renderUnivariateColorSizeRamp(a,c.opacity,d));if(!l)return null;h=a.title;var n=null;"string"===typeof h?n=h:h&&(n=m.getTitle(this.messages,h,e||g),n=m.isRendererTitle(h,e||g)&&h.title?`${h.title} (${n})`:n);e=f?"esri-legend__layer-child-table":"esri-legend__layer-table";g=n?b.tsx("div",{class:"esri-legend__layer-caption"},n):null;return b.tsx("div",{class:this.classes(e,{["esri-legend__layer-table--size-ramp"]:k||!f})},g,l)};q._renderPieChartRamp=function(a){return b.tsx("div",{bind:a.preview,
afterCreate:m.attachToNode})};q._renderUnivariateAboveAndBelowRamp=function(a,c,d){const {sizeRampElement:f,colorRampElement:e}=p.getUnivariateAboveAndBelowRampElements(a,c);if(!f)return null;var g=p.getUnivariateColorRampSize(f,"above",!0);a=p.getUnivariateColorRampSize(f,"below",!0);const k=p.getUnivariateColorRampPreview(e,{width:12,height:g,rampAlignment:"vertical",opacity:c,type:"above",effectList:d});c=p.getUnivariateColorRampPreview(e,{width:12,height:a,rampAlignment:"vertical",opacity:c,type:"below",
effectList:d});var l=p.getUnivariateColorRampMargin(f);const h=f.infos.map(t=>t.label);d=h.map((t,r)=>{const B=2===r;return 0===r?b.tsx("div",{key:r,class:t?k?"esri-univariate-above-and-below-ramp__label":"esri-legend__ramp-label":null},t):B?b.tsx("div",null):null});const n=h.length-1,x=Math.floor(h.length/2),L=h.map((t,r)=>{const B=r===n;return r===x||B?b.tsx("div",{key:r,class:t?k?"esri-univariate-above-and-below-ramp__label":"esri-legend__ramp-label":null},t):null}),M={display:"table-cell",verticalAlign:"middle"};
l={marginTop:`${l}px`};g={height:`${g}px`};a={height:`${a}px`};return b.tsx("div",{key:"univariate-above-and-below-ramp-preview",styles:C},b.tsx("div",{class:"esri-legend__layer-body"},f.infos.map((t,r)=>b.tsx("div",{class:this.classes("esri-legend__layer-row","esri-legend__size-ramp")},b.tsx("div",{class:"esri-legend__symbol",styles:M,bind:t.preview,afterCreate:m.attachToNode}),k||0!==r%2?null:b.tsx("div",{class:"esri-legend__layer-cell esri-legend__layer-cell--info"},h[r])))),k?b.tsx("div",{styles:l,
key:"color-ramp-preview"},b.tsx("div",{styles:z},b.tsx("div",{styles:v},b.tsx("div",{class:"esri-legend__ramps",bind:k,afterCreate:m.attachToNode})),b.tsx("div",{styles:v},b.tsx("div",{class:"esri-legend__ramp-labels",styles:g},d))),b.tsx("div",{styles:z},b.tsx("div",{styles:v},b.tsx("div",{class:"esri-legend__ramps",bind:c,afterCreate:m.attachToNode})),b.tsx("div",{styles:v},b.tsx("div",{class:"esri-legend__ramp-labels",styles:a},L)))):null)};q._renderUnivariateColorSizeRamp=function(a,c,d){const {sizeRampElement:f,
colorRampElement:e}=p.getUnivariateColorSizeRampElements(a);if(!f)return null;var g=p.getUnivariateColorRampMargin(f);a=p.getUnivariateColorRampSize(f,"full",!1);c=p.getUnivariateColorRampPreview(e,{width:12,height:a,rampAlignment:"vertical",opacity:c,type:"full",effectList:d});const k=f.infos.length-1;d=f.infos.map((h,n)=>0===n||n===k?b.tsx("div",{key:n,class:h.label?e?"esri-univariate-above-and-below-ramp__label":"esri-legend__ramp-label":null},h.label):null);const l={display:"table-cell",verticalAlign:"middle"};
g={marginTop:`${g}px`};a={height:`${a}px`};return b.tsx("div",{key:"univariate-above-and-below-ramp-preview",styles:C},b.tsx("div",{class:"esri-legend__layer-body"},f.infos.map(h=>b.tsx("div",{class:this.classes("esri-legend__layer-row","esri-legend__size-ramp")},b.tsx("div",{class:"esri-legend__symbol",styles:l,bind:h.preview,afterCreate:m.attachToNode})))),b.tsx("div",{styles:g,key:"color-ramp-preview"},b.tsx("div",{styles:z},b.tsx("div",{styles:v},b.tsx("div",{class:"esri-legend__ramps",bind:c,
afterCreate:m.attachToNode})),b.tsx("div",{styles:v},b.tsx("div",{class:"esri-legend__ramp-labels",styles:a},d)))))};q._renderLegendForRamp=function(a,c){const d=a.infos,f="heatmap-ramp"===a.type,e="stretch-ramp"===a.type,g=a.preview;g.className=`${"esri-legend__color-ramp"} ${"opacity-ramp"===a.type?"esri-legend__opacity-ramp":""}`;null!=c&&(g.style.opacity=c.toString());a=d.map(k=>b.tsx("div",{class:k.label?"esri-legend__ramp-label":null},f?this.messages[k.label]||k.label:e?this._getStretchStopLabel(k):
k.label));c={height:g.style.height};return b.tsx("div",{class:"esri-legend__layer-row"},b.tsx("div",{class:"esri-legend__layer-cell esri-legend__layer-cell--symbols",styles:{width:"24px"}},b.tsx("div",{class:"esri-legend__ramps",bind:g,afterCreate:m.attachToNode})),b.tsx("div",{class:"esri-legend__layer-cell esri-legend__layer-cell--info"},b.tsx("div",{class:"esri-legend__ramp-labels",styles:c},a)))};q._getStretchStopLabel=function(a){return a.label?this.messages[a.label]+": "+("string"===typeof a.value?
a.value:K.formatNumber(a.value,{style:"decimal",notation:a.value.toString().includes("e")?"scientific":"standard"})):""};q._renderLegendForElementInfo=function(a,c,d,f,e){if(a.type)return this._renderLegendForElement(a,c,d,!0);d=null;e=m.isImageryStretchedLegend(c,e);a.preview?d=b.tsx("div",{class:"esri-legend__symbol",bind:a.preview,afterCreate:m.attachToNode}):a.src&&(d=this._renderImage(a,c,e));if(!d)return null;c={["esri-legend__imagery-layer-info--stretched"]:e};return b.tsx("div",{class:"esri-legend__layer-row"},
b.tsx("div",{class:this.classes("esri-legend__layer-cell esri-legend__layer-cell--symbols",{["esri-legend__imagery-layer-info--stretched"]:e,["esri-legend__size-ramp"]:!e&&f})},d),b.tsx("div",{class:this.classes("esri-legend__layer-cell esri-legend__layer-cell--info",c)},m.getTitle(this.messages,a.label,!1)||""))};q._renderImage=function(a,c,d){const {label:f,src:e,opacity:g}=a;d={["esri-legend__imagery-layer-image--stretched"]:d,["esri-legend__symbol"]:!d};c={opacity:`${null!=g?g:c.opacity}`};return b.tsx("img",
{alt:m.getTitle(this.messages,f,!1),src:e,border:0,width:a.width,height:a.height,class:this.classes(d),styles:c})};return A}(G);w.__decorate([y.property()],u.prototype,"activeLayerInfos",void 0);w.__decorate([y.property()],u.prototype,"headingLevel",void 0);w.__decorate([y.property(),J.messageBundle("esri/widgets/Legend/t9n/Legend")],u.prototype,"messages",void 0);w.__decorate([y.property({readOnly:!0})],u.prototype,"type",void 0);return u=w.__decorate([F.subclass("esri.widgets.Legend.styles.Classic")],
u)});