// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.25/esri/copyright.txt for details.
//>>built
define(["./StyleDefinition","./StyleLayer"],function(l,m){return function(){function n(a){this._style=a;this.backgroundBucketIds=[];this._uidToLayer=new Map;this._layerByName={};this._runningId=0;a.layers||(a.layers=[]);this.version=parseFloat(a.version);if(this.layers=a.layers.map((b,c,f)=>this._create(b,c,f)).filter(b=>!!b))for(let b=0;b<this.layers.length;b++)a=this.layers[b],this._layerByName[a.id]=a,this._uidToLayer.set(a.uid,a),a.type===l.StyleLayerType.BACKGROUND&&this.backgroundBucketIds.push(a.id);
this._identifyRefLayers()}var h=n.prototype;h.isPainterDataDriven=function(a){return(a=this._layerByName[a])?a.isPainterDataDriven():!1};h.getStyleLayerId=function(a){return a>=this.layers.length?null:this.layers[a].id};h.getStyleLayerByUID=function(a){return this._uidToLayer.get(a)??null};h.getStyleLayerIndex=function(a){return(a=this._layerByName[a])?this.layers.indexOf(a):-1};h.setStyleLayer=function(a,b){if(a&&a.id){var c=this._style;null!=b&&b>=this.layers.length&&(b=this.layers.length-1);var f=
!0,d;if(d=this._layerByName[a.id]){const e=this.layers.indexOf(d);b||(b=e);b===e?(f=!1,d=n._recreateLayer(a,d),this.layers[b]=d,c.layers[b]=a):(this.layers.splice(e,1),c.layers.splice(e,1),d=this._create(a,b,this.layers),this.layers.splice(b,0,d),c.layers.splice(b,0,a))}else d=this._create(a,b,this.layers),!b||b>=this.layers.length?(this.layers.push(d),c.layers.push(a)):(this.layers.splice(b,0,d),c.layers.splice(b,0,a));this._layerByName[a.id]=d;this._uidToLayer.set(d.uid,d);f&&this._recomputeZValues();
this._identifyRefLayers()}};h.getStyleLayer=function(a){return(a=this._layerByName[a])?{type:a.typeName,id:a.id,source:a.source,"source-layer":a.sourceLayer,minzoom:a.minzoom,maxzoom:a.maxzoom,filter:a.filter,layout:a.layout,paint:a.paint}:null};h.deleteStyleLayer=function(a){const b=this._layerByName[a];b&&(delete this._layerByName[a],this._uidToLayer.delete(b.uid),a=this.layers.indexOf(b),this.layers.splice(a,1),this._style.layers.splice(a,1),this._recomputeZValues(),this._identifyRefLayers())};
h.getLayerById=function(a){return this._layerByName[a]};h.getLayoutProperties=function(a){return(a=this._layerByName[a])?a.layout:null};h.getPaintProperties=function(a){return(a=this._layerByName[a])?a.paint:null};h.setPaintProperties=function(a,b){if(a=this._layerByName[a]){var c=n._recreateLayer({type:a.typeName,id:a.id,source:a.source,"source-layer":a.sourceLayer,minzoom:a.minzoom,maxzoom:a.maxzoom,filter:a.filter,layout:a.layout,paint:b},a),f=this.layers.indexOf(a);this.layers[f]=c;this._style.layers[f].paint=
b;this._layerByName[a.id]=c;this._uidToLayer.set(a.uid,c)}};h.setLayoutProperties=function(a,b){if(a=this._layerByName[a]){var c=n._recreateLayer({type:a.typeName,id:a.id,source:a.source,"source-layer":a.sourceLayer,minzoom:a.minzoom,maxzoom:a.maxzoom,filter:a.filter,layout:b,paint:a.paint},a),f=this.layers.indexOf(a);this.layers[f]=c;this._style.layers[f].layout=b;this._layerByName[a.id]=c;this._uidToLayer.set(a.uid,c)}};h.setStyleLayerVisibility=function(a,b){if(a=this._layerByName[a]){var c=a.layout||
{};c.visibility=b;b=n._recreateLayer({type:a.typeName,id:a.id,source:a.source,"source-layer":a.sourceLayer,minzoom:a.minzoom,maxzoom:a.maxzoom,filter:a.filter,layout:c,paint:a.paint},a);var f=this.layers.indexOf(a);this.layers[f]=b;this._style.layers[f].layout=c;this._layerByName[a.id]=b;this._uidToLayer.set(a.uid,b)}};h.getStyleLayerVisibility=function(a){return(a=this._layerByName[a])?a.layout?.visibility??"visible":"none"};h._recomputeZValues=function(){const a=this.layers,b=1/(a.length+1);for(let c=
0;c<a.length;c++)a[c].z=1-(1+c)*b};h._identifyRefLayers=function(){const a=[],b=[];let c=0;for(const e of this.layers){const k=e.layout;if(e.type===l.StyleLayerType.FILL){var f=e,d=e.source+"|"+e.sourceLayer;d+="|"+(k?.visibility??"");d+="|"+e.minzoom;d+="|"+e.maxzoom;d+="|"+JSON.stringify(e.filter);if(f.hasDataDrivenFill||f.hasDataDrivenOutline)d+="|"+c;a.push({key:d,layer:e})}else if(e.type===l.StyleLayerType.LINE){f=e;d=e.paint;d=null!=d&&(null!=d["line-pattern"]||null!=d["line-dasharray"]);let g=
e.source+"|"+e.sourceLayer;g+="|"+(k?.visibility??"");g+="|"+e.minzoom;g+="|"+e.maxzoom;g+="|"+JSON.stringify(e.filter);g+="|"+(void 0!==k?k["line-cap"]:"");g+="|"+(void 0!==k?k["line-join"]:"");if(f.hasDataDrivenLine||d)g+="|"+c;b.push({key:g,layer:e})}++c}this._assignRefLayers(a);this._assignRefLayers(b)};h._assignRefLayers=function(a){a.sort((k,g)=>k.key<g.key?-1:k.key>g.key?1:0);let b,c;const f=a.length;for(let k=0;k<f;k++){const g=a[k];if(g.key===b)g.layer.refLayerId=c;else if(b=g.key,c=g.layer.id,
g.layer.type===l.StyleLayerType.FILL){if(!g.layer.getPaintProperty("fill-outline-color"))for(var d=k+1;d<f;d++){var e=a[d];if(e.key===b){if(e.layer.getPaintProperty("fill-outline-color")){a[k]=e;a[d]=g;c=e.layer.id;break}}else break}}else if(g.layer.type===l.StyleLayerType.LINE)for(d=g.layer,e=k+1;e<f;e++){const p=a[e];if(p.key!==b)break;const q=p.layer;if(d.canUseThinTessellation&&!q.canUseThinTessellation||!d.canUseThinTessellation&&(q.getPaintProperty("line-pattern")||q.getPaintProperty("line-dasharray")))d=
q,a[k]=p,a[e]=g,c=p.layer.id}}};h._create=function(a,b,c){b=1-1/(c.length+1)*(1+b);c=this._runningId++;switch(a.type){case "background":return new m.BackgroundStyleLayer(l.StyleLayerType.BACKGROUND,a,b,c);case "fill":return new m.FillStyleLayer(l.StyleLayerType.FILL,a,b,c);case "line":return new m.LineStyleLayer(l.StyleLayerType.LINE,a,b,c);case "symbol":return new m.SymbolStyleLayer(l.StyleLayerType.SYMBOL,a,b,c);case "raster":console.warn(`Unsupported vector tile raster layer ${a.id}`);case "circle":return new m.CircleStyleLayer(l.StyleLayerType.CIRCLE,
a,b,c)}};n._recreateLayer=function(a,b){switch(a.type){case "background":return new m.BackgroundStyleLayer(l.StyleLayerType.BACKGROUND,a,b.z,b.uid);case "fill":return new m.FillStyleLayer(l.StyleLayerType.FILL,a,b.z,b.uid);case "line":return new m.LineStyleLayer(l.StyleLayerType.LINE,a,b.z,b.uid);case "symbol":return new m.SymbolStyleLayer(l.StyleLayerType.SYMBOL,a,b.z,b.uid);case "raster":console.warn(`Unsupported vector tile raster layer ${a.id}`);case "circle":return new m.CircleStyleLayer(l.StyleLayerType.CIRCLE,
a,b.z,b.uid)}};return n}()});