// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.25/esri/copyright.txt for details.
//>>built
define("exports ../../../chunks/_rollupPluginBabelHelpers ../../../chunks/tslib.es6 ../../../core/quantityUtils ../../../core/accessorSupport/decorators/property ../../../core/accessorSupport/decorators/subclass ./SketchTooltipInfo".split(" "),function(a,g,c,l,d,h,k){a.DrawPointTooltipInfo=function(e){function f(b){b=e.call(this,b)||this;b.type="draw-point";return b}g._inheritsLoose(f,e);return f}(k.SketchTooltipInfo);c.__decorate([d.property()],a.DrawPointTooltipInfo.prototype,"type",void 0);c.__decorate([d.property()],
a.DrawPointTooltipInfo.prototype,"elevation",void 0);a.DrawPointTooltipInfo=c.__decorate([h.subclass("esri.views.interactive.tooltip.DrawPointTooltipInfo")],a.DrawPointTooltipInfo);a.DrawPolylineTooltipInfo=function(e){function f(b){b=e.call(this,b)||this;b.type="draw-polyline";return b}g._inheritsLoose(f,e);return f}(k.SketchTooltipInfo);c.__decorate([d.property()],a.DrawPolylineTooltipInfo.prototype,"type",void 0);c.__decorate([d.property()],a.DrawPolylineTooltipInfo.prototype,"elevation",void 0);
c.__decorate([d.property()],a.DrawPolylineTooltipInfo.prototype,"totalLength",void 0);c.__decorate([d.property()],a.DrawPolylineTooltipInfo.prototype,"viewType",void 0);a.DrawPolylineTooltipInfo=c.__decorate([h.subclass("esri.views.interactive.tooltip.DrawPolylineTooltipInfo")],a.DrawPolylineTooltipInfo);a.DrawPolygonTooltipInfo=function(e){function f(b){b=e.call(this,b)||this;b.type="draw-polygon";return b}g._inheritsLoose(f,e);return f}(k.SketchTooltipInfo);c.__decorate([d.property()],a.DrawPolygonTooltipInfo.prototype,
"type",void 0);c.__decorate([d.property()],a.DrawPolygonTooltipInfo.prototype,"elevation",void 0);c.__decorate([d.property()],a.DrawPolygonTooltipInfo.prototype,"area",void 0);c.__decorate([d.property()],a.DrawPolygonTooltipInfo.prototype,"viewType",void 0);a.DrawPolygonTooltipInfo=c.__decorate([h.subclass("esri.views.interactive.tooltip.DrawPolygonTooltipInfo")],a.DrawPolygonTooltipInfo);a.DrawRectangleTooltipInfo=function(e){function f(b){b=e.call(this,b)||this;b.type="draw-rectangle";b.xSize=l.zeroMeters;
b.ySize=l.zeroMeters;b.area=l.zeroSquareMeters;return b}g._inheritsLoose(f,e);return f}(k.SketchTooltipInfo);c.__decorate([d.property()],a.DrawRectangleTooltipInfo.prototype,"type",void 0);c.__decorate([d.property()],a.DrawRectangleTooltipInfo.prototype,"xSize",void 0);c.__decorate([d.property()],a.DrawRectangleTooltipInfo.prototype,"ySize",void 0);c.__decorate([d.property()],a.DrawRectangleTooltipInfo.prototype,"area",void 0);a.DrawRectangleTooltipInfo=c.__decorate([h.subclass("esri.views.interactive.tooltip.DrawRectangleTooltipInfo")],
a.DrawRectangleTooltipInfo);a.DrawCircleTooltipInfo=function(e){function f(b){b=e.call(this,b)||this;b.type="draw-circle";b.radius=null;b.xSize=null;b.ySize=null;b.area=l.zeroSquareMeters;return b}g._inheritsLoose(f,e);return f}(k.SketchTooltipInfo);c.__decorate([d.property()],a.DrawCircleTooltipInfo.prototype,"type",void 0);c.__decorate([d.property()],a.DrawCircleTooltipInfo.prototype,"radius",void 0);c.__decorate([d.property()],a.DrawCircleTooltipInfo.prototype,"xSize",void 0);c.__decorate([d.property()],
a.DrawCircleTooltipInfo.prototype,"ySize",void 0);c.__decorate([d.property()],a.DrawCircleTooltipInfo.prototype,"area",void 0);a.DrawCircleTooltipInfo=c.__decorate([h.subclass("esri.views.interactive.tooltip.DrawCircleTooltipInfo")],a.DrawCircleTooltipInfo);Object.defineProperties(a,{__esModule:{value:!0},[Symbol.toStringTag]:{value:"Module"}})});