// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.25/esri/copyright.txt for details.
//>>built
define("exports ../../../chunks/_rollupPluginBabelHelpers ../../../chunks/tslib.es6 ../../../core/Accessor ../../../core/Handles ../../../core/maybe ../../../core/accessorSupport/decorators/property ../../../core/arrayUtils ../../../core/accessorSupport/ensureType ../../../core/accessorSupport/decorators/subclass ../../../geometry/projection ../../../geometry/support/aaBoundingRect ../../../layers/support/layerUtils ../../ViewingMode ./TerrainConst ./terrainUtils".split(" "),function(d,p,e,D,E,q,
m,H,I,t,F,g,G,x,y,z){function A(b,a){return q.isSome(b)&&!b.spatialReference.equals(a)?F.projectWithoutEngine(b,b.spatialReference,a):b}d.ExtentHelper=function(b){function a(c){c=b.call(this,c)||this;c._handles=new E;return c}p._inheritsLoose(a,b);var k=a.prototype;k.initialize=function(){this._handles.add([this.layerViews.on("change",()=>this.notifyChange("stencilEnabledExtents"))])};k.destroy=function(){this._handles.destroy();this._handles=null};k._computeStencilEnabledExtents=function(){const c=
[];this.layerViews.forEach(f=>{f=f.layer;"IntegratedMeshLayer"===f.operationalLayerType&&null!=this.viewSpatialReference&&(f=A(f.fullExtent,this.viewSpatialReference),q.isSome(f)&&c.push(g.fromExtent(f)))});return c};p._createClass(a,[{key:"layerViewsExtent",get:function(){return this._computeLayerViewsExtent()}},{key:"tiledLayersExtent",get:function(){return this._computeTiledLayersExtent()}},{key:"stencilEnabledExtents",get:function(){return this._computeStencilEnabledExtents()}}]);return a}(D);
e.__decorate([m.property({readOnly:!0})],d.ExtentHelper.prototype,"layerViewsExtent",null);e.__decorate([m.property({readOnly:!0})],d.ExtentHelper.prototype,"tiledLayersExtent",null);e.__decorate([m.property({readOnly:!0})],d.ExtentHelper.prototype,"stencilEnabledExtents",null);e.__decorate([m.property()],d.ExtentHelper.prototype,"viewSpatialReference",void 0);e.__decorate([m.property()],d.ExtentHelper.prototype,"tilingScheme",void 0);e.__decorate([m.property()],d.ExtentHelper.prototype,"defaultTiledLayersExtent",
void 0);e.__decorate([m.property({constructOnly:!0})],d.ExtentHelper.prototype,"layers",void 0);e.__decorate([m.property({constructOnly:!0})],d.ExtentHelper.prototype,"layerViews",void 0);d.ExtentHelper=e.__decorate([t.subclass("esri.views.3d.terrain.ExtentHelper")],d.ExtentHelper);let u=function(b){function a(){return b.apply(this,arguments)||this}p._inheritsLoose(a,b);var k=a.prototype;k._computeLayerViewsExtent=function(){return this._globalExtent};k._computeTiledLayersExtent=function(){return this._globalExtent};
p._createClass(a,[{key:"_globalExtent",get:function(){return this.viewSpatialReference.isWebMercator?y.WEBMERCATOR_WORLD_EXTENT:y.GEOGRAPHIC_WORLD_EXTENT}}]);return a}(d.ExtentHelper);u=e.__decorate([t.subclass("esri.views.3d.terrain.ExtentHelperGlobal")],u);let w=function(b){function a(){return b.apply(this,arguments)||this}p._inheritsLoose(a,b);var k=a.prototype;k._computeLayerViewsExtent=function(){const c=g.empty(),f=this.viewSpatialReference;this.layerViews.forEach(h=>{const n=h.layer;!h.isResolved()||
"graphics"===n.type&&n.internal||(h=A("fullExtentInLocalViewSpatialReference"in h&&h.fullExtentInLocalViewSpatialReference||h.layer.fullExtent,f),g.expand(c,h,c))});const l=g.allFinite(c)?c:null,r=this._get("layerViewsExtent");return g.equals(l,r)?r:l};k._computeTiledLayersExtent=function(){const c=this.tilingScheme;if(!c)return null;const f=this.viewSpatialReference,l=g.empty();this.layers.forEach(n=>{if(n.loaded&&G.isTiledLayer(n)){const B=z.getTiledLayerInfo(n,f,x.ViewingMode.Local);if(!q.isNone(B)){var {tileInfo:C,
fullExtent:v}=B;q.isSome(C)&&q.isSome(v)&&(z.isProjectableRasterLayer(n)||c.compatibleWith(C)&&v.spatialReference.equals(c.spatialReference))&&g.expand(l,v,l)}}});g.expand(l,this.defaultTiledLayersExtent,l);const r=g.allFinite(l)?l:null,h=this._get("tiledLayersExtent");return g.equals(r,h)?h:r};return a}(d.ExtentHelper);w=e.__decorate([t.subclass("esri.views.3d.terrain.ExtentHelperLocal")],w);d.create=function(b,a){return b===x.ViewingMode.Global?new u(a):new w(a)};Object.defineProperties(d,{__esModule:{value:!0},
[Symbol.toStringTag]:{value:"Module"}})});