// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.25/esri/copyright.txt for details.
//>>built
define("exports ../../../chunks/_rollupPluginBabelHelpers ../../../core/maybe ./interfaces ./TerrainConst ./terrainUtils ./tileUtils".split(" "),function(q,r,g,u,B,C,D){let z=function(){function k(){}var b=k.prototype;b.init=function(a,h,d,e){this.tile=a;this._layerIdx=h;this._layerClass=d;this._suspended=e;this._tileLayerInfo=a.getLayerInfo(h,d);this._tileRequested=null;a=this._findAncestorWithData();this._setUpsampleTile(a)};b.startLoading=function(){return this._requestNext()};b.dispose=function(){this._tileRequested&&
(this._tileRequested.unrequestLayerData(this._layerIdx,this._layerClass,this),this._tileRequested=null);this._tileLayerInfo=this.tile=null};b.setSuspension=function(a){a!==this._suspended&&((this._suspended=a)?this._tileRequested&&(this._tileRequested.unrequestLayerData(this._layerIdx,this._layerClass,this),this._tileRequested=null):this._tileLayerInfo.data||this.update())};b.update=function(){const a=this._findAncestorWithData();this._setUpsampleTile(a);return this._requestNext()};b.dataArrived=
function(a){this._setUpsampleTile(a);this._tileRequested=null;a===this.tile?this.tile.updateRenderData(this._layerClass,u.TextureUpdate.FADING):this._requestNext()};b.dataMissing=function(){this._tileRequested=null;this._tileLayerInfo.data=null;this._requestNext()};b._agentDone=function(){this.tile.agentDone(this._layerIdx,this._layerClass);this.dispose()};b._requestNext=function(){if(this._suspended)return!0;const a=this._findNextDownload();if(this._tileRequested){if(a===this._tileRequested)return!0;
this._tileRequested.unrequestLayerData(this._layerIdx,this._layerClass,this);this._tileRequested=null}g.isSome(a)?a.requestLayerData(this._layerIdx,this._layerClass,this)&&(this._tileRequested=a):this._agentDone();return!!this._tileRequested};b._findNextDownload=function(){const a=this._layerIdx,h=this._layerClass;var d=this.tile.surface.layerViewByIndex(a,h);const e=C.getLayerWithExtentRange(d),{minLevel:v,maxLevel:E}=d.dataLevelRange;d=this._desiredMinLevelDelta;const F=this._progressiveLevelModulo+
d,G=this._scaleRangeEnabled?D.fallsWithinLayer:()=>!0;let c=this.tile;const m=c.level;let f;var l=this._tileLayerInfo.upsampleInfo;const w=g.isSome(l)?l.tile.level:-1;l=g.isSome(l)?w-m>=d:!1;const x=g.get(e,"tilemapCache");for(;c&&G(c,e,!1)&&c.level>=v;){const n=c.level,y=m-n,p=c.layerInfo[h][a];if(p.data&&y>=d){(!l||n>w)&&this._setUpsampleTile(c);p.dataInvalidated&&(f=c);break}if((g.isNone(x)||"unavailable"!==x.getAvailability(c.lij[0],c.lij[1],c.lij[2]))&&n<=E&&!p.data&&!p.dataMissing){if(g.isNone(f)||
c.level===v||0===n%B.PROGRESSIVE_LOADING_MODULO||m-f.level<d)f=c;if(y>=F)break}c=c.parent}g.isSome(f)&&m-f.level<d&&this._tileLayerInfo.upsampleInfo&&(f=null);return f};b._findAncestorWithData=function(){const a=this.tile.vlevel,h=this._desiredMinLevelDelta;let d;for(let e=this.tile;e;e=e.parent)if(e.hasLayerData(this._layerIdx,this._layerClass)){if(a-e.level>=h)return e;d=e}return d};b._setUpsampleTile=function(a){this._tileLayerInfo.setUpsampleInfo(this.tile,a);this.tile.updateRenderData(this._layerClass,
u.TextureUpdate.FADING)};r._createClass(k,[{key:"updating",get:function(){return!!this._tileRequested}},{key:"test",get:function(){return{findNextDownload:()=>this._findNextDownload(),tileLayerInfo:this._tileLayerInfo}}}]);return k}();var t=function(k){function b(){return k.apply(this,arguments)||this}r._inheritsLoose(b,k);b.prototype.dispose=function(){};r._createClass(b,[{key:"_desiredMinLevelDelta",get:function(){throw A;}},{key:"_progressiveLevelModulo",get:function(){throw A;}}]);return b}(z);
const A=Error("Abstract method called on TileAgent");t=new t;q.TILE_AGENT_DONE=t;q.TileAgent=z;Object.defineProperties(q,{__esModule:{value:!0},[Symbol.toStringTag]:{value:"Module"}})});