// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.25/esri/copyright.txt for details.
//>>built
define("exports ../../../../chunks/_rollupPluginBabelHelpers ../../../../chunks/tslib.es6 ../../../../core/Accessor ../../../../core/Evented ../../../../core/Handles ../../../../core/Logger ../../../../core/maybe ../../../../core/unitUtils ../../../../core/accessorSupport/decorators/property ../../../../core/arrayUtils ../../../../core/accessorSupport/ensureType ../../../../core/accessorSupport/decorators/subclass ../../../../chunks/vec3 ../../../../chunks/vec3f64 ../../../../geometry/support/aaBoundingBox ../../../../geometry/support/aaBoundingRect ../../../../symbols/support/unitConversionUtils ../../webgl-engine/lib/Intersector ../../webgl-engine/lib/IntersectorInterfaces".split(" "),
function(g,v,l,A,B,C,D,q,E,n,K,L,F,w,r,m,G,H,I,J){g.StageLayerElevationProvider=function(x){function p(a){a=x.call(this,a)||this;a._elevationOffset=0;a._layerHandes=new C;return a}v._inheritsLoose(p,x);var h=p.prototype;h.initialize=function(){this._renderCoordsHelper=this.view.renderCoordsHelper;this._intersectLayers=[this.stageLayer];this._intersector=I.newIntersector(this.view.state.viewingMode);this._intersector.options.store=J.StoreResults.MIN;var a=this._computeLayerExtent(this.spatialReference,
this.stageLayer);this._zmin=a[2];this._zmax=a[5];a=this.stageLayer.events;this._layerHandes.add([a.on("layerObjectAdded",b=>this._objectChanged(b.object)),a.on("layerObjectRemoved",b=>this._objectChanged(b.object)),a.on("objectGeometryAdded",b=>this._objectChanged(b.object)),a.on("objectGeometryRemoved",b=>this._objectChanged(b.object)),a.on("vertexAttrsUpdated",b=>this._objectChanged(b.object)),a.on("objectTransformation",b=>this._objectChanged(b))])};h.dispose=function(){this._layerHandes.destroy()};
h.elevationInfoChanged=function(){const a=null!=this.layer?this.layer.elevationInfo:null;if(null!=a&&"on-the-ground"!==a.mode){const b=E.getMetersPerVerticalUnitForSR(this.layer.spatialReference),c=H.getMetersPerUnit(a.unit);this._elevationOffset=q.unwrapOr(a.offset,0)*c/b}else this._elevationOffset=0};h.getElevation=function(a,b,c,k){d[0]=a;d[1]=b;d[2]=c;if(!this._renderCoordsHelper.toRenderCoords(d,k,d))return D.getLogger(this.declaredClass).error("could not project point for elevation alignment"),
null;a=this._elevationOffset;b=this._zmin+a;this._renderCoordsHelper.setAltitude(y,this._zmax+a,d);this._renderCoordsHelper.setAltitude(z,b,d);this._intersector.reset(y,z,null);this._intersector.intersect(this._intersectLayers,null,1,null,e=>e.metadata&&e.metadata.isElevationSource);return this._intersector.results.min.getIntersectionPoint(d)?this._renderCoordsHelper.getAltitude(d):null};h._objectChanged=function(a){const b=this.spatialReference;if(a.metadata?.isElevationSource&&!q.isNone(b)){m.empty(f);
var {lastValidElevationBB:c}=a.metadata;c.isEmpty()||this._expandExtent(b,c.min,c.max,f);var {min:k,max:e}=a.boundingVolumeWorldSpace;this._expandExtent(b,k,e,f);m.toRect(f,t);this._zmin=Math.min(this._zmin,f[2]);this._zmax=Math.max(this._zmax,f[5]);u.extent=t;u.spatialReference=b;this.emit("elevation-change",u);w.copy(c.min,k);w.copy(c.max,e)}};h._computeLayerExtent=function(a,b){m.empty(f);q.isSome(a)&&b.objects.forAll(c=>this._expandExtent(a,c.boundingVolumeWorldSpace.min,c.boundingVolumeWorldSpace.max,
f));return f};h._expandExtent=function(a,b,c,k){for(let e=0;8>e;++e)d[0]=e&1?b[0]:c[0],d[1]=e&2?b[1]:c[1],d[2]=e&4?b[2]:c[2],this._renderCoordsHelper.fromRenderCoords(d,d,a),m.expandWithVec3(k,d);return k};v._createClass(p,[{key:"spatialReference",get:function(){return this.view?.spatialReference}}]);return p}(B.EventedMixin(A));l.__decorate([n.property({constructOnly:!0})],g.StageLayerElevationProvider.prototype,"layer",void 0);l.__decorate([n.property({constructOnly:!0})],g.StageLayerElevationProvider.prototype,
"stageLayer",void 0);l.__decorate([n.property({constructOnly:!0})],g.StageLayerElevationProvider.prototype,"view",void 0);l.__decorate([n.property()],g.StageLayerElevationProvider.prototype,"spatialReference",null);g.StageLayerElevationProvider=l.__decorate([F.subclass("esri.views.3d.layers.support.StageLayerElevationProvider")],g.StageLayerElevationProvider);const f=m.empty(),t=G.empty(),u={spatialReference:null,extent:t,context:"scene"},d=r.create(),y=r.create(),z=r.create();Object.defineProperties(g,
{__esModule:{value:!0},[Symbol.toStringTag]:{value:"Module"}})});